// The typed test-id registry (UI-Gates §11.5): freeform `data-testid` strings let a typo silently
// break an e2e selector; a typed map makes the typo a `tsc` error on BOTH sides (the component
// stamping the id and the Playwright test selecting it). Add ids HERE, never inline — grow the map
// as surfaces land. Values are the literal DOM attribute strings (kebab-case, stable API for e2e).

export const TEST_IDS = {
  appShell: "app-shell",
  loginPage: "login-page",
  loginLocalForm: "login-local-form",
  loginHandle: "login-handle",
  loginPassword: "login-password",
  loginSubmit: "login-submit",
  loginError: "login-error",
  loginOidc: "login-oidc",
  accountSurface: "account-surface",
  accountLogout: "account-logout",
  firstRunPersonaDialog: "first-run-persona-dialog",
  firstRunPersonaName: "first-run-persona-name",
  firstRunPersonaCreate: "first-run-persona-create",
  adminUsersSection: "admin-users-section",
  adminCreateUserButton: "admin-create-user",
  adminCreateUserDialog: "admin-create-user-dialog",
  adminCreateUserSubmit: "admin-create-user-submit",
  adminSessionsDialog: "admin-sessions-dialog",
  adminResetPasswordDialog: "admin-reset-password-dialog",
  adminResetPasswordSubmit: "admin-reset-password-submit",
  adminEnginesSection: "admin-engines-section",
  composer: "composer",
  composerSend: "composer-send",
  composerWand: "composer-wand",
  speakAsSelect: "speak-as-select",
  messageList: "message-list",
  chatCastBar: "chat-cast-bar",
  notificationsInbox: "notifications-inbox",
  workloadsSection: "workloads-section",
  workloadsRunButton: "workloads-run-button",
  backupSection: "backup-section",
  backupExportButton: "backup-export-button",
  backupImportDropzone: "backup-import-dropzone",
  importReport: "import-report",
  importOnboardingCard: "import-onboarding-card",
  importOnboardingUpload: "import-onboarding-upload",
  importOnboardingDismiss: "import-onboarding-dismiss",
  runWorkloadDialog: "run-workload-dialog",
  runWorkloadSubmit: "run-workload-submit",
  workloadsSchedulesSection: "workloads-schedules-section",
  scheduleCreateButton: "schedule-create-button",
  createScheduleDialog: "create-schedule-dialog",
  createScheduleSubmit: "create-schedule-submit",
  editScheduleDialog: "edit-schedule-dialog",
  editScheduleSubmit: "edit-schedule-submit",
  membersPanel: "members-panel",
  invitePeopleButton: "invite-people-button",
  inviteDialog: "invite-dialog",
  inviteHandleInput: "invite-handle-input",
  inviteSubmit: "invite-submit",
  inviteCopyLink: "invite-copy-link",
  inviteLinkResult: "invite-link-result",
  inviteOutstandingList: "invite-outstanding-list",
  joinInviteDialog: "join-invite-dialog",
  joinInviteConfirm: "join-invite-confirm",
  corpusListSurface: "corpus-list-surface",
  corpusSearchInput: "corpus-search-input",
  corpusSearchTarget: "corpus-search-target",
  corpusSearchResults: "corpus-search-results",
  corpusSearchHit: "corpus-search-hit",
  corpusDiscoverEvidence: "corpus-discover-evidence",
  corpusBrowseView: "corpus-browse-view",
  corpusBrowseRow: "corpus-browse-row",
  corpusHomeSurface: "corpus-home-surface",
  corpusDossierSurface: "corpus-dossier-surface",
  corpusAskInput: "corpus-ask-input",
  corpusAskSubmit: "corpus-ask-submit",
  corpusContextMap: "corpus-context-map",
  corpusCompareTab: "corpus-compare-tab",
  corpusCompareDeep: "corpus-compare-deep",
  corpusVisualsTab: "corpus-visuals-tab",
  corpusFacetDrill: "corpus-facet-drill",
  corpusKeywordExplorer: "corpus-keyword-explorer",
  corpusThemesDrill: "corpus-themes-drill",
  corpusSearchSuggest: "corpus-search-suggest",
  analyticsListSurface: "analytics-list-surface",
  analyticsLeaderboardRow: "analytics-leaderboard-row",
  analyticsLeaderboardSort: "analytics-leaderboard-sort",
  analyticsOverviewSurface: "analytics-overview-surface",
  analyticsCharacterSurface: "analytics-character-surface",
  analyticsModelsTab: "analytics-models-tab",
  analyticsTimeTab: "analytics-time-tab",
  analyticsPersonasTab: "analytics-personas-tab",
} as const;

export type TestIdKey = keyof typeof TEST_IDS;

/** `<div data-testid={testId("appShell")}>` / `page.getByTestId(testId("appShell"))`. */
export function testId(key: TestIdKey): (typeof TEST_IDS)[TestIdKey] {
  return TEST_IDS[key];
}
