// Reviewed grants: z-index-tier-permission, skin-fragment-tier-permission, pointer-capability-tier-permission, query-freshness-coverage, query-machine-seals....
// Split from reviewed-grants.ts — see that file for the central home comment.
import type { ReviewedGateGrant } from "../contract/gate-authority.ts";

export const REVIEWED_GRANTS_Z_TO_CITATIONS: readonly ReviewedGateGrant[] = [
  {
    id: "z-index-tier-permission:markdown",
    policyId: "z-index-tier-permission",
    subject: "packages/ui/src/markdown/",
    operation: "spell-z-index-tier",
    why: "the markdown renderer maps prose surfaces onto the shared stacking vocabulary at this reviewed home.",
    endsWhen: "markdown uses token-only composition or moves to a different structural home.",
  },
  {
    id: "skin-fragment-tier-permission:lib",
    policyId: "skin-fragment-tier-permission",
    subject: "packages/ui/src/lib/",
    operation: "spell-skin-fragment-tier",
    why: "this is the canonical definition home for shared focus, scrim, arrow, touch-target and disabled fragments.",
    endsWhen: "the shared fragments move to a different canonical definition home.",
  },
  {
    id: "pointer-capability-tier-permission:app-shell",
    policyId: "pointer-capability-tier-permission",
    subject: "packages/client/src/features/app-shell/",
    operation: "spell-pointer-capability-tier",
    why: "app-shell is the reviewed feature home that owns device-capability adaptation for the product shell.",
    endsWhen: "device-capability adaptation moves completely into shared tokens or a different shell home.",
  },
  {
    id: "query-freshness-coverage:assets-resolveblobrefs",
    policyId: "query-freshness-coverage",
    subject: "assets.resolveBlobRefs",
    operation: "uncovered-query-freshness",
    why: "the OWNER-scoped twin of `assets.resolveChatBlobRefs` below, same content-addressed argument: keyed by the requested asset ids over CONTENT-ADDRESSED blobs (features/imagery/components/image-detail-body.tsx resolves hash+mime to build the set-as-background source). An asset's hash never changes — `packages/server/src/domain/assets/` carries ZERO `update(assets)` sites, and a re-upload mints a NEW id (D21), so a change produces a new key rather than a stale answer. A DELETED asset drops out of the owner join and the frozen entry can only hand back a hash the server's own ownership gate then refuses — a refused write, never a wrong one.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:assets-resolvechatblobrefs",
    policyId: "query-freshness-coverage",
    subject: "assets.resolveChatBlobRefs",
    operation: "uncovered-query-freshness",
    why: "keyed by (chatId, the row's asset ids) over CONTENT-ADDRESSED blobs (features/chat/hooks/attachment-url-provider.tsx): the hash behind an assetId never changes, so the resolved map is immutable for its key.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:settings-getversion",
    policyId: "query-freshness-coverage",
    subject: "settings.getVersion",
    operation: "uncovered-query-freshness",
    why: "the box's own build/checkout identity (features/user-admin/components/about-section.tsx), read once with useSuspenseQuery and never mutated by any write path in this process — nothing on the bus or in the mutation seam ever changes which commit is running, so no invalidation row could ever fire.",
    endsWhen: "the version identity becomes hot-swappable within a running process (a live redeploy signal), or the query gains reachable seam coverage.",
  },
  {
    id: "query-freshness-coverage:settings-checkforupdate",
    policyId: "query-freshness-coverage",
    subject: "settings.checkForUpdate",
    operation: "uncovered-query-freshness",
    why: "the MANUAL GitHub update check (features/user-admin/components/about-section.tsx): `enabled: false` plus an explicit button-triggered `refetch()` IS the whole freshness mechanism (see the component header) — no mount fetch, no poll, no persisted verdict to go stale, so there is no mutation event this query could ever be invalidated by.",
    endsWhen: "the update check becomes automatic (a poll or a persisted verdict), or the query gains reachable seam coverage.",
  },
  {
    id: "query-freshness-coverage:chat-getvariantwire",
    policyId: "query-freshness-coverage",
    subject: "chat.getVariantWire",
    operation: "uncovered-query-freshness",
    why: "keyed by (chatId, variantId) over a COMMITTED variant's stamped generation record (features/chat/components/variant-wire-viewer.tsx). A variant's prompt/params/draws are written once at commit and never updated: an edit mints a new variant and a swipe APPENDS one, so a new key is what a change produces — the old key's answer stays true forever. Deleting the message makes the key resolve NOT_FOUND, which the viewer renders as its typed gone-arm.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:imagery-readprovenance",
    policyId: "query-freshness-coverage",
    subject: "imagery.readProvenance",
    operation: "uncovered-query-freshness",
    why: "keyed by assetId over a WRITE-ONCE generation record (features/imagery/components/provenance-strip.tsx — the lightbox's prompt/model/mode/cost strip). The `imagery_generations` row is stamped at generation and never updated: `packages/server/src/` carries ZERO `update(imageryGenerations)` sites, and an EDIT mints a new asset with its own new row (`edited:true`), so a change produces a NEW key — the old key's answer stays true forever (the `chat.getVariantWire` argument, same shape). A non-generated or foreign asset resolves `null` through the owner join, which the strip renders as its typed no-details arm.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:search-search",
    policyId: "query-freshness-coverage",
    subject: "search.search",
    operation: "uncovered-query-freshness",
    why: "input-keyed live search (features/discovery/components/corpus-search-results.tsx) — the query text + `over` target are part of the key, so every new search is a cold fetch of a NEW cache entry.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:search-fields",
    policyId: "query-freshness-coverage",
    subject: "search.fields",
    operation: "uncovered-query-freshness",
    why: "input-keyed BM25 lexical search (same surface) — the query string is part of the key; re-running the identical query inside gcTime correctly returns the same corpus answer.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:search-suggest",
    policyId: "query-freshness-coverage",
    subject: "search.suggest",
    operation: "uncovered-query-freshness",
    why: "input-keyed prefix suggest (features/discovery/surfaces/corpus-list-surface.tsx) — keyed by the deferred query text, gated on a minimum length; each keystroke is its own key.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:chat-checksendavailability",
    policyId: "query-freshness-coverage",
    subject: "chat.checkSendAvailability",
    operation: "uncovered-query-freshness",
    why: "carries its OWN finite staleTime (AVAILABILITY_STALE_MS = 15s, features/chat/hooks/use-send-availability.ts). The fact it reads (an engine coming up, a key being added) has NO producer to emit an event; that documented 15s window is the driver, and the file explains why a poll/focus-refetch was rejected.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:admin-vllmengines",
    policyId: "query-freshness-coverage",
    subject: "admin.vllmEngines",
    operation: "uncovered-query-freshness",
    why: "POLLS: features/user-admin/components/admin-engines-section.tsx sets a status-adaptive `refetchInterval` (fast while an engine is mid-transition, slow at steady state) — an engine's liveness is a machine fact no bus announces.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:notifications-presence",
    policyId: "query-freshness-coverage",
    subject: "notifications.presence",
    operation: "uncovered-query-freshness",
    why: "POLLS (#1039): features/chat/hooks/use-roster-presence.ts sets `refetchInterval = PRESENCE_POLL_MS` (20s) beside a finite 10s staleTime, and the hook's header argues the choice — presence has NO bus (the registry is a ref-count over open sockets with no event and no fan-out), the roster it decorates is itself a query, and the server debounces disconnects behind a 15s grace window, so a sub-second driver could not see a change sooner than the poll does. The `admin.vllmEngines` shape exactly: a machine liveness fact nothing announces. The row goes STALE-RED the day presence grows a bus member and the seam gains its filter, which is the intended end condition.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:notifications-list",
    policyId: "query-freshness-coverage",
    subject: "notifications.list",
    operation: "uncovered-query-freshness",
    why: "driven by the durable inbox SSE adapter (features/notifications/hooks/use-inbox-stream.ts) — every arrival AND every transition into the live state calls invalidation.invalidateFilters([notifications.list]); the bell's own mark-read/dismiss mutations `invalidates` it too.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:workloads-list",
    policyId: "query-freshness-coverage",
    subject: "workloads.list",
    operation: "uncovered-query-freshness",
    why: "driven by the per-row workload SSE adapter (features/workloads/hooks/use-workload-stream.ts) — every non-progress event (state change, error, reconnect) invalidates the list through the seam; `progress` stays a row-local buffer by design.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:workloads-listschedules",
    policyId: "query-freshness-coverage",
    subject: "workloads.listSchedules",
    operation: "uncovered-query-freshness",
    why: "writer-local — the four schedule mutations (features/workloads/hooks/use-workload-mutations.ts) each `invalidates` it. Schedules are per-user and edited from exactly one pane; no second producer can change them behind it.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:admin-listusers",
    policyId: "query-freshness-coverage",
    subject: "admin.listUsers",
    operation: "uncovered-query-freshness",
    why: "writer-local — every admin user write (features/user-admin/hooks/use-admin-mutations.ts) `invalidates` it. The writes land on OTHER users' rows, so the actor's own user-bus never carries them (the hook's own header); the mutation is the only possible driver.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:admin-listsessions",
    policyId: "query-freshness-coverage",
    subject: "admin.listSessions",
    operation: "uncovered-query-freshness",
    why: "writer-local — the session revoke/reset/kill mutations (features/user-admin/hooks/use-admin-mutations.ts) each `invalidates` it; another user's session lifecycle reaches this admin's bus through nothing.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:settings-getappsettings",
    policyId: "query-freshness-coverage",
    subject: "settings.getAppSettings",
    operation: "uncovered-query-freshness",
    why: "writer-local — AppSettings is admin-only and emits no user-bus event; both writers (`useUpdateAppSettings`/`useUpdateAppOverrides` in features/user-admin/hooks/use-admin-mutations.ts and the system-settings surface's own mutation) `invalidates` it.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:settings-getappsettingswithoverrides",
    policyId: "query-freshness-coverage",
    subject: "settings.getAppSettingsWithOverrides",
    operation: "uncovered-query-freshness",
    why: "writer-local — the floor-vs-override read of the admin tuning sections; its sole writer `useUpdateAppOverrides` invalidates it alongside `getAppSettings` (same admin-only, bus-less write path).",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:invites-listinvites",
    policyId: "query-freshness-coverage",
    subject: "invites.listInvites",
    operation: "uncovered-query-freshness",
    why: "writer-local — the invite create/revoke mutations (features/chat/hooks/use-invite-mutations.ts) `invalidates` the list, and it is the inviting host's own dialog surface (nobody else's action adds a link).",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:rpg-listcheckpoints",
    policyId: "query-freshness-coverage",
    subject: "rpg.listCheckpoints",
    operation: "uncovered-query-freshness",
    why: "writer-local — create/restore checkpoint (features/rpg/hooks/use-rpg-mutations.ts) each `invalidates` it. Marks are HOST-only and written from this one pane, so the acting tab is the only tab that can be stale.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:assets-listgallery",
    policyId: "query-freshness-coverage",
    subject: "assets.listGallery",
    operation: "uncovered-query-freshness",
    why: "writer-local — add/remove gallery art (features/chat/hooks/use-character-gallery.ts) `invalidates` it; the gallery dialog is the only writer of the junction it reads.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:assets-listowned",
    policyId: "query-freshness-coverage",
    subject: "assets.listOwned",
    operation: "uncovered-query-freshness",
    why: "driven by the upload front door `useUploadAsset` (data/use-upload-asset.ts) — every completed upload calls invalidation.invalidateFilters([trpc.assets.listOwned.pathFilter()]). The upload route is a raw multipart POST, not a tRPC mutation, so it can carry no `invalidates` and no bus event announces it; the hook IS the driver, and every feature upload (character/persona avatars, backgrounds, chat attachments) goes through it. Proven by tests/client/data/use-upload-asset.ct.tsx (the mounted listOwned read refetches after an upload).",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:automation-listrules",
    policyId: "query-freshness-coverage",
    subject: "automation.listRules",
    operation: "uncovered-query-freshness",
    why: "TWO feature-local drivers (blind spot 4). (1) Every rule-lifecycle mutation `invalidates` it — setRuleEnabled/deleteRule/runRuleNow/createRuleFromPreset in features/automation/lib/rule-mutations.ts all carry trpc.automation.listRules.queryFilter({chatId}). (2) The REMOTE-fire edge, which no mutation can see: rules-section.tsx's `useRuleFeedInvalidation` joins the chat's `automation` bus room and calls invalidation.invalidateFilters([listRules.queryFilter]) on ruleFired/ruleErrored/ruleAutoDisabled/rulesChanged, so a rule firing from a real turn moves `enabled`/`lastFiredAt`/`lastError` without a local write. Proven by tests/client/features/automation/components/rules-section.ct.tsx (toggle/Test/Run-now each drive the proc and the list reconciles).",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:automation-listfires",
    policyId: "query-freshness-coverage",
    subject: "automation.listFires",
    operation: "uncovered-query-freshness",
    why: "Same TWO drivers as automation.listRules, keyed by ruleId: testRule/runRuleNow `invalidates` trpc.automation.listFires.queryFilter({ruleId}) (rule-mutations.ts), and the automation-room feed in rules-section.tsx invalidates the fired rule's log on ruleFired/ruleErrored. This is the host's 'why didn't my rule fire' log, so the REMOTE edge is the one that matters — a bus-driven fire is exactly the row it exists to show.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:automation-listownerrules",
    policyId: "query-freshness-coverage",
    subject: "automation.listOwnerRules",
    operation: "uncovered-query-freshness",
    why: "C5's owner-GLOBAL rule list, and it has exactly ONE driver where its per-chat twin has two (blind spot 4). (1) Every rule-lifecycle mutation `invalidates` it — the same five verbs drive both surfaces, and `ruleListFilter` in features/automation/lib/rule-mutations.ts maps a `chatId: null` scope onto trpc.automation.listOwnerRules.queryFilter(). (2) There is NO remote-fire edge, and that is a structural fact rather than a gap this cite is hiding: `AutomationBusEvent` is the per-CHAT feedback bus (every member carries a chatId; transport/trpc/stream/sources/automation.ts fans it to one chat's subscribers), so a chat-less rule's fire reaches no subscriber and there is no channel a bus row could ride. The durable fire LOG under each row is what answers 'did it run', and it is re-read on open. Ends the day an owner-plane bus member exists (it would need its own producer belt, coverage sites and a per-USER stream source).",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:automation-getownerbudgets",
    policyId: "query-freshness-coverage",
    subject: "automation.getOwnerBudgets",
    operation: "uncovered-query-freshness",
    why: "C5's owner-GLOBAL fire-rate ceiling. Its ONLY writer is `setOwnerBudgets`, which `invalidates` trpc.automation.getOwnerBudgets.queryFilter() (features/automation/lib/owner-budget-mutations.ts) — a single-owned belt row nothing else can move: no other principal may write it (the plane is keyed by the caller's own userId) and no bus event touches it. Same no-remote-edge argument as automation.listOwnerRules above.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:automation-listrulepresets",
    policyId: "query-freshness-coverage",
    subject: "automation.listRulePresets",
    operation: "uncovered-query-freshness",
    why: "IMMUTABLE for the session: the rule-preset catalogue is a pure projection of a compile-time Record (domain/automation/contract/presets.ts via verbs/list-rule-presets.ts — no principal, no chat, no db, per its own header). It cannot change without a deploy, so no bus row is warranted and no mutation can move it; the picker refetching it would answer identically forever.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:plugin-list",
    policyId: "query-freshness-coverage",
    subject: "plugin.list",
    operation: "uncovered-query-freshness",
    why: "writer-local — the plugin lifecycle has no bus event (no plugin room; `plugin.list` is a per-owner catalog read), and all four writers `invalidates` it: install/upgrade/setEnabled/uninstall in features/plugin/lib/plugin-mutations.ts each carry trpc.plugin.list.queryFilter(). The SINGLE-WRITER claim rests on OWNERSHIP, not on a role gate (D147, restated 2026-08-24 when plugins went user-scoped and the admin gate came off the verbs): a `plugins` row is stamped ownerId = the installing principal, every management verb loads it through the owner-scoped getById(db, caller.userId, pluginId), and there is no admin any-row branch — so the only principal who can move this catalog is the one reading it, in the tab that issued the write. Proven by the cross-tenant sweep's four plugin probes (a stranger holding the owner's real pluginId gets NOT_FOUND from upgrade/setGrant/setEnabled/uninstall).",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:plugin-listsurfaces",
    policyId: "query-freshness-coverage",
    subject: "plugin.listSurfaces",
    operation: "uncovered-query-freshness",
    why: "writer-local, SAME class as `plugin.list` above (plugin-ui-plane #679 U1) — the resident surface SET is a projection of the plugin lifecycle, which has NO bus event (no plugin room). A plugin's surfaces come and go only on the owner-scoped lifecycle writes that move whether/what it runs: setEnabled brings a plugin's registrations resident or drops them, upgrade swaps the bundle (a different surface set), uninstall removes them — and each of those three `invalidates` trpc.plugin.listSurfaces.queryFilter() in features/plugin/lib/plugin-mutations.ts. (install lands the row `disabled` with nothing resident, so it needs no listSurfaces invalidate — the covering setEnabled does.) The ownership single-writer argument is identical to plugin.list's: registrations are stamped through the owner-scoped plugin row, no admin any-row branch, so the only principal who can move this set is the one reading it in the tab that issued the write. NOTE the per-surface STATE read `plugin.getSurfaceState` is DIFFERENT — it IS bus-driven (`pluginSurfaceStateChanged`, host.ui.setState) and lives in the seam, not here; only the registration LIST is writer-local. Proven by tests/client/features/plugin/components/plugin-surface-renderer.ct.tsx (the affinity-tracker panel renders from listSurfaces and round-trips).",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:plugin-listcommands",
    policyId: "query-freshness-coverage",
    subject: "plugin.listCommands",
    operation: "uncovered-query-freshness",
    why: "writer-local, the EXACT twin of `plugin.listSurfaces` above (plugin-ui-plane #679 U5) — a plugin's registered COMMAND set is the same projection of the same resident instance, collected by the same activation and dropped by the same deactivate. It moves only on the owner-scoped lifecycle writes that move whether/what a plugin runs, and the same three carry it: setEnabled (activation collects the commands, disable drops them), upgrade (a new bundle registers a different set) and uninstall each `invalidates` trpc.plugin.listCommands.queryFilter() in features/plugin/lib/plugin-mutations.ts. (install lands the row `disabled` with nothing resident, so the covering setEnabled is the one that matters.) The ownership single-writer argument is identical: registrations are stamped through the owner-scoped plugin row, there is no admin any-row branch, so the only principal who can move this set is the one reading it in the tab that issued the write. Its two READERS are always-mounted chrome — the `/plugin` composer dispatcher and the Plugins wand menu — which is precisely why it is cited here rather than left uncovered: a frozen command list is a menu that lists a plugin a person just uninstalled. Proven by tests/server/domain/plugin/verbs/list-commands.int.test.ts (enable/disable each move the projection) and tests/server/entry/boot/seed-example-plugins.int.test.ts (a REAL activation over the WASM runtime registers the oracle deck's two commands).",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:plugin-listdistributed",
    policyId: "query-freshness-coverage",
    subject: "plugin.listDistributed",
    operation: "uncovered-query-freshness",
    why: "writer-local, and more strictly than its siblings: the PUBLISHED set (D147 clause (d)) has exactly two movers and both are admin verbs this same surface issues — `installForAllUsers` and `uninstallForAllUsers` in features/plugin/lib/plugin-mutations.ts each carry trpc.plugin.listDistributed.queryFilter(). Nothing else can move it: it is DEPLOYMENT POLICY rather than anyone's data, so no per-user act (an install, an uninstall, an upgrade of somebody's own copy) touches the record, and there is no bus channel for the same reason plugin.list has none (no plugin room). The one un-covered edge is a SECOND admin publishing from another session, which is the ordinary two-operators-one-console case this table already accepts for the admin.* reads above — and the section re-reads on open.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:plugin-listdisplaytransforms",
    policyId: "query-freshness-coverage",
    subject: "plugin.listDisplayTransforms",
    operation: "uncovered-query-freshness",
    why: "writer-local, the EXACT class as `plugin.listSurfaces` above (plugin-ui-plane seam 14, U6) — a plugin's registered DISPLAY transforms are a projection of the same resident instance, so the same three owner-scoped lifecycle writes move them and the same three already `invalidates` the sibling key: setEnabled brings a plugin's registrations resident or drops them, upgrade swaps the bundle, uninstall removes them (features/plugin/lib/plugin-mutations.ts). The ownership single-writer argument is identical (D147: no admin any-row branch, so the only principal who can move this set is the one reading it, in the tab that issued the write). It is deliberately not folded into `listSurfaces`: its ONE job is the per-row BYTE-IDENTITY gate — a viewer with no display transforms must learn so in one room-level query and make zero per-row calls — and a key that answers a cost question wants to be independently cacheable. Proven by tests/server/domain/plugin/verbs/list-display-transforms.int.test.ts (a disabled plugin contributes none; a stranger sees none).",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:plugin-transformfordisplay",
    policyId: "query-freshness-coverage",
    subject: "plugin.transformForDisplay",
    operation: "uncovered-query-freshness",
    why: "STATIC by CONSTRUCTION, and the strongest form of it in this table: the key CARRIES its own content identity. Its input is `(chatId, messageId, text)` where `text` is the row as this viewer's client has already rendered it, and the answer is a pure function of that input plus the viewer's registered transforms — so an edit, a swipe, or a macro re-resolve produces a DIFFERENT key rather than a stale entry, and a repaint of the same bytes correctly resolves from cache (which is the point: the round-trip is per visible ROW, and a freshness driver that refetched it would be a transcript-wide query storm). The one thing that can change the ANSWER for an unchanged key is the transform SET moving, which is exactly the sibling key above — and that key's own three writers already repaint the surface that consumes this one. Proven by tests/server/domain/plugin/verbs/transform-for-display.int.test.ts.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:plugin-listbundleassets",
    policyId: "query-freshness-coverage",
    subject: "plugin.listBundleAssets",
    operation: "uncovered-query-freshness",
    why: "writer-local, and the NARROWEST member of the plugin family above (#820 seam 11) — the `ui/assets/` path → CAS-id map is a projection of the INSTALLED BUNDLE, so exactly one act can move it for an existing key: an UPGRADE, which replaces the bundle-asset set wholesale (clear-then-insert in `applyUpgrade`). Both upgrade mutations carry it — `useUpgradePlugin` and `useUpgradePluginFromStoredUrl` in features/plugin/lib/plugin-mutations.ts each `invalidates` trpc.plugin.listBundleAssets.queryFilter(). The other lifecycle acts CANNOT produce a stale answer for a live key: install mints a NEW pluginId (a new key, a cold fetch), uninstall removes the row and unmounts every surface that could read it, and setEnabled/setGrant move residency and consent without touching the zip. The ownership single-writer argument is identical to plugin.list's (D147: the map is read through the owner-scoped `getById`, there is no admin any-row branch, so the only principal who can move it is the one reading it in the tab that issued the write). Staleness here is BOUNDED and non-leaking by construction even if a driver were missed: a dropped path resolves to nothing and paints the node's placeholder, and every id the map yields still rides the owner-scoped `assets.resolveBlobRefs`, so a frozen map can show LESS art, never another owner's. Proven by tests/client/features/plugin/components/plugin-surface-renderer.ct.tsx (a shipped path paints; one the plugin never shipped stays a placeholder and never poisons the resolve set) and tests/server/domain/plugin/verbs/upgrade.int.test.ts (the set is replaced, not merged).",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-freshness-coverage:plugin-getlog",
    policyId: "query-freshness-coverage",
    subject: "plugin.getLog",
    operation: "uncovered-query-freshness",
    why: "writer-local — the host.log ring only moves when the plugin RUNS, and the two client acts that can start a run both `invalidates` it: setEnabled (activation logs, or fails and writes lastError) and upgrade (a re-activation on the new bundle) in features/plugin/lib/plugin-mutations.ts carry trpc.plugin.getLog.queryFilter({pluginId}). A run triggered by a chat event moves it with no client act, and that edge is DELIBERATELY not covered here: the log is a disclosure the owner opens on demand, so it refetches when opened rather than streaming — the frozen-tab class this gate guards needs a MOUNTED read, and this one is mounted only inside its own Collapsible.",
    endsWhen: "the query gains reachable seam coverage, is no longer consumed, or the cited independent driver changes",
  },
  {
    id: "query-machine-seals:create-entity-mutation",
    policyId: "query-machine-seals",
    subject: "packages/client/src/data/create-entity-mutation.ts",
    operation: "raw-useMutation-import",
    why: "The canonical mutation factory owns the one raw useMutation import behind every client entity mutation.",
    endsWhen: "the factory stops importing useMutation, moves, or another raw mutation home is introduced",
  },
  {
    id: "query-machine-seals:create-collection-surface",
    policyId: "query-machine-seals",
    subject: "packages/client/src/data/create-collection-surface.ts",
    operation: "raw-useInfiniteQuery-import",
    why: "The canonical collection factory owns the one raw useInfiniteQuery import behind every paginated browse surface.",
    endsWhen: "the factory stops importing useInfiniteQuery, moves, or another raw infinite-query home is introduced",
  },
  {
    id: "query-machine-seals:ct-stories",
    policyId: "query-machine-seals",
    subject: "tests/client/lib/_ct-stories.tsx",
    operation: "raw-useMutation-import",
    why: "The CT story reproduces the app MutationCache error-toast channel and must drive a raw mutation without inserting the production entity-mutation belt into the behavior under test.",
    endsWhen: "the CT story stops importing useMutation or the tested global mutation-error channel moves to a different harness",
  },
  {
    id: "dangling-ref-citations:tooling-src-verify-ops-gen-density-ts",
    policyId: "dangling-ref-citations",
    subject: "tooling/src/verify/ops/gen/density.ts",
    operation: "dangling-path-cite",
    why: "density generator was restructured into tooling/src/verify/gates/density-tier.ts + lib/density-tier.ts; the law doc still names the pre-restructure path",
    endsWhen:
      "the owning doc (UI-Density-Law.md) is repaired to repoint, strike, or rider this reference; the finding disappears and central zero-use reconciliation stales this row.",
  },
  {
    id: "dangling-ref-citations:tooling-src-snap-ops-lighthouse-ts",
    policyId: "dangling-ref-citations",
    subject: "tooling/src/snap/ops/lighthouse.ts",
    operation: "dangling-path-cite",
    why: "lighthouse op moved to tooling/src/snap/ops/arms/lighthouse.ts; the retirement design doc names the pre-move path as the historical shape it describes",
    endsWhen:
      "the owning doc (1195-devtools-mcp-retirement.md) is repaired to repoint, strike, or rider this reference; the finding disappears and central zero-use reconciliation stales this row.",
  },
  {
    id: "dangling-ref-citations:tooling-src-snap-ops-request-log-ts",
    policyId: "dangling-ref-citations",
    subject: "tooling/src/snap/ops/request-log.ts",
    operation: "dangling-path-cite",
    why: "request-log op split into contract/request-log.ts + lib/request-log.ts; the retirement design doc names the pre-split path as the historical shape it describes",
    endsWhen:
      "the owning doc (1195-devtools-mcp-retirement.md) is repaired to repoint, strike, or rider this reference; the finding disappears and central zero-use reconciliation stales this row.",
  },
  {
    id: "dangling-ref-citations:tooling-src-stack-stack-sh-start",
    policyId: "dangling-ref-citations",
    subject: "tooling/src/stack/stack.sh start",
    operation: "dangling-path-cite",
    why: "the path includes a CLI subcommand suffix; tooling/src/stack/stack.sh exists but the backticked slice `stack.sh start` does not resolve as a file path",
    endsWhen:
      "the owning doc (1208-instrument-substrate.md) is repaired to repoint, strike, or rider this reference; the finding disappears and central zero-use reconciliation stales this row.",
  },
  {
    id: "dangling-ref-citations:tooling-src-stage",
    policyId: "dangling-ref-citations",
    subject: "tooling/src/stage/",
    operation: "dangling-path-cite",
    why: "the stage tool directory was never built or was merged into snap; the substrate design doc describes planned architecture",
    endsWhen:
      "the owning doc (1208-instrument-substrate.md) is repaired to repoint, strike, or rider this reference; the finding disappears and central zero-use reconciliation stales this row.",
  },
  {
    id: "dangling-ref-citations:tooling-src-_shared-browser-attach-ts",
    policyId: "dangling-ref-citations",
    subject: "tooling/src/_shared/browser-attach.ts",
    operation: "dangling-path-cite",
    why: "browser-attach was split into the browser-*.ts family in _shared/; the substrate design doc describes the planned single-file shape",
    endsWhen:
      "the owning doc (1208-instrument-substrate.md) is repaired to repoint, strike, or rider this reference; the finding disappears and central zero-use reconciliation stales this row.",
  },
  {
    id: "dangling-ref-citations:tooling-src-screen-record",
    policyId: "dangling-ref-citations",
    subject: "tooling/src/screen-record/",
    operation: "dangling-path-cite",
    why: "screen-record tool was never built as a separate directory; the filmstrip design doc describes planned architecture",
    endsWhen:
      "the owning doc (1310-snap-filmstrip.md) is repaired to repoint, strike, or rider this reference; the finding disappears and central zero-use reconciliation stales this row.",
  },
  {
    id: "dangling-ref-citations:tooling-src-ui-audit-ops-matrix-ts",
    policyId: "dangling-ref-citations",
    subject: "tooling/src/ui-audit/ops/matrix.ts",
    operation: "dangling-path-cite",
    why: "matrix op was restructured; the appearance-invariant design doc names the pre-restructure path",
    endsWhen:
      "the owning doc (953-appearance-invariant-matrix.md) is repaired to repoint, strike, or rider this reference; the finding disappears and central zero-use reconciliation stales this row.",
  },
  {
    id: "dangling-ref-citations:tooling-src-motion-audit-ops-matrix-ts",
    policyId: "dangling-ref-citations",
    subject: "tooling/src/motion-audit/ops/matrix.ts",
    operation: "dangling-path-cite",
    why: "motion matrix op was split into matrix-contract.ts + matrix-verdict.ts; the appearance-invariant design doc names the pre-split path",
    endsWhen:
      "the owning doc (953-appearance-invariant-matrix.md) is repaired to repoint, strike, or rider this reference; the finding disappears and central zero-use reconciliation stales this row.",
  },
  {
    id: "dangling-ref-citations:tooling-src-verify-gates-bus-onData-no-store-write-ts",
    policyId: "dangling-ref-citations",
    subject: "tooling/src/verify/gates/bus-onData-no-store-write.ts",
    operation: "dangling-path-cite",
    why: "the gate was renamed to bus-on-data-no-store-write.ts (kebab-case); the doc names the historical camelCase path as context for the naming-convention suppression it describes",
    endsWhen:
      "the owning doc (962-blanket-suppression-control-plane.md) is repaired to repoint, strike, or rider this reference; the finding disappears and central zero-use reconciliation stales this row.",
  },
  {
    id: "dangling-ref-citations:tooling-src-ui-audit-ops-run-ts",
    policyId: "dangling-ref-citations",
    subject: "tooling/src/ui-audit/ops/run.ts",
    operation: "dangling-path-cite",
    why: "ui-audit run.ts was restructured into the snap ops tree; the population-semantics design doc names the pre-restructure path",
    endsWhen:
      "the owning doc (983-984-ui-audit-population-semantics.md) is repaired to repoint, strike, or rider this reference; the finding disappears and central zero-use reconciliation stales this row.",
  },
  {
    id: "dangling-ref-citations:tooling-shared-appearance-ts",
    policyId: "dangling-ref-citations",
    subject: "tooling/_shared/appearance.ts",
    operation: "dangling-path-cite",
    why: "appearance.ts was restructured into the _shared/appearance-matrix.ts family; the config-revamp design doc names the pre-restructure path",
    endsWhen:
      "the owning doc (DESIGN.md) is repaired to repoint, strike, or rider this reference; the finding disappears and central zero-use reconciliation stales this row.",
  },
];
