// The ONE central home for typed reviewed grants (docs/design/gate-runtime-standardization.md §"Exceptions
// and debt"). A row licenses exactly one `(policyId, subject, operation)` identity of one `reviewed-grant`
// policy; `why` and `endsWhen` are mandatory; after a complete owner run zero consumption is STALE and more
// than one matching finding is OVER-BROAD and licenses nothing (lib/gate-authority.ts owns reconciliation).
// Gate modules never import this table; the command runner hands it to `runPolicyPass` as `reviewedGrants`.
import type { ReviewedGateGrant, SelectedGatePolicy } from "../contract/gate-authority.ts";

/** Sorted by `policyId`, then `id`; `id` is `<policyId>:<short-kebab-subject>` so a row is greppable by its policy. */
export const REVIEWED_GRANTS: readonly ReviewedGateGrant[] = Object.freeze([
  {
    id: "biome-grant-liveness:catalog-tmp",
    policyId: "biome-grant-liveness",
    subject: "docs/catalog/catalog.tmp.*.json",
    operation: "biome-glob-grant",
    why: "absent at rest BY DESIGN and never tracked: the doc-catalog's biome round-trip writes docs/catalog/catalog.tmp.<runId>.json, formats it through the binary, and rm's it in a `finally` — the run identity in the name is what stops two concurrent catalog runs from formatting each other's file (#1029), and the files.maxSize grant must PRE-EXIST the write. Producer: tooling/src/doc-catalog/ops/tree.ts. This ONE row replaces the pair the retired tables carried, whose own comment asked to 'collapse the pair the day one table can express both' (#2021).",
    endsWhen:
      "the catalog serializer stops formatting through a temp file — the glob then matches nothing anybody wrote, the finding disappears and this row is consumed zero times.",
  },
  {
    id: "bound-field-via-hook:use-bound-field",
    policyId: "bound-field-via-hook",
    subject: "packages/client/src/forms/editor/bound-fields/use-bound-field.ts",
    operation: "raw-field-context-read",
    why: "`useBoundField` IS the one home for the bound-field wiring (derive-modernization-audit.md §W3 G28): it reads the raw form context once, normalizes the touch-gated error, and assembles the `<Field>` prop bundle every bound field then shares. The seal cannot be built without the read it seals.",
    endsWhen:
      "the bound-field bundle is assembled from something other than the raw `useFieldContext` — at which point this file stops making the read and the row goes stale on its own.",
  },
  {
    id: "bus-channel-primitive:bus-channel-mint",
    policyId: "bus-channel-primitive",
    subject: "packages/server/src/transport/trpc/bus-channel.ts",
    operation: "event-emitter-construction",
    why: "`defineBusChannel`'s own module — the emitter it wraps is constructed HERE, which is the entire point of the mint (M9, client-architecture-lockdown.md §13/§16 G10).",
    endsWhen:
      "the mint moves or stops wrapping a node EventEmitter; the row is then consumed zero times and reds at its dead subject, which is the rename tripwire the legacy SANCTIONED_HOMES table owned by hand.",
  },
  {
    id: "chat-stream-writes-in-bus-only:chat-bus-writes",
    policyId: "chat-stream-writes-in-bus-only",
    subject: "packages/client/src/data/bus/chat-bus-writes.ts",
    operation: "chat-stream-write-handle",
    why: "this file IS the bus applier (UI-Gates-and-Lessons.md §11.1): `applyChatBusEvent` turns bus events into turn-slot writes, so it is the one writer the rule exists to make singular.",
    endsWhen:
      "turn slots are written by the stream store itself rather than applied from bus events, or the applier moves — either way this row stops being consumed.",
  },
  {
    id: "chat-stream-writes-in-bus-only:chat-ct-stories",
    policyId: "chat-stream-writes-in-bus-only",
    subject: "tests/client/features/chat/_ct-stories.tsx",
    operation: "chat-stream-write-handle",
    why: "the chat CT story harness seeds turn state directly because a component test mounts without a live bus: there is no `applyChatBusEvent` producer in a story, so the write api is how a phase gets rendered at all. This site is NEW EVIDENCE from the conversion — the legacy check keyed on the literal `#state` specifier and this file imports through `@orb/client/state`, so it was never judged.",
    endsWhen:
      "the CT stories seed turn state through a bus-event fixture instead of the write handle (the honest fix, and the reason this is a row rather than a population exclusion).",
  },
  {
    id: "client-cache-surgery-only-in-data:create-entity-mutation-cancel",
    policyId: "client-cache-surgery-only-in-data",
    subject: "packages/client/src/data/create-entity-mutation.ts",
    operation: "cache-surgery:cancelQueries",
    why: "`createEntityMutation` IS the optimistic-write seam (UI-Gates-and-Lessons.md §11.3): cancelling in-flight reads before the optimistic patch is step one of the recipe every feature is supposed to get from it rather than write.",
    endsWhen: "the optimistic recipe stops cancelling in flight, or the seam moves.",
  },
  {
    id: "client-cache-surgery-only-in-data:create-entity-mutation-get",
    policyId: "client-cache-surgery-only-in-data",
    subject: "packages/client/src/data/create-entity-mutation.ts",
    operation: "cache-surgery:getQueryData",
    why: "the seam snapshots the previous cache value so `onError` can roll the optimistic patch back — the rollback half of the same recipe.",
    endsWhen: "the seam rolls back from something other than a cache snapshot.",
  },
  {
    id: "client-cache-surgery-only-in-data:create-entity-mutation-remove",
    policyId: "client-cache-surgery-only-in-data",
    subject: "packages/client/src/data/create-entity-mutation.ts",
    operation: "cache-surgery:removeQueries",
    why: "a deleted entity's own query is dropped by the seam rather than left to refetch a 404 — the delete arm of the recipe.",
    endsWhen: "deletes stop pruning their entity query at the seam.",
  },
  {
    id: "client-cache-surgery-only-in-data:create-entity-mutation-set",
    policyId: "client-cache-surgery-only-in-data",
    subject: "packages/client/src/data/create-entity-mutation.ts",
    operation: "cache-surgery:setQueryData",
    why: "writing the optimistic value into the cache IS what `createEntityMutation` exists to do once, for every feature.",
    endsWhen: "optimistic writes are applied somewhere other than this seam.",
  },
  {
    id: "client-cache-surgery-only-in-data:invalidation",
    policyId: "client-cache-surgery-only-in-data",
    subject: "packages/client/src/data/invalidation.ts",
    operation: "cache-surgery:invalidateQueries",
    why: "the central invalidation seam owns the exhaustive event→filter maps and the sole invalidate call; the seam cannot obey its own rule.",
    endsWhen: "invalidation is expressed as data rather than as a call here, or the seam moves.",
  },
  {
    id: "client-cache-surgery-only-in-data:invalidation-carrier-get",
    policyId: "client-cache-surgery-only-in-data",
    subject: "packages/client/src/data/invalidation-carrier.ts",
    operation: "cache-surgery:getQueryData",
    why: "the invalidation carrier reads the current cache entry to decide whether the event's payload can be merged in place instead of refetched — part of the same seam, split out for size.",
    endsWhen: "the carrier stops reading the cache to make that decision.",
  },
  {
    id: "client-cache-surgery-only-in-data:invalidation-carrier-set",
    policyId: "client-cache-surgery-only-in-data",
    subject: "packages/client/src/data/invalidation-carrier.ts",
    operation: "cache-surgery:setQueryData",
    why: "and writes the merged entry back — the carrier's whole purpose is to be the one place that surgery happens.",
    endsWhen: "the carrier stops writing merged entries.",
  },
  {
    id: "client-cache-surgery-only-in-data:peek-query",
    policyId: "client-cache-surgery-only-in-data",
    subject: "packages/client/src/data/peek-query.ts",
    operation: "cache-surgery:getQueryData",
    why: "`peekQuery` IS the sanctioned non-subscribing cache READ that features are pointed at instead of reaching for the client themselves; it is one function whose whole body is the read.",
    endsWhen: "the peek is served by a query observer rather than a direct cache read.",
  },
  {
    id: "client-cache-surgery-only-in-data:use-start-chat",
    policyId: "client-cache-surgery-only-in-data",
    subject: "packages/client/src/data/use-start-chat.ts",
    operation: "cache-surgery:setQueryData",
    why: "the start-chat seam seeds the new chat's cache entry from the create response so the room can render before its first read lands — a data/ seam doing exactly what the seam layer is for.",
    endsWhen: "the new chat's first render no longer depends on a seeded cache entry.",
  },
  {
    id: "config-anchor-in-registry:config-jump",
    policyId: "config-anchor-in-registry",
    subject: "packages/client/src/features/config/lib/config-jump.ts",
    operation: "config-anchor-stamp",
    why: "the config JUMP resolves an anchor id to scroll to it — the READER half of §6.8.3's contract, which is the reason anchors are derived from the registry rather than authored twice.",
    endsWhen: "jump targets are resolved from registry rows directly instead of by re-deriving the anchor id.",
  },
  {
    id: "config-anchor-in-registry:config-scroll-spy",
    policyId: "config-anchor-in-registry",
    subject: "packages/client/src/features/config/hooks/use-config-scroll-spy.ts",
    operation: "config-anchor-stamp",
    why: "the config content pane's scroll-spy hook READS anchors rather than painting one: it derives the active group's anchor prefix to drive the spy (the WHEN half split out of `surfaces/config-content-surface.tsx` on main, #1632 train 81; the grant moved with the reader, which is exactly the liveness this row is keyed on). It owns no config row and must not be registered as one (config-revamp-design.md §6.8.3).",
    endsWhen: "the spy's prefix is supplied by the registry itself instead of recomputed at the reader.",
  },
  {
    id: "content-part-seam:chat-contract-results",
    policyId: "content-part-seam",
    subject: "packages/server/src/domain/chat/contract/results.ts",
    operation: "chat-content-part-reference",
    why: "the domain-side request DTO the seam populates (`content: ChatContentPart[]` handed to the runner) — the shape the engine fills and infra reads.",
    endsWhen:
      "the wire seam stops taking content PARTS (D51 is retired) or this module stops naming the type; either way the row is consumed zero times and reds.",
  },
  {
    id: "content-part-seam:chat-engine-pipeline",
    policyId: "content-part-seam",
    subject: "packages/server/src/domain/chat/engine/pipeline.ts",
    operation: "chat-content-part-reference",
    why: "the engine request seam ASSEMBLES the parts the CONVERT step builds, and mints its own for the TOOL-RESULT rows (`toolResultMessages`), which never pass through the history conversion.",
    endsWhen:
      "the wire seam stops taking content PARTS (D51 is retired) or this module stops naming the type; either way the row is consumed zero times and reds.",
  },
  {
    id: "content-part-seam:chat-wire-history",
    policyId: "content-part-seam",
    subject: "packages/server/src/domain/chat/substrate/wire-history.ts",
    operation: "chat-content-part-reference",
    why: "THE one producer (D51). The CONVERT step moved here at #1540 so the read verb's previews price the same converted rows the turn's fitter prices; a pure read cannot import the turn-execution module.",
    endsWhen:
      "the wire seam stops taking content PARTS (D51 is retired) or this module stops naming the type; either way the row is consumed zero times and reds.",
  },
  {
    id: "content-part-seam:providers-contract-chat",
    policyId: "content-part-seam",
    subject: "packages/server/src/infra/providers/contract/chat.ts",
    operation: "chat-content-part-reference",
    why: "the sealed runner tier's own request contract — the shape every backend runner is handed.",
    endsWhen:
      "the wire seam stops taking content PARTS (D51 is retired) or this module stops naming the type; either way the row is consumed zero times and reds.",
  },
  {
    id: "content-part-seam:runner-custom-byo-chat",
    policyId: "content-part-seam",
    subject: "packages/server/src/infra/providers/backends/custom-byo/runners/chat.ts",
    operation: "chat-content-part-reference",
    why: "the sealed runner tier is the D51 seam's ONLY consumer — this runner maps content parts onto its backend's wire, which is the reason parts exist at all.",
    endsWhen:
      "the wire seam stops taking content PARTS (D51 is retired) or this module stops naming the type; either way the row is consumed zero times and reds.",
  },
  {
    id: "content-part-seam:runner-kit-history",
    policyId: "content-part-seam",
    subject: "packages/server/src/infra/providers/backends/kit/history.ts",
    operation: "chat-content-part-reference",
    why: "the sealed runner tier is the D51 seam's ONLY consumer — this runner maps content parts onto its backend's wire, which is the reason parts exist at all.",
    endsWhen:
      "the wire seam stops taking content PARTS (D51 is retired) or this module stops naming the type; either way the row is consumed zero times and reds.",
  },
  {
    id: "content-part-seam:runner-openrouter-responses",
    policyId: "content-part-seam",
    subject: "packages/server/src/infra/providers/backends/openrouter/runners/chat/responses.ts",
    operation: "chat-content-part-reference",
    why: "the sealed runner tier is the D51 seam's ONLY consumer — this runner maps content parts onto its backend's wire, which is the reason parts exist at all.",
    endsWhen:
      "the wire seam stops taking content PARTS (D51 is retired) or this module stops naming the type; either way the row is consumed zero times and reds.",
  },
  {
    id: "content-part-seam:runner-openrouter-shared",
    policyId: "content-part-seam",
    subject: "packages/server/src/infra/providers/backends/openrouter/runners/chat/shared.ts",
    operation: "chat-content-part-reference",
    why: "the sealed runner tier is the D51 seam's ONLY consumer — this runner maps content parts onto its backend's wire, which is the reason parts exist at all.",
    endsWhen:
      "the wire seam stops taking content PARTS (D51 is retired) or this module stops naming the type; either way the row is consumed zero times and reds.",
  },
  {
    id: "content-part-seam:runner-vllm-chat",
    policyId: "content-part-seam",
    subject: "packages/server/src/infra/providers/vllm/surfaces/chat.ts",
    operation: "chat-content-part-reference",
    why: "the sealed runner tier is the D51 seam's ONLY consumer — this runner maps content parts onto its backend's wire, which is the reason parts exist at all.",
    endsWhen:
      "the wire seam stops taking content PARTS (D51 is retired) or this module stops naming the type; either way the row is consumed zero times and reds.",
  },
  {
    id: "no-direct-useform:contexts",
    policyId: "no-direct-useform",
    subject: "packages/client/src/forms/editor/contexts.ts",
    operation: "tanstack-form-mint:createFormHookContexts",
    why: "the ONE `createFormHookContexts()` call the whole toolkit is built on (UI-Lib-TanStack-Form.md §Composition: 'define this once'); it is split from `use-app-form.ts` only so the bound components can import the contexts without a circular edge.",
    endsWhen: "the form toolkit stops minting its own contexts (a vendor change), or the contexts move.",
  },
  {
    id: "no-direct-useform:use-app-form",
    policyId: "no-direct-useform",
    subject: "packages/client/src/forms/editor/use-app-form.ts",
    operation: "tanstack-form-mint:createFormHook",
    why: "the single `createFormHook` instance every multi-field form builds from — `useAppForm` IS this call, and it is what the rule points every surface at instead.",
    endsWhen: "the shared instance is minted somewhere else, which stales this row at its old path.",
  },
  {
    id: "no-direct-users-read:admin-create-user",
    policyId: "no-direct-users-read",
    subject: "packages/server/src/domain/admin/verbs/create-user.ts",
    operation: "users-table-reference",
    why: "user MANAGEMENT is one of the two sanctioned identity readers (Spine-Identity-and-Auth.md): the admin surface owns the `users` row's own lifecycle, so it cannot take userId from a Principal that describes the CALLER instead of the target.",
    endsWhen:
      "this module stops reading the identity root — which is the mode-A staleness the legacy EXEMPT_DOMAINS arm checked by hand, now the central zero-consumption alarm.",
  },
  {
    id: "no-direct-users-read:admin-persistence-queries",
    policyId: "no-direct-users-read",
    subject: "packages/server/src/domain/admin/persistence/queries.ts",
    operation: "users-table-reference",
    why: "user MANAGEMENT is one of the two sanctioned identity readers (Spine-Identity-and-Auth.md): the admin surface owns the `users` row's own lifecycle, so it cannot take userId from a Principal that describes the CALLER instead of the target.",
    endsWhen:
      "this module stops reading the identity root — which is the mode-A staleness the legacy EXEMPT_DOMAINS arm checked by hand, now the central zero-consumption alarm.",
  },
  {
    id: "no-direct-users-read:admin-reset-password",
    policyId: "no-direct-users-read",
    subject: "packages/server/src/domain/admin/verbs/reset-password.ts",
    operation: "users-table-reference",
    why: "user MANAGEMENT is one of the two sanctioned identity readers (Spine-Identity-and-Auth.md): the admin surface owns the `users` row's own lifecycle, so it cannot take userId from a Principal that describes the CALLER instead of the target.",
    endsWhen:
      "this module stops reading the identity root — which is the mode-A staleness the legacy EXEMPT_DOMAINS arm checked by hand, now the central zero-consumption alarm.",
  },
  {
    id: "no-direct-users-read:admin-set-enabled",
    policyId: "no-direct-users-read",
    subject: "packages/server/src/domain/admin/verbs/set-enabled.ts",
    operation: "users-table-reference",
    why: "user MANAGEMENT is one of the two sanctioned identity readers (Spine-Identity-and-Auth.md): the admin surface owns the `users` row's own lifecycle, so it cannot take userId from a Principal that describes the CALLER instead of the target.",
    endsWhen:
      "this module stops reading the identity root — which is the mode-A staleness the legacy EXEMPT_DOMAINS arm checked by hand, now the central zero-consumption alarm.",
  },
  {
    id: "no-direct-users-read:admin-set-role",
    policyId: "no-direct-users-read",
    subject: "packages/server/src/domain/admin/verbs/set-role.ts",
    operation: "users-table-reference",
    why: "user MANAGEMENT is one of the two sanctioned identity readers (Spine-Identity-and-Auth.md): the admin surface owns the `users` row's own lifecycle, so it cannot take userId from a Principal that describes the CALLER instead of the target.",
    endsWhen:
      "this module stops reading the identity root — which is the mode-A staleness the legacy EXEMPT_DOMAINS arm checked by hand, now the central zero-consumption alarm.",
  },
  {
    id: "no-direct-users-read:sessions-persistence-sessions",
    policyId: "no-direct-users-read",
    subject: "packages/server/src/domain/sessions/persistence/sessions.ts",
    operation: "users-table-reference",
    why: "the resolution path JOINS the session row to its identity row — this is the read that MINTS the Principal every other domain then takes userId from, so it cannot itself take one.",
    endsWhen:
      "this module stops reading the identity root — which is the mode-A staleness the legacy EXEMPT_DOMAINS arm checked by hand, now the central zero-consumption alarm.",
  },
  {
    id: "no-direct-users-read:sessions-persistence-users",
    policyId: "no-direct-users-read",
    subject: "packages/server/src/domain/sessions/persistence/users.ts",
    operation: "users-table-reference",
    why: "the identity root's own persistence module in the sanctioned resolution-path domain — it is what turns a session into the Principal.",
    endsWhen:
      "this module stops reading the identity root — which is the mode-A staleness the legacy EXEMPT_DOMAINS arm checked by hand, now the central zero-consumption alarm.",
  },
  {
    id: "no-inline-invalidate-outside-seam:invalidation",
    policyId: "no-inline-invalidate-outside-seam",
    subject: "packages/client/src/data/invalidation.ts",
    operation: "inline-invalidate-queries",
    why: "the ONE sanctioned `invalidateQueries` call: this file owns the exhaustive event→`queryFilter()` maps that every `invalidate(event)` resolves through (UI-Gates-and-Lessons.md §11.3). It carries a second row under `client-cache-surgery-only-in-data` because that policy fences the same call at the DIRECTORY grain — two doc rows, two licences.",
    endsWhen: "the seam expresses invalidation as data consumed by the query client rather than as its own call, or the seam file moves.",
  },
  {
    id: "no-raw-clock:entry-lifecycle",
    policyId: "no-raw-clock",
    subject: "packages/server/src/entry/lifecycle.ts",
    operation: "ambient-clock-read",
    why: "the composition root CONSTRUCTS the clock it injects into every tier (Tier-5-Entry.md) — a root that cannot read the ambient clock cannot mint one.",
    endsWhen: "the clock is minted from a platform seam the root receives rather than read here; the row is then consumed zero times and reds.",
  },
  {
    id: "no-raw-clock:kit-time-engine",
    policyId: "no-raw-clock",
    subject: "packages/kit/src/time/index.ts",
    operation: "ambient-clock-read",
    why: "`@orb/kit/time` IS the clock seam — `createClock`/`nowMs` read the ambient clock here exactly once so nothing else has to.",
    endsWhen:
      "the time engine moves out of this module or stops defaulting to the ambient clock; the row is then consumed zero times and reds at its dead subject.",
  },
  {
    id: "no-raw-egress:agent-sdk-host-token",
    policyId: "no-raw-egress",
    subject: "packages/server/src/infra/providers/backends/agent-sdk/host-token.ts",
    operation: "raw-fetch",
    why: "the ambient default of this module's INJECTED fetch port (`deps.fetch ?? fetch`), used for the Claude Agent SDK host-credential refresh — a fixed vendor endpoint reached with the operator's own credential, not a user-influenced URL. NEW EVIDENCE from the conversion: the legacy directory zone licensed the whole of infra/providers, and the legacy identifier-CALLEE check could not have seen a bare reference in a default position either.",
    endsWhen: "the port stops carrying an ambient default (the composition root always injects one), which is the honest fix and makes this row stale.",
  },
  {
    id: "no-raw-egress:custom-byo-chat",
    policyId: "no-raw-egress",
    subject: "packages/server/src/infra/providers/backends/custom-byo/runners/chat.ts",
    operation: "raw-fetch",
    why: "the BYO CHAT runner, the streaming twin of the inspect probe and host-pinned the same way (#25, mirrors inspect.ts #21) — an operator-configured endpoint reached with the operator's own key.",
    endsWhen: "the BYO runner routes through `safeFetch` with an ANY_HOST escape that preserves the manual-redirect pin.",
  },
  {
    id: "no-raw-egress:custom-byo-inspect",
    policyId: "no-raw-egress",
    subject: "packages/server/src/infra/providers/backends/custom-byo/inspect.ts",
    operation: "raw-fetch",
    why: 'the BYO endpoint INSPECT probe: an operator-configured endpoint reached with the operator\'s own key, host-pinned by `redirect: "manual"` so the key never follows a redirect off it (#21). The URL is a stored connection setting, not user-influenced input, and the request/response are redacted before they are recorded.',
    endsWhen: "the BYO probe routes through `safeFetch` with an ANY_HOST escape that preserves the manual-redirect pin.",
  },
  {
    id: "no-raw-egress:egress-hop",
    policyId: "no-raw-egress",
    subject: "packages/server/src/infra/network/egress.ts",
    operation: "raw-fetch",
    why: "`safeFetch`'s own home: `fetchHop` IS the guarded request every other server call is routed through. The guard cannot be built without the one raw fetch it wraps, and the scheme pin, host allowlist, resolve→validate→pin and deadline all run around this exact line.",
    endsWhen: "the guard stops issuing the request itself (a lower transport primitive takes over), at which point this row is consumed zero times and reds.",
  },
  {
    id: "no-raw-egress:vllm-engine-client",
    policyId: "no-raw-egress",
    subject: "packages/server/src/infra/providers/vllm/engine/client.ts",
    operation: "raw-fetch",
    why: "the vLLM engine client's POST to a LOOPBACK engine this process supervises: the base URL is derived from the engine record rather than from any request, and the call is always signalled with the caller's derived deadline.",
    endsWhen: "engine traffic leaves loopback (a remote engine becomes addressable), at which point it needs the SSRF guard rather than this row.",
  },
  {
    id: "no-raw-egress:vllm-fleet-control",
    policyId: "no-raw-egress",
    subject: "packages/server/src/infra/providers/vllm/engine/fleet-control.ts",
    operation: "raw-fetch",
    why: "the engine LIFECYCLE control plane (`POST /sleep`) against a loopback engine this process supervises — no auth, no credential, no user-influenced URL, and a hard `AbortSignal.timeout`.",
    endsWhen: "engine traffic leaves loopback, at which point the lifecycle plane needs the SSRF guard rather than this row.",
  },
  {
    id: "no-raw-egress:vllm-gen-window",
    policyId: "no-raw-egress",
    subject: "packages/server/src/infra/providers/vllm/engine/gen-window.ts",
    operation: "raw-fetch",
    why: "the loopback `GET /v1/models` read that discovers an engine's context window; a failure degrades to the env-owned window. Same loopback, no-credential class as the rest of the engine plane.",
    endsWhen: "engine traffic leaves loopback, at which point this read needs the SSRF guard rather than this row.",
  },
  {
    id: "no-raw-egress:vllm-supervisor",
    policyId: "no-raw-egress",
    subject: "packages/server/src/infra/providers/vllm/engine/supervisor.ts",
    operation: "raw-fetch",
    why: "the loopback `/is_sleeping` HEALTH probe the supervisor uses to decide whether an engine needs waking; any failure reads as not-sleeping (fails toward healthy). Same loopback, no-credential class as the rest of the engine plane.",
    endsWhen: "engine traffic leaves loopback, at which point the health probe needs the SSRF guard rather than this row.",
  },
  {
    id: "no-raw-interactive-intrinsics:app-shell-surface",
    policyId: "no-raw-interactive-intrinsics",
    subject: "packages/client/src/features/app-shell/surfaces/app-shell.tsx",
    operation: "raw-interactive-intrinsic:button",
    why: "the SHELL tier composes the app frame BELOW the primitive layer, which design-enforcement.md §3.2 (D62) exempts — this control is part of the frame an @orb/ui Button is rendered inside, not a feature affordance. Narrowed from the legacy DIRECTORY row: the permission is now this one file, so a second shell file hosting a raw control reds until someone reviews it.",
    endsWhen:
      "the shell's own control is expressible through an @orb/ui primitive without a frame cycle, or the shell moves — either way the row is consumed zero times and reds at its dead subject.",
  },
  {
    id: "no-raw-intl-time:kit-time",
    policyId: "no-raw-intl-time",
    subject: "packages/kit/src/time/index.ts",
    operation: "intl-formatter",
    why: "`@orb/kit/time` IS the memoized Intl seam: `createTimeLib` constructs the `DateTimeFormat`/`RelativeTimeFormat` instances it then hands every call site, which is the whole reason the rest of the repo may not.",
    endsWhen:
      "time formatting moves off Intl, or the time engine leaves this file — the row stales at its dead path instead of exempting one that no longer exists.",
  },
  {
    id: "no-raw-matchmedia:coarse-pointer-now",
    policyId: "no-raw-matchmedia",
    subject: "packages/ui/src/lib/coarse-pointer-now.ts",
    operation: "raw-match-media",
    why: "the ONE (pointer: coarse) home minted by #1182 (`coarsePointerNow()`, the imperative twin of the reduced-motion pair): every coarse-pointer read in @orb/ui and the client goes through it, so the raw `matchMedia` read belongs here and nowhere else — the same recurring permission the two reduced-motion homes carry.",
    endsWhen:
      "the pointer-coarseness read moves into a shared media-query seam that also serves the reduced-motion homes, or the browser exposes the fact without matchMedia.",
  },
  {
    id: "no-raw-matchmedia:media-grid",
    policyId: "no-raw-matchmedia",
    subject: "packages/ui/src/primitives/media-grid/media-grid.tsx",
    operation: "raw-match-media",
    why: "a POINTER-CAPABILITY query (`(pointer: fine)`), which the reduced-motion one-homes do not cover. `#1182` landed a coarse-pointer imperative one-home (`coarsePointerNow()`), but that reader answers `(pointer: coarse)` — a DIFFERENT query, not this call's logical inverse (a `pointer: none` device matches neither), so it does not serve this read; the one-home's existence narrows the gap this row licenses, it does not close it. This was the permanent `@orb-gate-ignore` that used to sit at the call site, translated: a reviewed-grant policy has no inline door, and a standing permission belongs in the reviewed table rather than in a comment one author can write.",
    endsWhen: "a `(pointer: fine)` one-home lands beside `coarsePointerNow()` in `@orb/ui/src/lib/` and this call reads it instead.",
  },
  {
    id: "no-raw-matchmedia:reduced-motion-now",
    policyId: "no-raw-matchmedia",
    subject: "packages/ui/src/lib/reduced-motion-now.ts",
    operation: "raw-match-media",
    why: "the imperative reduced-motion one-home (`prefersReducedMotionNow()`) — the point-in-time half of the pair the rule points every caller at.",
    endsWhen: "the imperative reader is served by the render hook's cached query instead of its own read, or the home moves.",
  },
  {
    id: "no-raw-matchmedia:use-is-mobile-viewport",
    policyId: "no-raw-matchmedia",
    subject: "packages/client/src/features/app-shell/hooks/use-is-mobile-viewport.ts",
    operation: "raw-match-media",
    why: "the shell's viewport one-home: the ONE place the mobile-viewport fact is read, which the rest of the client then reads off `#state` rather than re-querying (the store's own header points at this hook by name).",
    endsWhen: "the viewport fact is published by something other than a media query, or the hook moves out of the shell.",
  },
  {
    id: "no-raw-matchmedia:use-prefers-reduced-motion",
    policyId: "no-raw-matchmedia",
    subject: "packages/ui/src/lib/use-prefers-reduced-motion.ts",
    operation: "raw-match-media",
    why: "the render-time reduced-motion one-home: one `matchMedia` + `useSyncExternalStore` subscription for every non-CSS motion path.",
    endsWhen: "reduced motion is read from a CSS-driven signal instead, or the home moves.",
  },
  {
    id: "no-raw-random:entry-compose-chat",
    policyId: "no-raw-random",
    subject: "packages/server/src/entry/compose/chat.ts",
    operation: "ambient-entropy-draw",
    why: "the composition root SEEDS the turn PRNG it injects into the chat engine (Tier-5-Entry.md) — the seed has to be drawn somewhere, and the root is the one tier allowed to.",
    endsWhen: "the seed is supplied to the root as an injected value rather than drawn here; the row is then consumed zero times and reds.",
  },
  {
    id: "no-raw-zustand-persist:create-entity-draft-store-persist",
    policyId: "no-raw-zustand-persist",
    subject: "packages/client/src/state/create-entity-draft-store.ts",
    operation: "zustand-persist-mint",
    why: "the draft-store factory bakes the footguns in (partialize / version+total-migrate / key uniqueness); the `persist(` call it wraps IS the seal every draft store then mints through.",
    endsWhen:
      "the factory stops calling `persist` or leaves the project — both of which stale this row, which is the two-sided liveness the module used to implement itself.",
  },
  {
    id: "no-raw-zustand-persist:create-entity-draft-store-reset",
    policyId: "no-raw-zustand-persist",
    subject: "packages/client/src/state/create-entity-draft-store.ts",
    operation: "destructive-store-reset",
    why: "the factory's own `reset` closure is what the durable-local registry drives through `resetWithoutPersisting`, which blindfolds the store's storage first — so the destructive reset here is the in-memory drop #837 requires, not the write-through it forbids.",
    endsWhen: "the factory's reset stops being driven behind the storage blindfold.",
  },
  {
    id: "no-raw-zustand-persist:create-persisted-store-persist",
    policyId: "no-raw-zustand-persist",
    subject: "packages/client/src/state/create-persisted-store.ts",
    operation: "zustand-persist-mint",
    why: "the general persisted-store factory, the same seal one shape over.",
    endsWhen: "the factory stops calling `persist` or leaves the project.",
  },
  {
    id: "no-raw-zustand-persist:create-persisted-store-reset",
    policyId: "no-raw-zustand-persist",
    subject: "packages/client/src/state/create-persisted-store.ts",
    operation: "destructive-store-reset",
    why: "the same registered-reset closure on the general factory, driven through the same blindfolded door.",
    endsWhen: "the factory's reset stops being driven behind the storage blindfold.",
  },
  {
    id: "no-untyped-soft-ref:audit-logs-entity",
    policyId: "no-untyped-soft-ref",
    subject: "audit_logs.entityId",
    operation: "soft-reference",
    why: "the append-only audit log must outlive an arbitrary referent of unknown TYPE — the one D24 sanctioned soft ref. An FK would either pin the log to one table or delete history with its subject, and the log's whole purpose is to survive both.",
    endsWhen:
      "the audit log stops recording polymorphic referents (each entity kind gains its own typed log table), at which point this column can carry a real FK.",
  },
  {
    id: "no-untyped-soft-ref:automation-rule-preset",
    policyId: "no-untyped-soft-ref",
    subject: "automation_rules.rulePresetId",
    operation: "soft-reference",
    why: "a rule-preset CATALOGUE id (`RULE_PRESET_IDS`, @orb/contracts/automation) — a member of a closed CODE tuple, not a row of any table, so there is nothing to FK. Coherence is the wire's z.enum at write plus the live-catalogue re-check at read/apply, where an orphaned id degrades to a reported skip.",
    endsWhen: "the rule-preset catalogue becomes a table, at which point every catalogue id gains a real FK.",
  },
  {
    id: "no-untyped-soft-ref:roster-rule-preset",
    policyId: "no-untyped-soft-ref",
    subject: "roster_preset_rules.rulePresetId",
    operation: "soft-reference",
    why: "the same rule-preset CATALOGUE id on the saved-roster side — the cast's captured rule, a code-tuple member rather than a row (D24-external), with the same enum-at-write plus re-check-at-apply coherence.",
    endsWhen: "the rule-preset catalogue becomes a table, at which point every catalogue id gains a real FK.",
  },
  {
    id: "no-untyped-soft-ref:sdk-session-handle",
    policyId: "no-untyped-soft-ref",
    subject: "session_entries.sdkSessionId",
    operation: "soft-reference",
    why: "the Claude Agent SDK's OWN resume handle — the prompt-cache lineage id the SDK returns (D8/D25). An EXTERNAL identifier owned by the vendor runtime, not a reference to any orbweaver table.",
    endsWhen: "the SDK session becomes an orbweaver-owned row rather than a vendor handle we carry.",
  },
  {
    id: "no-untyped-soft-ref:users-external",
    policyId: "no-untyped-soft-ref",
    subject: "users.externalId",
    operation: "soft-reference",
    why: "an external IdP subject identifier (the SSO `sub`) — a string minted by another system, not a reference to any orbweaver table, so there is nothing for an FK to point at.",
    endsWhen: "identity stops being federated and the subject becomes an orbweaver row.",
  },
  {
    id: "no-untyped-soft-ref:variant-generation",
    policyId: "no-untyped-soft-ref",
    subject: "message_variants.generationId",
    operation: "soft-reference",
    why: "the upstream OpenRouter generation handle (`gen-…`) a variant was billed under — an EXTERNAL provider id (`connection.orGenerationCost`'s key, PD-137), not a reference to any orbweaver table (D24).",
    endsWhen: "generation records are persisted as orbweaver rows, at which point the column can carry a real FK.",
  },
  {
    id: "owner-role-split:admin-create-user",
    policyId: "owner-role-split",
    subject: "packages/server/src/domain/admin/verbs/create-user.ts",
    operation: "global-role-comparison",
    why: "the owner is the immutable bootstrap row and is never minted through admin, so this verb refuses to ASSIGN the owner role even to an owner caller. This is a TARGET-VALIDITY check on the owner ROW, not a caller-privilege gate: `can()` decides whether a principal may act, and it structurally cannot answer whether the row being acted on is the immutable bootstrap owner. The legacy text reader was blind to it because the literal is the `OWNER_ROLE` const rather than a quoted string.",
    endsWhen: "the admin guard exposes an owner-immutability decision the verbs call, instead of each verb comparing the global-role value itself.",
  },
  {
    id: "owner-role-split:admin-link-sso-identity",
    policyId: "owner-role-split",
    subject: "packages/server/src/domain/admin/verbs/link-sso-identity.ts",
    operation: "global-role-comparison",
    why: "the owner is never admin-linked — its SSO binding is the automatic owner-flip adoption, and choosing the owner's subject here would be box takeover. This is a TARGET-VALIDITY check on the owner ROW, not a caller-privilege gate: `can()` decides whether a principal may act, and it structurally cannot answer whether the row being acted on is the immutable bootstrap owner. The legacy text reader was blind to it because the literal is the `OWNER_ROLE` const rather than a quoted string.",
    endsWhen: "the admin guard exposes an owner-immutability decision the verbs call, instead of each verb comparing the global-role value itself.",
  },
  {
    id: "owner-role-split:admin-reset-password",
    policyId: "owner-role-split",
    subject: "packages/server/src/domain/admin/verbs/reset-password.ts",
    operation: "global-role-comparison",
    why: "the owner's credential is not admin-resettable; the verb refuses the owner ROW rather than the caller. This is a TARGET-VALIDITY check on the owner ROW, not a caller-privilege gate: `can()` decides whether a principal may act, and it structurally cannot answer whether the row being acted on is the immutable bootstrap owner. The legacy text reader was blind to it because the literal is the `OWNER_ROLE` const rather than a quoted string.",
    endsWhen: "the admin guard exposes an owner-immutability decision the verbs call, instead of each verb comparing the global-role value itself.",
  },
  {
    id: "owner-role-split:admin-set-enabled",
    policyId: "owner-role-split",
    subject: "packages/server/src/domain/admin/verbs/set-enabled.ts",
    operation: "global-role-comparison",
    why: "the owner row cannot be disabled — a disabled owner is a bricked box. This is a TARGET-VALIDITY check on the owner ROW, not a caller-privilege gate: `can()` decides whether a principal may act, and it structurally cannot answer whether the row being acted on is the immutable bootstrap owner. The legacy text reader was blind to it because the literal is the `OWNER_ROLE` const rather than a quoted string.",
    endsWhen: "the admin guard exposes an owner-immutability decision the verbs call, instead of each verb comparing the global-role value itself.",
  },
  {
    id: "owner-role-split:admin-set-role",
    policyId: "owner-role-split",
    subject: "packages/server/src/domain/admin/verbs/set-role.ts",
    operation: "global-role-comparison",
    why: "the owner cannot be demoted, and the no-op re-grant of owner-to-owner returns unchanged. This is a TARGET-VALIDITY check on the owner ROW, not a caller-privilege gate: `can()` decides whether a principal may act, and it structurally cannot answer whether the row being acted on is the immutable bootstrap owner. The legacy text reader was blind to it because the literal is the `OWNER_ROLE` const rather than a quoted string.",
    endsWhen: "the admin guard exposes an owner-immutability decision the verbs call, instead of each verb comparing the global-role value itself.",
  },
  {
    id: "persistence-boundary:durable-local",
    policyId: "persistence-boundary",
    subject: "packages/client/src/state/durable-local.ts",
    operation: "raw-storage:localStorage",
    why: "the two persist factories' SHARED half — the per-user durable-local namespace. Its only raw-storage touch is the last-bound-userId POINTER a cold boot mints store keys against; store blobs move through each store's own persist storage and never through this. Boot machinery, the same carve-out class as the composition root.",
    endsWhen: "key minting stops needing a pre-store pointer (the bound user is known before any store is created), which would make this read unnecessary.",
  },
  {
    id: "persistence-boundary:main-preload-guard",
    policyId: "persistence-boundary",
    subject: "packages/client/src/main.tsx",
    operation: "raw-storage:sessionStorage",
    why: "the composition root's `vite:preloadError` reload-once guard: a redeploy rotates hashed chunk names and an old tab that lazy-imports a stale hash white-screens, so the soft reload is guarded by a tab-scoped flag that stops a reload loop. Boot machinery, and it runs in a window listener before the app's stores exist.",
    endsWhen: "chunk-hash rotation stops white-screening an open tab (a service worker or a version handshake owns it), which retires the guard.",
  },
  {
    id: "persistence-boundary:probe-mode",
    policyId: "persistence-boundary",
    subject: "packages/client/src/lib/probe-mode.ts",
    operation: "raw-storage:localStorage",
    why: "the dev-only probe flag seeded by `pnpm snap --probe` BEFORE the app boots — deterministic-render instrumentation, not app state, and read once before React mounts. A store door cannot serve it because no store exists yet at that point.",
    endsWhen: "probe mode is delivered by something other than pre-boot storage (a query parameter or a build flag), at which point this read disappears.",
  },
  {
    id: "persistence-boundary:session-resume",
    policyId: "persistence-boundary",
    subject: "packages/client/src/data/session-resume.ts",
    operation: "raw-storage:sessionStorage",
    why: "the OIDC re-auth resume snapshot: TAB-scoped by requirement (a sibling tab must not inherit another tab's redirect round trip) and written across a full-document navigation, so it cannot ride a store door at all. Session machinery, not a device-local preference.",
    endsWhen: "the IdP round trip stops requiring a full-document navigation, so the resume target can live in memory.",
  },
  {
    id: "render-error-via-battery:persona-panel-surface",
    policyId: "render-error-via-battery",
    subject: "packages/client/src/features/persona/surfaces/persona-panel-surface.tsx",
    operation: "custom-render-error",
    why: "the persona avatar degrades to its own loading placeholder rather than a Couldn't-load card with a Retry: it is a decorative slot, not a read the user retries.",
    endsWhen: "the avatar becomes a retryable read, or the surface moves.",
  },
  {
    id: "render-error-via-battery:rpg-context-section",
    policyId: "render-error-via-battery",
    subject: "packages/client/src/features/rpg/lib/rpg-context-section.tsx",
    operation: "custom-render-error",
    why: "the rpg context pane needs a CONSOLIDATED, ANNOUNCED failure (Context-Panel-Program §4.4): the pane's live region reports 'Loaded chat.' on success, and `QueryErrorState` is a plain stack with no `role=\"alert\"`, so the game-tab body renders `RpgErrorState` — the pane's single announced region. One row covers both of this file's arms, because they are one licensed act at one subject.",
    endsWhen: "the pane drops its announced-failure intent, or `QueryErrorState` gains a live region the pane can use.",
  },
  {
    id: "render-error-via-battery:rpg-hud-band",
    policyId: "render-error-via-battery",
    subject: "packages/client/src/features/rpg/components/rpg-hud-band.tsx",
    operation: "custom-render-error",
    why: "the decorative HUD band collapses to `() => null` on a failed read so the pane has exactly ONE announced error surface (the body's) rather than two contradictory ones.",
    endsWhen: "the band becomes a retryable read of its own, or the pane stops owning a single announced failure.",
  },
  {
    id: "route-imports-no-feature:app-root-app-shell",
    policyId: "route-imports-no-feature",
    subject: "packages/client/src/routes/app-root.tsx",
    operation: "feature-front-door-import:#features/app-shell",
    why: "app-root.tsx is the ONE sanctioned composition route (client-architecture-lockdown.md §6): the shell it mounts is what OWNS the section/modal/chrome registries, so it cannot itself reach them through a registry that does not exist until it has mounted.",
    endsWhen: "the app shell is entered through a registry-assembled door rather than composed at the route.",
  },
  {
    id: "route-imports-no-feature:app-root-chat",
    policyId: "route-imports-no-feature",
    subject: "packages/client/src/routes/app-root.tsx",
    operation: "feature-front-door-import:#features/chat",
    why: "the sanctioned composition route assembles the chat feature's contributor registries at the door (client-architecture-lockdown.md §12 row 5); the assembly is the door's job by construction.",
    endsWhen: "chat's contributor registries are assembled by the shell from registered contributions instead of at the route.",
  },
  {
    id: "route-imports-no-feature:app-root-persona",
    policyId: "route-imports-no-feature",
    subject: "packages/client/src/routes/app-root.tsx",
    operation: "feature-front-door-import:#features/persona",
    why: "the sanctioned composition route assembles the persona feature's contributions at the door, on the same §12 row-5 ruling as chat.",
    endsWhen: "persona's contributions are assembled by the shell from registered contributions instead of at the route.",
  },
  {
    id: "route-imports-no-feature:login-page-auth",
    policyId: "route-imports-no-feature",
    subject: "packages/client/src/routes/login-page.tsx",
    operation: "feature-front-door-import:#features/auth",
    why: "the login page IS the auth surface: it renders before any authenticated shell exists, so there is no registry for it to ride.",
    endsWhen: "the login surface is reached through the authenticated shell's registries, which by definition it cannot be while it is the pre-auth entry.",
  },
  {
    id: "route-imports-no-feature:router-auth",
    policyId: "route-imports-no-feature",
    subject: "packages/client/src/routes/router.tsx",
    operation: "feature-front-door-import:#features/auth",
    why: "the router's beforeLoad gate must consult auth before it can decide which route tree to build, which is strictly earlier than any registry read.",
    endsWhen: "route admission is decided by a contracts-level session fact instead of by the auth feature's own door.",
  },
  {
    id: "scrubber-home:member-visibility-stamp",
    policyId: "scrubber-home",
    subject: "packages/server/src/domain/chat/substrate/member-visibility.ts",
    operation: "hidden-span-scrubber-construction",
    why: "THE producer stamp — the one place a stateful per-slot scrubber may be constructed (§3.6, ed2aafc5), because scrub state cannot survive a replay→live handoff and a cold scrubber mid-`<lie>` forwards the secret's tail.",
    endsWhen:
      "the producer stamp moves or stops constructing a scrubber; the row is then consumed zero times and reds, which is the legacy mode-A arm owned centrally.",
  },
  {
    id: "selection-store-via-factory:create-drill-selection-store",
    policyId: "selection-store-via-factory",
    subject: "packages/client/src/state/create-drill-selection-store.ts",
    operation: "raw-gated-store-mint",
    why: "the drill FACTORY itself composes the raw `createGatedStore` door on purpose — that composition IS the seal every per-section selection store mints through (derive-modernization-audit.md §W3 G27).",
    endsWhen:
      "the factory stops composing the door, or moves — either stales this row, where the legacy `/create-` FILENAME pattern would have exempted any future file with that prefix for free.",
  },
  {
    id: "selection-store-via-factory:create-kinded-selection-store",
    policyId: "selection-store-via-factory",
    subject: "packages/client/src/state/create-kinded-selection-store.ts",
    operation: "raw-gated-store-mint",
    why: "the kinded-selection factory, the same composition one shape over, named as its OWN row so a THIRD factory is judged rather than auto-exempt.",
    endsWhen: "the kinded factory stops composing the door, or moves.",
  },
  {
    id: "selection-store-via-factory:message-selection-store",
    policyId: "selection-store-via-factory",
    subject: "packages/client/src/state/message-selection-store.ts",
    operation: "raw-gated-store-mint",
    why: "the ONE `*-selection-store.ts` that is not a single-id drill: message selection is a bulk multi-select (presence in a Set keyed by message id, PD-119), a shape the drill factory does not model.",
    endsWhen: "the drill factory models bulk selection and this store migrates onto it.",
  },
  {
    id: "single-stream-transport:chat-impersonate-stream",
    policyId: "single-stream-transport",
    subject: "packages/server/src/transport/trpc/routers/chat.ts",
    operation: "sse-subscription:impersonateStream",
    why: "PERMANENT by owner ruling (sse-multiplex-spec.md §14 decision 2): request-scoped, user-gesture-initiated, at most one at a time, and its abort semantics ARE the socket teardown — folding it would mean modelling `detach = cancel generation`. This is the last survivor of the fold ledger; the six staged rows were deleted with the rooms they named.",
    endsWhen:
      "the spec is amended to fold impersonation onto the multiplexed socket; a fold that ships without deleting this row leaves it consumed zero times and reds.",
  },
  {
    id: "single-stream-transport:stream-connect",
    policyId: "single-stream-transport",
    subject: "packages/server/src/transport/trpc/routers/stream.ts",
    operation: "sse-subscription:connect",
    why: "THE one-socket home — the multiplex's own `.subscription(` lives here and every room rides it (sse-multiplex-spec.md §11). Keyed on the PROC so a SECOND subscription added to this same router is still red.",
    endsWhen:
      "the stream router moves or renames its connect proc; the row is then consumed zero times and reds at its dead identity instead of the exemption following the file.",
  },
  {
    id: "sole-env-reader:env-home-dynamic-key",
    policyId: "sole-env-reader",
    subject: "packages/server/src/foundation/env/index.ts",
    operation: "process-env-read",
    why: "THE sole reader (Tier-2-Foundation.md inv #1) — foundation/env is what parses and FREEZES `env` for every other tier, so it cannot import the frozen object it produces. This row covers the reads that name no static key: the `.env` loader's `process.env[key]` copy, the zod parse of the whole bag, and the raw snapshot the agent-sdk child env builders spread.",
    endsWhen: "the sole reader moves out of foundation/env, or stops making this read; the row is then consumed zero times and reds.",
  },
  {
    id: "sole-env-reader:env-home-orb-env-no-file",
    policyId: "sole-env-reader",
    subject: "packages/server/src/foundation/env/index.ts",
    operation: "process-env-read:ORB_ENV_NO_FILE",
    why: "THE sole reader (Tier-2-Foundation.md inv #1) — foundation/env is what parses and FREEZES `env` for every other tier, so it cannot import the frozen object it produces. The `.env` file load is skipped by this escape hatch, which must be read BEFORE the frozen object exists.",
    endsWhen: "the sole reader moves out of foundation/env, or stops making this read; the row is then consumed zero times and reds.",
  },
  {
    id: "sole-env-reader:env-home-orb-env-no-override",
    policyId: "sole-env-reader",
    subject: "packages/server/src/foundation/env/index.ts",
    operation: "process-env-read:ORB_ENV_NO_OVERRIDE",
    why: "THE sole reader (Tier-2-Foundation.md inv #1) — foundation/env is what parses and FREEZES `env` for every other tier, so it cannot import the frozen object it produces. Whether a checked-in dev `.env` overrides an already-set var is decided before the parse, so it cannot come from the parse's own output.",
    endsWhen: "the sole reader moves out of foundation/env, or stops making this read; the row is then consumed zero times and reds.",
  },
  {
    id: "sole-env-reader:env-home-vitest",
    policyId: "sole-env-reader",
    subject: "packages/server/src/foundation/env/index.ts",
    operation: "process-env-read:VITEST",
    why: "THE sole reader (Tier-2-Foundation.md inv #1) — foundation/env is what parses and FREEZES `env` for every other tier, so it cannot import the frozen object it produces. The test runner's own marker selects the no-override posture, and is read at module init before the frozen object exists.",
    endsWhen: "the sole reader moves out of foundation/env, or stops making this read; the row is then consumed zero times and reds.",
  },
  {
    id: "sole-env-reader:role-policy-oidc-admin-groups",
    policyId: "sole-env-reader",
    subject: "packages/server/src/domain/sessions/substrate/role-policy.ts",
    operation: "process-env-read:OIDC_ADMIN_GROUPS",
    why: "the IdP group whose members are granted admin — the group→role governance half. the role-derivation policy reads this governance var at CALL time rather than through the frozen `env` so per-test `vi.stubEnv` drives the role/access matrix; the exception is scoped to this one file and to exactly these keys, and any other key here is still red.",
    endsWhen:
      "role-policy stops reading this var at call time — which is the per-key ratchet the legacy SANCTIONED_KEYS ledger owned by hand, now the central zero-consumption alarm.",
  },
  {
    id: "sole-env-reader:role-policy-oidc-allowed-groups",
    policyId: "sole-env-reader",
    subject: "packages/server/src/domain/sessions/substrate/role-policy.ts",
    operation: "process-env-read:OIDC_ALLOWED_GROUPS",
    why: "the IdP group gate on login itself — the other governance half. the role-derivation policy reads this governance var at CALL time rather than through the frozen `env` so per-test `vi.stubEnv` drives the role/access matrix; the exception is scoped to this one file and to exactly these keys, and any other key here is still red.",
    endsWhen:
      "role-policy stops reading this var at call time — which is the per-key ratchet the legacy SANCTIONED_KEYS ledger owned by hand, now the central zero-consumption alarm.",
  },
  {
    id: "sole-env-reader:role-policy-owner-group",
    policyId: "sole-env-reader",
    subject: "packages/server/src/domain/sessions/substrate/role-policy.ts",
    operation: "process-env-read:OWNER_GROUP",
    why: "the IdP group that adopts the owner row. the role-derivation policy reads this governance var at CALL time rather than through the frozen `env` so per-test `vi.stubEnv` drives the role/access matrix; the exception is scoped to this one file and to exactly these keys, and any other key here is still red.",
    endsWhen:
      "role-policy stops reading this var at call time — which is the per-key ratchet the legacy SANCTIONED_KEYS ledger owned by hand, now the central zero-consumption alarm.",
  },
  {
    id: "sole-env-reader:role-policy-owner-handles",
    policyId: "sole-env-reader",
    subject: "packages/server/src/domain/sessions/substrate/role-policy.ts",
    operation: "process-env-read:OWNER_HANDLES",
    why: "the handle list that adopts the owner row. the role-derivation policy reads this governance var at CALL time rather than through the frozen `env` so per-test `vi.stubEnv` drives the role/access matrix; the exception is scoped to this one file and to exactly these keys, and any other key here is still red.",
    endsWhen:
      "role-policy stops reading this var at call time — which is the per-key ratchet the legacy SANCTIONED_KEYS ledger owned by hand, now the central zero-consumption alarm.",
  },
  {
    id: "sole-env-reader:role-policy-re-derive-role-on-login",
    policyId: "sole-env-reader",
    subject: "packages/server/src/domain/sessions/substrate/role-policy.ts",
    operation: "process-env-read:RE_DERIVE_ROLE_ON_LOGIN",
    why: "whether a login re-derives the stored role from current group membership. the role-derivation policy reads this governance var at CALL time rather than through the frozen `env` so per-test `vi.stubEnv` drives the role/access matrix; the exception is scoped to this one file and to exactly these keys, and any other key here is still red.",
    endsWhen:
      "role-policy stops reading this var at call time — which is the per-key ratchet the legacy SANCTIONED_KEYS ledger owned by hand, now the central zero-consumption alarm.",
  },
  {
    id: "tooling-argv-front-door:shared-entrypoint",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/_shared/entrypoint.ts",
    operation: "process-argv-read",
    why: "reads argv[1] — the ENTRY IDENTITY ('was this module the program?'), never the operator's flags; it is the one home for that question (Core-Tooling-Law §4.9).",
    endsWhen: "the direct-invocation refusal moves or stops asking it — the row is then consumed zero times and reds at its dead subject.",
  },
  {
    id: "tooling-argv-front-door:stack-dev-identity-entry",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/stack/ops/dev-identity-entry.ts",
    operation: "process-argv-read",
    why: "the node half stack.sh execs for the dev-identity verbs — a BASH_FRONTED_TOOLS tool has no cli.ts (Core-Tooling-Law §2.5/§4.1), so the node half it execs is the argv front door itself.",
    endsWhen: "stack grows a cli.ts or this entry is retired — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-argv-front-door:stack-engines",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/stack/ops/engines.ts",
    operation: "process-argv-read",
    why: "the node half engines.sh setsid-execs to boot the fleet (`--detach`) — the same bash-fronted exception (Core-Tooling-Law §2.5).",
    endsWhen: "the launcher moves behind a cli.ts — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-argv-front-door:stack-engines-ctl",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/stack/ops/engines-ctl.ts",
    operation: "process-argv-read",
    why: "the node half engines.sh execs for status/stop/sleep/wake/reconcile — the same bash-fronted exception (Core-Tooling-Law §2.5).",
    endsWhen: "the fleet front door stops being bash — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-argv-front-door:stack-prod-entry",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/stack/ops/prod-entry.ts",
    operation: "process-argv-read",
    why: "the node half stack.sh execs for every PROD invocation — the same bash-fronted exception (Core-Tooling-Law §2.5).",
    endsWhen: "stack grows a cli.ts or this entry is retired — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-argv-front-door:verify-config-snapshot-entry",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/verify/ops/config-snapshot-entry.ts",
    operation: "process-argv-read",
    why: "the private process boundary reads native config snapshots and ESLint's discovery-only filename list without eagerly importing the whole verify CLI; its argv is a parent-authored request validated by those operations, never a second operator door (#1351).",
    endsWhen: "both observations move in-process or behind a different worker — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-artifact-path-home:artifacts",
    policyId: "tooling-artifact-path-home",
    subject: "tooling/src/_shared/artifacts.ts",
    operation: "reports-path-literal",
    why: "THE artifact root home: `reportsPath`/`reportsRelPath`/`ensureReportsDir` are the one spelling of `reports/…` in the repo, and the run-slot layout (#1029/#1164) is built on them (Core-Tooling-Law.md §4.4, arm C of the retired plumbing gate).",
    endsWhen:
      "the artifact root moves out of artifacts.ts — the row is then consumed zero times and reds at its dead subject, which is the legacy HOMES stale sweep.",
  },
  {
    id: "tooling-browser-door:browser-attach",
    policyId: "tooling-browser-door",
    subject: "tooling/src/_shared/browser.ts",
    operation: "browser-attach",
    why: "`attachProbeSession` IS the one door onto a stateful session daemon's browser (docs/design/1208-instrument-substrate.md §3.4): the `connectOverCDP` here is the attach every consumer rides, shape-identical to a launched session (arm H of the retired plumbing gate).",
    endsWhen: "the attach moves out of browser.ts or the daemon stops exposing a debugging endpoint — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-browser-door:browser-launch",
    policyId: "tooling-browser-door",
    subject: "tooling/src/_shared/browser.ts",
    operation: "browser-launch",
    why: "`launchProbeSession` IS the one Playwright bootstrap: the `chromium.launch` here carries the marked args/env and the run-marker every instrument's browser must wear (arm B of the retired plumbing gate).",
    endsWhen: "the launch moves out of browser.ts — the row is then consumed zero times and reds at its dead subject.",
  },
  {
    id: "tooling-child-process-door:proc",
    policyId: "tooling-child-process-door",
    subject: "tooling/src/_shared/proc.ts",
    operation: "child-process-import",
    why: "THE subprocess home: proc.ts is where `node:child_process` is imported so every tooling spawn rides the nice -19 homelab floor (`spawnNiced`/`runNicedSync`/`spawnNicedChild`); the two full-priority doors are defined here too (arm F of the retired plumbing gate).",
    endsWhen: "the subprocess home moves — the row is then consumed zero times and reds at its dead subject, which is the legacy HOMES stale sweep.",
  },
  {
    id: "tooling-child-process-door:snap-session-client",
    policyId: "tooling-child-process-door",
    subject: "tooling/src/snap/ops/session-client.ts",
    operation: "full-priority-spawn",
    why: "the session daemon owns the interactive Chromium a human drives across calls — nice 19 silently changes motion/performance evidence (the legacy FULL_PRIORITY_CALLERS row, carried verbatim).",
    endsWhen: "the daemon stops hosting the interactive browser or its spawn moves — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-child-process-door:snap-stage",
    policyId: "tooling-child-process-door",
    subject: "tooling/src/snap/ops/stage.ts",
    operation: "full-priority-spawn",
    why: "the stage stack BOOT serves interactive snap navigations — a -19 staged app times out captures under load (the legacy FULL_PRIORITY_CALLERS row, carried verbatim).",
    endsWhen: "the stage boot moves or drops the exception — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-child-process-door:stack-engines",
    policyId: "tooling-child-process-door",
    subject: "tooling/src/stack/ops/engines.ts",
    operation: "full-priority-spawn",
    why: "the vLLM engines ARE the inference workload the operator waits on — a -19 engine degrades the interactive token latency the fleet exists to provide (the legacy FULL_PRIORITY_CALLERS row, carried verbatim).",
    endsWhen: "the fleet launcher moves or stops spawning — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-child-process-door:stack-prod-up",
    policyId: "tooling-child-process-door",
    subject: "tooling/src/stack/ops/prod-up.ts",
    operation: "full-priority-spawn",
    why: "the child it spawns IS the production server answering the operator's requests — a -19 app is the thing the launcher exists to run, degraded (the legacy FULL_PRIORITY_CALLERS row, carried verbatim).",
    endsWhen: "the prod spawn moves or drops the exception — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-port-registry:ports",
    policyId: "tooling-port-registry",
    subject: "tooling/src/_shared/ports.ts",
    operation: "port-literal",
    why: "THE port registry — the one home every reserved row and stage band is declared in, and the table the policy imports to know what a port number even is (the legacy PORT_HOME row; docs/design/1208-instrument-substrate.md §3.6).",
    endsWhen: "the registry moves, or stops declaring ports — which is the day it stopped being the registry; the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-process-exit-home:run-tool",
    policyId: "tooling-process-exit-home",
    subject: "tooling/src/_shared/run-tool.ts",
    operation: "process-exit",
    why: "THE exit-honesty runner: the crash path's hard exit lives here and nowhere else — every verdict path sets `process.exitCode` and lets the loop drain (arm D of the retired plumbing gate).",
    endsWhen: "the runner's hard exit moves — the row is then consumed zero times and reds at its dead subject, which is the legacy HOMES stale sweep.",
  },
  {
    id: "tooling-project-home:baseui-read",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/lib/baseui-read.ts",
    operation: "ts-morph-project-construction",
    why: "loads the INSTALLED @base-ui/react `.d.ts` surface out of packages/ui/node_modules — not workspace source, not in harnessGlobs, and unreadable any other way, so the manifest would have nothing to adjudicate against (the legacy PROJECT_SITES row, carried verbatim).",
    endsWhen: "the surface is ever vendored INTO the workspace — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:comment-spans",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/lib/comment-spans.ts",
    operation: "ts-morph-project-construction",
    why: "an in-memory SCRATCH parser (`useInMemoryFileSystem`) for ONE string of text read off real disk — it resolves no dependency and walks no workspace; it exists so a `//` inside a string literal is still not a comment (the legacy PROJECT_SITES row; three constructions, one grant).",
    endsWhen: "comment blanking ever reads from the shared project instead of raw text — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:config-static-read",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/lib/config-static-read.ts",
    operation: "ts-morph-project-construction",
    why: "ONE scratch parser (`useInMemoryFileSystem`) for exact code outside the governed workspace corpus: the root eslint/dep-cruiser configs, Playwright's CT bootstrap, and now the three root runner configs delivered as `exact-file` facts. Loading them into harnessGlobs would widen every gate's jurisdiction; separate parsers per consumer would violate the one-parser census (the legacy PROJECT_SITES row).",
    endsWhen: "every such file joins the governed corpus or stops needing AST reads — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:dangling-refs",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/gates/dangling-refs.ts",
    operation: "ts-morph-project-construction",
    why: "fsBacked: reads gate descriptor SOURCE off real disk (readdirSync over the gates dir) so it works identically inside a conformance temp tree, where the shared workspace does not exist (the legacy PROJECT_SITES row, carried verbatim).",
    endsWhen:
      "the arm is folded onto the shared project the way diagnostic-legibility was (§2.2), or the gate converts — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:enforcement-registry-parity",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/gates/enforcement-registry-parity.ts",
    operation: "ts-morph-project-construction",
    why: "fsBacked, same reason as dangling-refs: it reconciles the on-disk gate corpus against the enforcement doc, and a conformance temp tree has no shared workspace to read from (the legacy PROJECT_SITES row, carried verbatim).",
    endsWhen: "the same diagnostic-legibility-style fold-in, or the gate converts — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:ops-conformance",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/ops/conformance.ts",
    operation: "ts-morph-project-construction",
    why: "materializes each LEGACY gate's mustFlag/mustPass example as its OWN synthetic mini-project (in-memory, or a real temp dir for an fsBacked gate) — a self-proof run over the shared workspace would prove nothing about the example (the legacy PROJECT_SITES row; two constructions, one grant).",
    endsWhen: "the legacy conformance runner retires at the gate-runtime cutover (#1584) — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:ops-policy-conformance",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/ops/policy-conformance.ts",
    operation: "ts-morph-project-construction",
    why: "materializes each FINAL policy's proof as its own mini-project (a virtual project for source/types rows, a real temp dir plus an in-memory parser for resource rows) and hosts the shared scratch parser the twin rewriter reads — three constructions the legacy census never listed, RED on the live tree under the legacy gate itself and licensed here for what they load (#1950 group 4; the module belongs to another lane and is not edited).",
    endsWhen:
      "policy conformance stops being example-driven, or its parsers fold onto `lib/config-static-read.ts`'s scratch — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:spelling-twins",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/lib/spelling-twins.ts",
    operation: "ts-morph-project-construction",
    why: "an in-memory SCRATCH parser (`useInMemoryFileSystem`) that parses each gate's mustFlag fixture STRING at its OWN virtual path to emit its bracket/namespace twins (#1506) — resolves no dependency, walks no workspace, and cannot ride comment-spans' door (that one reuses a single overwritten SourceFile; the namespace twin walks references and needs the fixture's own extension) (the legacy PROJECT_SITES row).",
    endsWhen: "the twin rewriter becomes purely textual or moves onto conformance's per-example mini-project — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:ts-workspace",
    policyId: "tooling-project-home",
    subject: "tooling/src/_shared/ts-workspace.ts",
    operation: "ts-morph-project-construction",
    why: "THE ts-morph loader (`getWorkspace`): the one home the shared workspace is loaded from, once, so every gate walks one project (Core-Tooling-Law.md §2.4/§4.4, arm A of the retired plumbing gate).",
    endsWhen: "the loader moves — the row is then consumed zero times and reds at its dead subject, which is the legacy HOMES stale sweep.",
  },
  {
    id: "tooling-root-config-import:prodonly-knip",
    policyId: "tooling-root-config-import",
    subject: "tooling/src/ast/ops/prodonly.ts",
    operation: "root-config-import:knip.ts",
    why: "ast/ops/prodonly derives its entry closure from the ONE knip workspace-entry config — re-spelling the globs is the one-home violation the front-door law exists to kill (P4 of #393, Core-Tooling-Law §4.2).",
    endsWhen:
      "prodonly stops deriving its closure from knip.ts, or knip's entry config moves — the row is then consumed zero times and reds at its dead subject, which is the two-sided stale sweep the legacy ROOT_CONFIG_IMPORTS table carried by hand.",
  },
  {
    id: "tsconfig-entry-liveness:g-fixture-file",
    policyId: "tsconfig-entry-liveness",
    subject: "**/__g_*",
    operation: "tsconfig-glob-entry",
    why: "the reserved throwaway-fixture sentinel: check-gates.int materialises `__g_*` files at real-tree paths for milliseconds and reaps them, so the subject is ABSENT from every tracked source BY CONSTRUCTION — an exclude that must PRE-EXIST the fixture it excludes. Law: tooling/src/verify/gates/GATE-AUTHORING.md.",
    endsWhen: "the `__g_` fixture sentinel is retired with the legacy gate runtime — the entry then leaves every tsconfig and this row is consumed zero times.",
  },
  {
    id: "tsconfig-entry-liveness:g-fixture-tree",
    policyId: "tsconfig-entry-liveness",
    subject: "**/__g_*/**",
    operation: "tsconfig-glob-entry",
    why: "the DIRECTORY half of the `__g_` sentinel exclude — same construction as its sibling row, same law (tooling/src/verify/gates/GATE-AUTHORING.md): the tree exists for milliseconds mid-run and is tracked never.",
    endsWhen: "the `__g_` fixture sentinel is retired — it dies with its file-half sibling, never alone.",
  },
  {
    id: "tsconfig-entry-liveness:node-modules",
    policyId: "tsconfig-entry-liveness",
    subject: "**/node_modules",
    operation: "tsconfig-glob-entry",
    why: "INSTALLED DEPENDENCIES: node_modules is gitignored (.gitignore), so it is absent from the tracked corpus by design and present only after an install — judging it either way would make the verdict depend on machine state, which is the whole reason this family reads `git ls-files` rather than the filesystem.",
    endsWhen: "the type programs stop needing to exclude installed packages.",
  },
  {
    id: "tsconfig-entry-liveness:scripts-cts",
    policyId: "tsconfig-entry-liveness",
    subject: "scripts/**/*.cts",
    operation: "tsconfig-glob-entry",
    why: "the Node world root declares EVERY authored TypeScript dialect before its first `scripts` .cts file, so a future authored file cannot be silently unowned by any program (docs/architecture/core/Core-Tooling-Law.md).",
    endsWhen: "the first scripts/**/*.cts source lands — the glob acquires a member, the finding disappears and this row is consumed zero times.",
  },
  {
    id: "tsconfig-entry-liveness:scripts-mts",
    policyId: "tsconfig-entry-liveness",
    subject: "scripts/**/*.mts",
    operation: "tsconfig-glob-entry",
    why: "the same pre-declaration, for the `.mts` dialect: the Node world root owns every authored dialect under scripts/ before the first file of that dialect exists (docs/architecture/core/Core-Tooling-Law.md).",
    endsWhen: "the first scripts/**/*.mts source lands.",
  },
  {
    id: "tsconfig-entry-liveness:scripts-tsx",
    policyId: "tsconfig-entry-liveness",
    subject: "scripts/**/*.tsx",
    operation: "tsconfig-glob-entry",
    why: "the BROWSER world root declares TSX scripts before its first member so a future authored file cannot be silently unowned — the DOM half of the same pre-declaration (docs/architecture/core/Core-Tooling-Law.md).",
    endsWhen: "the first scripts/**/*.tsx source lands.",
  },
  {
    id: "tsconfig-entry-liveness:st-goldens-runtime",
    policyId: "tsconfig-entry-liveness",
    subject: "scripts/probes/st-goldens/sillytavern-runtime",
    operation: "tsconfig-exact-entry",
    why: "not a dead entry — a GITIGNORED captured SillyTavern install, absent on a clean checkout by design. The root aggregator EXCLUDES it so its four root .d.ts files, which declare ST's browser globals into our global scope, never join the program. Evidence: scripts/probes/st-goldens/README.md.",
    endsWhen:
      "scripts/probes/st-goldens stops shipping a gitignored runtime subtree — the exclude then names nothing anybody would create and leaves the config.",
  },
  {
    id: "tsconfig-entry-liveness:tests-cts",
    policyId: "tsconfig-entry-liveness",
    subject: "tests/**/*.cts",
    operation: "tsconfig-glob-entry",
    why: "the Node world root's dialect pre-declaration for the test tree, identical in kind to its scripts siblings (docs/architecture/core/Core-Tooling-Law.md).",
    endsWhen: "the first tests/**/*.cts source lands.",
  },
  {
    id: "tsconfig-entry-liveness:tests-iso-helpers",
    policyId: "tsconfig-entry-liveness",
    subject: "tests/support/iso/**/*",
    operation: "tsconfig-glob-entry",
    why: "the explicit ISO-helper root exists before its first helper BY DESIGN; reset.d.ts + platform.d.ts keep the compiler leaf measurable meanwhile (docs/architecture/core/Core-Tooling-Law.md). The entry is authored in three configs — one include and two excludes — and is one permission, which is why the grant subject is the entry rather than a per-config coordinate.",
    endsWhen: "the first tests/support/iso source lands.",
  },
  {
    id: "two-class-role-authority:admin-guard-can-seam",
    policyId: "two-class-role-authority",
    subject: "packages/server/src/domain/admin/guard.ts",
    operation: "enforcement-role-comparison",
    why: "the `can()` seam itself — spine invariant #6: the chat resource-role verdict is DECIDED here and nowhere else, so the comparison must be spelled here exactly once.",
    endsWhen:
      "the kernel stops comparing the participant role directly (a resource-role table replaces the switch); the row is then consumed zero times and reds.",
  },
  {
    id: "two-class-role-authority:chat-nominee-target",
    policyId: "two-class-role-authority",
    subject: "packages/server/src/domain/chat/verbs/participants.ts",
    operation: "enforcement-role-comparison",
    why: "the host compare is on the NOMINEE (`nominee.role === 'host'` → ChatNotFound) — a TARGET-VALIDITY check on the handoff candidate, not the caller's privilege; the caller's gate is the `requireHost` on the line above it.",
    endsWhen: "target validity moves behind a chokepoint helper that owns the leak-free refusal for a nominee as well as for a caller.",
  },
  {
    id: "two-class-role-authority:chat-participant-shape",
    policyId: "two-class-role-authority",
    subject: "packages/server/src/domain/chat/persistence/participant.ts",
    operation: "enforcement-role-comparison",
    why: "`assertForcedCharacterMember` is the runtime twin of the `chat_participants` CHECK constraint — a persisted-row SHAPE invariant (a character seat can never be the host), not a caller-privilege gate. The legacy reader was blind to it because it hardcoded the `host` literal and this assertion names `member`.",
    endsWhen: "the row shape is guaranteed by the schema alone at every write path, so the runtime twin can be deleted.",
  },
  {
    id: "zod-error-issues-home:persona-write-guard",
    policyId: "zod-error-issues-home",
    subject: "packages/contracts/src/persona/index.ts",
    operation: "error-issues-read",
    why: "a write-guard RE-EMIT, not a message render: `personaMetadataWriteSchema`'s superRefine forwards each inner issue as `ctx.addIssue({code:'custom', message, path})`. It keeps `path`, which `prettifyError` cannot — that returns a STRING and would collapse the whole issue array into one opaque message on the outer error.",
    endsWhen: "the metadata write guard stops re-emitting inner issues (the inner schema is composed directly into the outer one).",
  },
  {
    id: "zod-error-issues-home:rpg-extraction",
    policyId: "zod-error-issues-home",
    subject: "packages/contracts/src/rpg/extraction.ts",
    operation: "error-issues-read",
    why: "MODEL-facing: `issueLines` renders the salvage drop list in the same `path: message` convention. The shared-plane proof means the structured plane and its tool validate through the identical schema, so the two refusal texts must agree.",
    endsWhen: "the structured plane and its tool stop sharing one schema, at which point the two texts no longer have to agree.",
  },
  {
    id: "zod-error-issues-home:schema-forge",
    policyId: "zod-error-issues-home",
    subject: "packages/server/src/domain/refinery/substrate/schema-forge.ts",
    operation: "error-issues-read",
    why: "STRUCTURAL RE-EMIT: the §4.5 lift-refusal bridge maps each document-belt issue into the OUTER envelope parse (`ctx.addIssue({path: issue.path, …})`) so the bounded retry's correction prompt carries construct plus path to the MODEL. The path is forwarded, never dropped, and prettify returns a STRING that would collapse the array.",
    endsWhen: "the lift refusal stops being re-emitted into an outer parse (the belt reports its own refusal directly).",
  },
  {
    id: "zod-error-issues-home:structured-turn",
    policyId: "zod-error-issues-home",
    subject: "packages/server/src/kit/structured-turn/index.ts",
    operation: "error-issues-read",
    why: "MODEL-facing: the issue summary is fed straight BACK to the model as the retry prompt (`args.run(first.issues)`), so it must be the schema-addressable `path: message` form rather than a human-formatted tree.",
    endsWhen: "the structured-turn retry stops re-prompting with the parse issues.",
  },
  {
    id: "zod-error-issues-home:tool-register",
    policyId: "zod-error-issues-home",
    subject: "packages/server/src/domain/tool-use/verbs/register.ts",
    operation: "error-issues-read",
    why: "MODEL-facing: the tool registry hands the failing model `path.join('.') + ': ' + message` so it can match the refusal against its own arg schema. The path is CARRIED, not dropped — the opposite of the F4 defect — and `z.prettifyError`'s human layout is the wrong shape for a wire the model re-reads.",
    endsWhen: "tool refusals stop being fed back to a model verbatim, at which point the human renderer is the right one.",
  },
  {
    id: "zod-error-issues-home:tool-register-plugin",
    policyId: "zod-error-issues-home",
    subject: "packages/server/src/domain/tool-use/verbs/register-plugin-tool.ts",
    operation: "error-issues-read",
    why: "MODEL-facing, the plugin twin of `register.ts` — the identical `path: message` convention, deliberately kept byte-identical between the two registration doors so a model sees one refusal vocabulary.",
    endsWhen: "the two registration doors stop sharing a refusal vocabulary, or tool refusals stop being model-facing.",
  },
  {
    id: "zod-error-issues-home:versioned-config",
    policyId: "zod-error-issues-home",
    subject: "packages/contracts/src/versioned-config/index.ts",
    operation: "error-issues-read",
    why: "the structured FIRST issue (path plus message) IS this contract's parse-outcome payload (#1592): the import refusal needs the PATH to name the offending field, which `z.prettifyError` flattens into prose, and nothing here prints a raw message. TRANSLATED FROM A MARKER — the site carried a permanent `@orb-gate-ignore`, and a reviewed-grant policy has no inline door, so the standing permission is this row and the marker is deleted.",
    endsWhen: "the degraded-parse payload stops carrying a field path (the caller renders the whole refusal itself).",
  },
  {
    id: "zod-error-issues-home:world-info-write-guard",
    policyId: "zod-error-issues-home",
    subject: "packages/contracts/src/world-info/index.ts",
    operation: "error-issues-read",
    why: "the same write-guard RE-EMIT for `entryMetadataWriteSchema`, whose header cites the persona rationale verbatim — issues forwarded structurally with their paths, never flattened to a display string.",
    endsWhen: "the entry write guard stops re-emitting inner issues (the inner schema is composed directly into the outer one).",
  },
]);

/** The rows a partial invocation may pass: a grant naming a policy the run does not know is a tool error by
 *  contract, so a pre-cutover real-tree receipt over a hand-picked roster filters to that roster first. */
export function reviewedGrantsFor(policies: readonly Pick<SelectedGatePolicy, "id">[]): readonly ReviewedGateGrant[] {
  const known = new Set(policies.map(({ id }) => id));
  return REVIEWED_GRANTS.filter((grant) => known.has(grant.policyId));
}
