// Reviewed grants: no-raw-egress, no-raw-interactive-intrinsics, no-raw-intl-time, no-raw-matchmedia, no-raw-random....
// Split from reviewed-grants.ts — see that file for the central home comment.
import type { ReviewedGateGrant } from "../contract/gate-authority.ts";

export const REVIEWED_GRANTS_NO_TO_FACTORY: readonly ReviewedGateGrant[] = [
      {
        id: "no-raw-egress:vllm-fleet-control",
        policyId: "no-raw-egress",
        subject: "packages/server/src/infra/providers/vllm/engine/fleet-control.ts",
        operation: "raw-fetch",
        why: "the engine LIFECYCLE control plane (`POST /sleep`) against a loopback engine this process supervises — no auth, no credential, no user-influenced URL, and a hard `AbortSignal.timeout`.",
        endsWhen: "engine traffic leaves loopback, at which point the lifecycle plane needs the SSRF guard rather than this row.",
      },
      {
        id: "no-raw-egress:vllm-gen-window",
        policyId: "no-raw-egress",
        subject: "packages/server/src/infra/providers/vllm/engine/gen-window.ts",
        operation: "raw-fetch",
        why: "the loopback `GET /v1/models` read that discovers an engine's context window; a failure degrades to the env-owned window. Same loopback, no-credential class as the rest of the engine plane.",
        endsWhen: "engine traffic leaves loopback, at which point this read needs the SSRF guard rather than this row.",
      },
      {
        id: "no-raw-egress:vllm-supervisor",
        policyId: "no-raw-egress",
        subject: "packages/server/src/infra/providers/vllm/engine/supervisor.ts",
        operation: "raw-fetch",
        why: "the loopback `/is_sleeping` HEALTH probe the supervisor uses to decide whether an engine needs waking; any failure reads as not-sleeping (fails toward healthy). Same loopback, no-credential class as the rest of the engine plane.",
        endsWhen: "engine traffic leaves loopback, at which point the health probe needs the SSRF guard rather than this row.",
      },
      {
        id: "no-raw-interactive-intrinsics:app-shell-surface",
        policyId: "no-raw-interactive-intrinsics",
        subject: "packages/client/src/features/app-shell/surfaces/app-shell.tsx",
        operation: "raw-interactive-intrinsic:button",
        why: "the SHELL tier composes the app frame BELOW the primitive layer, which design-enforcement.md §3.2 (D62) exempts — this control is part of the frame an @orb/ui Button is rendered inside, not a feature affordance. Narrowed from the legacy DIRECTORY row: the permission is now this one file, so a second shell file hosting a raw control reds until someone reviews it.",
        endsWhen:
          "the shell's own control is expressible through an @orb/ui primitive without a frame cycle, or the shell moves — either way the row is consumed zero times and reds at its dead subject.",
      },
      {
        id: "no-raw-intl-time:kit-time",
        policyId: "no-raw-intl-time",
        subject: "packages/kit/src/time/index.ts",
        operation: "intl-formatter",
        why: "`@orb/kit/time` IS the memoized Intl seam: `createTimeLib` constructs the `DateTimeFormat`/`RelativeTimeFormat` instances it then hands every call site, which is the whole reason the rest of the repo may not.",
        endsWhen:
          "time formatting moves off Intl, or the time engine leaves this file — the row stales at its dead path instead of exempting one that no longer exists.",
      },
      {
        id: "no-raw-matchmedia:coarse-pointer-now",
        policyId: "no-raw-matchmedia",
        subject: "packages/ui/src/lib/coarse-pointer-now.ts",
        operation: "raw-match-media",
        why: "the ONE (pointer: coarse) home minted by #1182 (`coarsePointerNow()`, the imperative twin of the reduced-motion pair): every coarse-pointer read in @orb/ui and the client goes through it, so the raw `matchMedia` read belongs here and nowhere else — the same recurring permission the two reduced-motion homes carry.",
        endsWhen:
          "the pointer-coarseness read moves into a shared media-query seam that also serves the reduced-motion homes, or the browser exposes the fact without matchMedia.",
      },
      {
        id: "no-raw-matchmedia:media-grid",
        policyId: "no-raw-matchmedia",
        subject: "packages/ui/src/primitives/media-grid/media-grid.tsx",
        operation: "raw-match-media",
        why: "a POINTER-CAPABILITY query (`(pointer: fine)`), which the reduced-motion one-homes do not cover. `#1182` landed a coarse-pointer imperative one-home (`coarsePointerNow()`), but that reader answers `(pointer: coarse)` — a DIFFERENT query, not this call's logical inverse (a `pointer: none` device matches neither), so it does not serve this read; the one-home's existence narrows the gap this row licenses, it does not close it. This was the permanent `@orb-gate-ignore` that used to sit at the call site, translated: a reviewed-grant policy has no inline door, and a standing permission belongs in the reviewed table rather than in a comment one author can write.",
        endsWhen: "a `(pointer: fine)` one-home lands beside `coarsePointerNow()` in `@orb/ui/src/lib/` and this call reads it instead.",
      },
      {
        id: "no-raw-matchmedia:reduced-motion-now",
        policyId: "no-raw-matchmedia",
        subject: "packages/ui/src/lib/reduced-motion-now.ts",
        operation: "raw-match-media",
        why: "the imperative reduced-motion one-home (`prefersReducedMotionNow()`) — the point-in-time half of the pair the rule points every caller at.",
        endsWhen: "the imperative reader is served by the render hook's cached query instead of its own read, or the home moves.",
      },
      {
        id: "no-raw-matchmedia:use-is-mobile-viewport",
        policyId: "no-raw-matchmedia",
        subject: "packages/client/src/features/app-shell/hooks/use-is-mobile-viewport.ts",
        operation: "raw-match-media",
        why: "the shell's viewport one-home: the ONE place the mobile-viewport fact is read, which the rest of the client then reads off `#state` rather than re-querying (the store's own header points at this hook by name).",
        endsWhen: "the viewport fact is published by something other than a media query, or the hook moves out of the shell.",
      },
      {
        id: "no-raw-matchmedia:use-prefers-reduced-motion",
        policyId: "no-raw-matchmedia",
        subject: "packages/ui/src/lib/use-prefers-reduced-motion.ts",
        operation: "raw-match-media",
        why: "the render-time reduced-motion one-home: one `matchMedia` + `useSyncExternalStore` subscription for every non-CSS motion path.",
        endsWhen: "reduced motion is read from a CSS-driven signal instead, or the home moves.",
      },
      {
        id: "no-raw-random:entry-compose-chat",
        policyId: "no-raw-random",
        subject: "packages/server/src/entry/compose/chat.ts",
        operation: "ambient-entropy-draw",
        why: "the composition root SEEDS the turn PRNG it injects into the chat engine (Tier-5-Entry.md) — the seed has to be drawn somewhere, and the root is the one tier allowed to.",
        endsWhen: "the seed is supplied to the root as an injected value rather than drawn here; the row is then consumed zero times and reds.",
      },
      {
        id: "no-raw-zustand-persist:create-entity-draft-store-persist",
        policyId: "no-raw-zustand-persist",
        subject: "packages/client/src/state/create-entity-draft-store.ts",
        operation: "zustand-persist-mint",
        why: "the draft-store factory bakes the footguns in (partialize / version+total-migrate / key uniqueness); the `persist(` call it wraps IS the seal every draft store then mints through.",
        endsWhen:
          "the factory stops calling `persist` or leaves the project — both of which stale this row, which is the two-sided liveness the module used to implement itself.",
      },
      {
        id: "no-raw-zustand-persist:create-entity-draft-store-reset",
        policyId: "no-raw-zustand-persist",
        subject: "packages/client/src/state/create-entity-draft-store.ts",
        operation: "destructive-store-reset",
        why: "the factory's own `reset` closure is what the durable-local registry drives through `resetWithoutPersisting`, which blindfolds the store's storage first — so the destructive reset here is the in-memory drop #837 requires, not the write-through it forbids.",
        endsWhen: "the factory's reset stops being driven behind the storage blindfold.",
      },
      {
        id: "no-raw-zustand-persist:create-persisted-store-persist",
        policyId: "no-raw-zustand-persist",
        subject: "packages/client/src/state/create-persisted-store.ts",
        operation: "zustand-persist-mint",
        why: "the general persisted-store factory, the same seal one shape over.",
        endsWhen: "the factory stops calling `persist` or leaves the project.",
      },
      {
        id: "no-raw-zustand-persist:create-persisted-store-reset",
        policyId: "no-raw-zustand-persist",
        subject: "packages/client/src/state/create-persisted-store.ts",
        operation: "destructive-store-reset",
        why: "the same registered-reset closure on the general factory, driven through the same blindfolded door.",
        endsWhen: "the factory's reset stops being driven behind the storage blindfold.",
      },
      {
        id: "no-untyped-soft-ref:audit-logs-entity",
        policyId: "no-untyped-soft-ref",
        subject: "audit_logs.entityId",
        operation: "soft-reference",
        why: "the append-only audit log must outlive an arbitrary referent of unknown TYPE — the one D24 sanctioned soft ref. An FK would either pin the log to one table or delete history with its subject, and the log's whole purpose is to survive both.",
        endsWhen:
          "the audit log stops recording polymorphic referents (each entity kind gains its own typed log table), at which point this column can carry a real FK.",
      },
      {
        id: "no-untyped-soft-ref:automation-rule-preset",
        policyId: "no-untyped-soft-ref",
        subject: "automation_rules.rulePresetId",
        operation: "soft-reference",
        why: "a rule-preset CATALOGUE id (`RULE_PRESET_IDS`, @orb/contracts/automation) — a member of a closed CODE tuple, not a row of any table, so there is nothing to FK. Coherence is the wire's z.enum at write plus the live-catalogue re-check at read/apply, where an orphaned id degrades to a reported skip.",
        endsWhen: "the rule-preset catalogue becomes a table, at which point every catalogue id gains a real FK.",
      },
      {
        id: "no-untyped-soft-ref:roster-rule-preset",
        policyId: "no-untyped-soft-ref",
        subject: "roster_preset_rules.rulePresetId",
        operation: "soft-reference",
        why: "the same rule-preset CATALOGUE id on the saved-roster side — the cast's captured rule, a code-tuple member rather than a row (D24-external), with the same enum-at-write plus re-check-at-apply coherence.",
        endsWhen: "the rule-preset catalogue becomes a table, at which point every catalogue id gains a real FK.",
      },
      {
        id: "no-untyped-soft-ref:sdk-session-handle",
        policyId: "no-untyped-soft-ref",
        subject: "session_entries.sdkSessionId",
        operation: "soft-reference",
        why: "the Claude Agent SDK's OWN resume handle — the prompt-cache lineage id the SDK returns (D8/D25). An EXTERNAL identifier owned by the vendor runtime, not a reference to any orbweaver table.",
        endsWhen: "the SDK session becomes an orbweaver-owned row rather than a vendor handle we carry.",
      },
      {
        id: "no-untyped-soft-ref:users-external",
        policyId: "no-untyped-soft-ref",
        subject: "users.externalId",
        operation: "soft-reference",
        why: "an external IdP subject identifier (the SSO `sub`) — a string minted by another system, not a reference to any orbweaver table, so there is nothing for an FK to point at.",
        endsWhen: "identity stops being federated and the subject becomes an orbweaver row.",
      },
      {
        id: "no-untyped-soft-ref:variant-generation",
        policyId: "no-untyped-soft-ref",
        subject: "message_variants.generationId",
        operation: "soft-reference",
        why: "the upstream OpenRouter generation handle (`gen-…`) a variant was billed under — an EXTERNAL provider id (`connection.orGenerationCost`'s key, PD-137), not a reference to any orbweaver table (D24).",
        endsWhen: "generation records are persisted as orbweaver rows, at which point the column can carry a real FK.",
      },
      {
        id: "open-json-column-key-parity:character-extensions",
        policyId: "open-json-column-key-parity",
        subject: "characters.extensions",
        operation: "open-json-key-read",
        why: "The ST/V2 card extensions field is a foreign-authored residue bucket with an intentionally open vocabulary; import and serde promote known keys defensively while preserving unknown keys losslessly.",
        endsWhen: "all named extension readers move onto a typed promoted contract and the residue has no named reader, or the column closes its vocabulary.",
      },
      {
        id: "owner-role-split:admin-create-user",
        policyId: "owner-role-split",
        subject: "packages/server/src/domain/admin/verbs/create-user.ts",
        operation: "global-role-comparison",
        why: "the owner is the immutable bootstrap row and is never minted through admin, so this verb refuses to ASSIGN the owner role even to an owner caller. This is a TARGET-VALIDITY check on the owner ROW, not a caller-privilege gate: `can()` decides whether a principal may act, and it structurally cannot answer whether the row being acted on is the immutable bootstrap owner. The legacy text reader was blind to it because the literal is the `OWNER_ROLE` const rather than a quoted string.",
        endsWhen: "the admin guard exposes an owner-immutability decision the verbs call, instead of each verb comparing the global-role value itself.",
      },
      {
        id: "owner-role-split:admin-link-sso-identity",
        policyId: "owner-role-split",
        subject: "packages/server/src/domain/admin/verbs/link-sso-identity.ts",
        operation: "global-role-comparison",
        why: "the owner is never admin-linked — its SSO binding is the automatic owner-flip adoption, and choosing the owner's subject here would be box takeover. This is a TARGET-VALIDITY check on the owner ROW, not a caller-privilege gate: `can()` decides whether a principal may act, and it structurally cannot answer whether the row being acted on is the immutable bootstrap owner. The legacy text reader was blind to it because the literal is the `OWNER_ROLE` const rather than a quoted string.",
        endsWhen: "the admin guard exposes an owner-immutability decision the verbs call, instead of each verb comparing the global-role value itself.",
      },
      {
        id: "owner-role-split:admin-reset-password",
        policyId: "owner-role-split",
        subject: "packages/server/src/domain/admin/verbs/reset-password.ts",
        operation: "global-role-comparison",
        why: "the owner's credential is not admin-resettable; the verb refuses the owner ROW rather than the caller. This is a TARGET-VALIDITY check on the owner ROW, not a caller-privilege gate: `can()` decides whether a principal may act, and it structurally cannot answer whether the row being acted on is the immutable bootstrap owner. The legacy text reader was blind to it because the literal is the `OWNER_ROLE` const rather than a quoted string.",
        endsWhen: "the admin guard exposes an owner-immutability decision the verbs call, instead of each verb comparing the global-role value itself.",
      },
      {
        id: "owner-role-split:admin-set-enabled",
        policyId: "owner-role-split",
        subject: "packages/server/src/domain/admin/verbs/set-enabled.ts",
        operation: "global-role-comparison",
        why: "the owner row cannot be disabled — a disabled owner is a bricked box. This is a TARGET-VALIDITY check on the owner ROW, not a caller-privilege gate: `can()` decides whether a principal may act, and it structurally cannot answer whether the row being acted on is the immutable bootstrap owner. The legacy text reader was blind to it because the literal is the `OWNER_ROLE` const rather than a quoted string.",
        endsWhen: "the admin guard exposes an owner-immutability decision the verbs call, instead of each verb comparing the global-role value itself.",
      },
      {
        id: "owner-role-split:admin-set-role",
        policyId: "owner-role-split",
        subject: "packages/server/src/domain/admin/verbs/set-role.ts",
        operation: "global-role-comparison",
        why: "the owner cannot be demoted, and the no-op re-grant of owner-to-owner returns unchanged. This is a TARGET-VALIDITY check on the owner ROW, not a caller-privilege gate: `can()` decides whether a principal may act, and it structurally cannot answer whether the row being acted on is the immutable bootstrap owner. The legacy text reader was blind to it because the literal is the `OWNER_ROLE` const rather than a quoted string.",
        endsWhen: "the admin guard exposes an owner-immutability decision the verbs call, instead of each verb comparing the global-role value itself.",
      },
      {
        id: "persistence-boundary:durable-local",
        policyId: "persistence-boundary",
        subject: "packages/client/src/state/durable-local.ts",
        operation: "raw-storage:localStorage",
        why: "the two persist factories' SHARED half — the per-user durable-local namespace. Its only raw-storage touch is the last-bound-userId POINTER a cold boot mints store keys against; store blobs move through each store's own persist storage and never through this. Boot machinery, the same carve-out class as the composition root.",
        endsWhen:
          "key minting stops needing a pre-store pointer (the bound user is known before any store is created), which would make this read unnecessary.",
      },
      {
        id: "persistence-boundary:main-preload-guard",
        policyId: "persistence-boundary",
        subject: "packages/client/src/main.tsx",
        operation: "raw-storage:sessionStorage",
        why: "the composition root's `vite:preloadError` reload-once guard: a redeploy rotates hashed chunk names and an old tab that lazy-imports a stale hash white-screens, so the soft reload is guarded by a tab-scoped flag that stops a reload loop. Boot machinery, and it runs in a window listener before the app's stores exist.",
        endsWhen: "chunk-hash rotation stops white-screening an open tab (a service worker or a version handshake owns it), which retires the guard.",
      },
      {
        id: "persistence-boundary:probe-mode",
        policyId: "persistence-boundary",
        subject: "packages/client/src/lib/probe-mode.ts",
        operation: "raw-storage:localStorage",
        why: "the dev-only probe flag seeded by `pnpm snap --probe` BEFORE the app boots — deterministic-render instrumentation, not app state, and read once before React mounts. A store door cannot serve it because no store exists yet at that point.",
        endsWhen: "probe mode is delivered by something other than pre-boot storage (a query parameter or a build flag), at which point this read disappears.",
      },
      {
        id: "persistence-boundary:session-resume",
        policyId: "persistence-boundary",
        subject: "packages/client/src/data/session-resume.ts",
        operation: "raw-storage:sessionStorage",
        why: "the OIDC re-auth resume snapshot: TAB-scoped by requirement (a sibling tab must not inherit another tab's redirect round trip) and written across a full-document navigation, so it cannot ride a store door at all. Session machinery, not a device-local preference.",
        endsWhen: "the IdP round trip stops requiring a full-document navigation, so the resume target can live in memory.",
      },
      {
        id: "render-error-via-battery:persona-panel-surface",
        policyId: "render-error-via-battery",
        subject: "packages/client/src/features/persona/surfaces/persona-panel-surface.tsx",
        operation: "custom-render-error",
        why: "the persona avatar degrades to its own loading placeholder rather than a Couldn't-load card with a Retry: it is a decorative slot, not a read the user retries.",
        endsWhen: "the avatar becomes a retryable read, or the surface moves.",
      },
      {
        id: "render-error-via-battery:rpg-context-section",
        policyId: "render-error-via-battery",
        subject: "packages/client/src/features/rpg/lib/rpg-context-section.tsx",
        operation: "custom-render-error",
        why: "the rpg context pane needs a CONSOLIDATED, ANNOUNCED failure (Context-Panel-Program §4.4): the pane's live region reports 'Loaded chat.' on success, and `QueryErrorState` is a plain stack with no `role=\"alert\"`, so the game-tab body renders `RpgErrorState` — the pane's single announced region. One row covers both of this file's arms, because they are one licensed act at one subject.",
        endsWhen: "the pane drops its announced-failure intent, or `QueryErrorState` gains a live region the pane can use.",
      },
      {
        id: "render-error-via-battery:rpg-hud-band",
        policyId: "render-error-via-battery",
        subject: "packages/client/src/features/rpg/components/rpg-hud-band.tsx",
        operation: "custom-render-error",
        why: "the decorative HUD band collapses to `() => null` on a failed read so the pane has exactly ONE announced error surface (the body's) rather than two contradictory ones.",
        endsWhen: "the band becomes a retryable read of its own, or the pane stops owning a single announced failure.",
      },
      {
        id: "route-imports-no-feature:app-root-app-shell",
        policyId: "route-imports-no-feature",
        subject: "packages/client/src/routes/app-root.tsx",
        operation: "feature-front-door-import:#features/app-shell",
        why: "app-root.tsx is the ONE sanctioned composition route (client-architecture-lockdown.md §6): the shell it mounts is what OWNS the section/modal/chrome registries, so it cannot itself reach them through a registry that does not exist until it has mounted.",
        endsWhen: "the app shell is entered through a registry-assembled door rather than composed at the route.",
      },
      {
        id: "route-imports-no-feature:app-root-chat",
        policyId: "route-imports-no-feature",
        subject: "packages/client/src/routes/app-root.tsx",
        operation: "feature-front-door-import:#features/chat",
        why: "the sanctioned composition route assembles the chat feature's contributor registries at the door (client-architecture-lockdown.md §12 row 5); the assembly is the door's job by construction.",
        endsWhen: "chat's contributor registries are assembled by the shell from registered contributions instead of at the route.",
      },
      {
        id: "route-imports-no-feature:app-root-persona",
        policyId: "route-imports-no-feature",
        subject: "packages/client/src/routes/app-root.tsx",
        operation: "feature-front-door-import:#features/persona",
        why: "the sanctioned composition route assembles the persona feature's contributions at the door, on the same §12 row-5 ruling as chat.",
        endsWhen: "persona's contributions are assembled by the shell from registered contributions instead of at the route.",
      },
      {
        id: "route-imports-no-feature:login-page-auth",
        policyId: "route-imports-no-feature",
        subject: "packages/client/src/routes/login-page.tsx",
        operation: "feature-front-door-import:#features/auth",
        why: "the login page IS the auth surface: it renders before any authenticated shell exists, so there is no registry for it to ride.",
        endsWhen: "the login surface is reached through the authenticated shell's registries, which by definition it cannot be while it is the pre-auth entry.",
      },
      {
        id: "route-imports-no-feature:router-auth",
        policyId: "route-imports-no-feature",
        subject: "packages/client/src/routes/router.tsx",
        operation: "feature-front-door-import:#features/auth",
        why: "the router's beforeLoad gate must consult auth before it can decide which route tree to build, which is strictly earlier than any registry read.",
        endsWhen: "route admission is decided by a contracts-level session fact instead of by the auth feature's own door.",
      },
      {
        id: "scrubber-home:member-visibility-stamp",
        policyId: "scrubber-home",
        subject: "packages/server/src/domain/chat/substrate/member-visibility.ts",
        operation: "hidden-span-scrubber-construction",
        why: "THE producer stamp — the one place a stateful per-slot scrubber may be constructed (§3.6, ed2aafc5), because scrub state cannot survive a replay→live handoff and a cold scrubber mid-`<lie>` forwards the secret's tail.",
        endsWhen:
          "the producer stamp moves or stops constructing a scrubber; the row is then consumed zero times and reds, which is the legacy mode-A arm owned centrally.",
      },
      {
        id: "seed-theme-ink-contrast:meter-border",
        policyId: "seed-theme-ink-contrast",
        subject: "packages/ui/src/charts/meter/variants.ts",
        operation: "ink:border",
        why: "the gauge RAIL stroke (`track: text-border`, three species) — `--color-border` is a translucent LINE token that has no opaque colour to judge as text at all, and the rail is aria-hidden geometry under WCAG 1.4.11.",
        endsWhen: "a `track` slot typesets, or border stops being the rail's colour; either way this identity stops being reported and the row reds STALE.",
      },
      {
        id: "seed-theme-ink-contrast:meter-muted",
        policyId: "seed-theme-ink-contrast",
        subject: "packages/ui/src/charts/meter/variants.ts",
        operation: "ink:muted",
        why: "the UNFILLED segment (`filled:false -> segment: text-muted`) — a SURFACE token deliberately one ramp step from the panel, which is the whole point of an empty segment (its own header, #685/#693) and is 1.4.11 geometry, not text.",
        endsWhen: "a segment carries a label; the ink is then text duty, judged at 4.5:1, and this row licenses a finding whose reason no longer holds.",
      },
      {
        id: "seed-theme-ink-contrast:meter-track-1",
        policyId: "seed-theme-ink-contrast",
        subject: "packages/ui/src/charts/meter/variants.ts",
        operation: "ink:track-1",
        why: "`RING_STROKE` feeds `currentColor` to the RingGauge arc stroke on aria-hidden decorative geometry (its own header, #697) — WCAG 1.4.11's 3:1 applies, not 4.5:1 text, and palette-contrast.suite.test.ts already enforces that floor per seed.",
        endsWhen:
          "this kit typesets with a track token — the ink then stops being decorative geometry, the class is judged at 4.5:1, and this row licenses a finding whose reason no longer holds. A track slot that stops being painted at all consumes the row zero times and reds STALE.",
      },
      {
        id: "seed-theme-ink-contrast:meter-track-2",
        policyId: "seed-theme-ink-contrast",
        subject: "packages/ui/src/charts/meter/variants.ts",
        operation: "ink:track-2",
        why: "`RING_STROKE` feeds `currentColor` to the RingGauge arc stroke on aria-hidden decorative geometry (its own header, #697) — WCAG 1.4.11's 3:1 applies, not 4.5:1 text, and palette-contrast.suite.test.ts already enforces that floor per seed.",
        endsWhen:
          "this kit typesets with a track token — the ink then stops being decorative geometry, the class is judged at 4.5:1, and this row licenses a finding whose reason no longer holds. A track slot that stops being painted at all consumes the row zero times and reds STALE.",
      },
      {
        id: "seed-theme-ink-contrast:meter-track-3",
        policyId: "seed-theme-ink-contrast",
        subject: "packages/ui/src/charts/meter/variants.ts",
        operation: "ink:track-3",
        why: "`RING_STROKE` feeds `currentColor` to the RingGauge arc stroke on aria-hidden decorative geometry (its own header, #697) — WCAG 1.4.11's 3:1 applies, not 4.5:1 text, and palette-contrast.suite.test.ts already enforces that floor per seed.",
        endsWhen:
          "this kit typesets with a track token — the ink then stops being decorative geometry, the class is judged at 4.5:1, and this row licenses a finding whose reason no longer holds. A track slot that stops being painted at all consumes the row zero times and reds STALE.",
      },
      {
        id: "seed-theme-ink-contrast:meter-track-4",
        policyId: "seed-theme-ink-contrast",
        subject: "packages/ui/src/charts/meter/variants.ts",
        operation: "ink:track-4",
        why: "`RING_STROKE` feeds `currentColor` to the RingGauge arc stroke on aria-hidden decorative geometry (its own header, #697) — WCAG 1.4.11's 3:1 applies, not 4.5:1 text, and palette-contrast.suite.test.ts already enforces that floor per seed.",
        endsWhen:
          "this kit typesets with a track token — the ink then stops being decorative geometry, the class is judged at 4.5:1, and this row licenses a finding whose reason no longer holds. A track slot that stops being painted at all consumes the row zero times and reds STALE.",
      },
      {
        id: "seed-theme-ink-contrast:meter-track-5",
        policyId: "seed-theme-ink-contrast",
        subject: "packages/ui/src/charts/meter/variants.ts",
        operation: "ink:track-5",
        why: "`RING_STROKE` feeds `currentColor` to the RingGauge arc stroke on aria-hidden decorative geometry (its own header, #697) — WCAG 1.4.11's 3:1 applies, not 4.5:1 text, and palette-contrast.suite.test.ts already enforces that floor per seed.",
        endsWhen:
          "this kit typesets with a track token — the ink then stops being decorative geometry, the class is judged at 4.5:1, and this row licenses a finding whose reason no longer holds. A track slot that stops being painted at all consumes the row zero times and reds STALE.",
      },
      {
        id: "seed-theme-ink-contrast:meter-track-6",
        policyId: "seed-theme-ink-contrast",
        subject: "packages/ui/src/charts/meter/variants.ts",
        operation: "ink:track-6",
        why: "`RING_STROKE` feeds `currentColor` to the RingGauge arc stroke on aria-hidden decorative geometry (its own header, #697) — WCAG 1.4.11's 3:1 applies, not 4.5:1 text, and palette-contrast.suite.test.ts already enforces that floor per seed.",
        endsWhen:
          "this kit typesets with a track token — the ink then stops being decorative geometry, the class is judged at 4.5:1, and this row licenses a finding whose reason no longer holds. A track slot that stops being painted at all consumes the row zero times and reds STALE.",
      },
      {
        id: "seed-theme-ink-contrast:switch-readonly-glyph",
        policyId: "seed-theme-ink-contrast",
        subject: "packages/ui/src/primitives/switch/variants.ts",
        operation: "ink:background",
        why: "`readOnlyIcon` is the readonly LOCK GLYPH painted ON the switch thumb: `text-background` inverts against the thumb's own `bg-foreground` fill, measuring ~13:1 on the surface it actually sits on. An INVERTED pair ink — the `-foreground` suffix rule cannot see it because the inversion runs the other way (the INK is `background`) — and a glyph, judged at 1.4.11's 3:1.",
        endsWhen:
          "this slot paints a text run, or the thumb stops declaring its own fill; the grounds table then judges it correctly and the row is no longer needed.",
      },
      {
        id: "selection-store-via-factory:create-drill-selection-store",
        policyId: "selection-store-via-factory",
        subject: "packages/client/src/state/create-drill-selection-store.ts",
        operation: "raw-gated-store-mint",
        why: "the drill FACTORY itself composes the raw `createGatedStore` door on purpose — that composition IS the seal every per-section selection store mints through (derive-modernization-audit.md §W3 G27).",
        endsWhen:
          "the factory stops composing the door, or moves — either stales this row, where the legacy `/create-` FILENAME pattern would have exempted any future file with that prefix for free.",
      },
      {
        id: "selection-store-via-factory:create-kinded-selection-store",
        policyId: "selection-store-via-factory",
        subject: "packages/client/src/state/create-kinded-selection-store.ts",
        operation: "raw-gated-store-mint",
        why: "the kinded-selection factory, the same composition one shape over, named as its OWN row so a THIRD factory is judged rather than auto-exempt.",
        endsWhen: "the kinded factory stops composing the door, or moves.",
      },
      {
        id: "selection-store-via-factory:message-selection-store",
        policyId: "selection-store-via-factory",
        subject: "packages/client/src/state/message-selection-store.ts",
        operation: "raw-gated-store-mint",
        why: "the ONE `*-selection-store.ts` that is not a single-id drill: message selection is a bulk multi-select (presence in a Set keyed by message id, PD-119), a shape the drill factory does not model.",
        endsWhen: "the drill factory models bulk selection and this store migrates onto it.",
      },

];
