// Reviewed grants: tooling-argv-front-door, tooling-artifact-path-home, tooling-browser-door, tooling-child-process-door, tooling-port-registry....
// Split from reviewed-grants.ts — see that file for the central home comment.
import type { ReviewedGateGrant } from "../contract/gate-authority.ts";

export const REVIEWED_GRANTS_TOOLING_TO_PERMISSION: readonly ReviewedGateGrant[] = [
  {
    id: "tooling-argv-front-door:shared-entrypoint",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/_shared/entrypoint.ts",
    operation: "process-argv-read",
    why: "reads argv[1] — the ENTRY IDENTITY ('was this module the program?'), never the operator's flags; it is the one home for that question (Core-Tooling-Law §4.9).",
    endsWhen: "the direct-invocation refusal moves or stops asking it — the row is then consumed zero times and reds at its dead subject.",
  },
  {
    id: "tooling-argv-front-door:stack-dev-identity-entry",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/stack/ops/dev-identity-entry.ts",
    operation: "process-argv-read",
    why: "the node half stack.sh execs for the dev-identity verbs — a BASH_FRONTED_TOOLS tool has no cli.ts (Core-Tooling-Law §2.5/§4.1), so the node half it execs is the argv front door itself.",
    endsWhen: "stack grows a cli.ts or this entry is retired — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-argv-front-door:stack-engines",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/stack/ops/engines.ts",
    operation: "process-argv-read",
    why: "the node half engines.sh setsid-execs to boot the fleet (`--detach`) — the same bash-fronted exception (Core-Tooling-Law §2.5).",
    endsWhen: "the launcher moves behind a cli.ts — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-argv-front-door:stack-engines-ctl",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/stack/ops/engines-ctl.ts",
    operation: "process-argv-read",
    why: "the node half engines.sh execs for status/stop/sleep/wake/reconcile — the same bash-fronted exception (Core-Tooling-Law §2.5).",
    endsWhen: "the fleet front door stops being bash — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-argv-front-door:stack-prod-entry",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/stack/ops/prod-entry.ts",
    operation: "process-argv-read",
    why: "the node half stack.sh execs for every PROD invocation — the same bash-fronted exception (Core-Tooling-Law §2.5).",
    endsWhen: "stack grows a cli.ts or this entry is retired — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-argv-front-door:stack-start-entry",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/stack/ops/start-entry.ts",
    operation: "process-argv-read",
    why: "the node half the root `start` pnpm script runs for `pnpm start` — stack is bash-fronted and owns no cli.ts (Core-Tooling-Law §2.5/§4.1), and this entry deliberately has NO .sh in front of it: it is the one launcher a macOS or Windows operator can run at all.",
    endsWhen: "stack grows a cli.ts or `pnpm start` is retired — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-argv-front-door:verify-config-snapshot-entry",
    policyId: "tooling-argv-front-door",
    subject: "tooling/src/verify/ops/config-snapshot-entry.ts",
    operation: "process-argv-read",
    why: "the private process boundary reads native config snapshots and ESLint's discovery-only filename list without eagerly importing the whole verify CLI; its argv is a parent-authored request validated by those operations, never a second operator door (#1351).",
    endsWhen: "both observations move in-process or behind a different worker — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-artifact-path-home:artifacts",
    policyId: "tooling-artifact-path-home",
    subject: "tooling/src/_shared/artifacts.ts",
    operation: "reports-path-literal",
    why: "THE artifact root home: `reportsPath`/`reportsRelPath`/`ensureReportsDir` are the one spelling of `reports/…` in the repo, and the run-slot layout (#1029/#1164) is built on them (Core-Tooling-Law.md §4.4, arm C of the retired plumbing gate).",
    endsWhen:
      "the artifact root moves out of artifacts.ts — the row is then consumed zero times and reds at its dead subject, which is the legacy HOMES stale sweep.",
  },
  {
    id: "tooling-browser-door:browser-attach",
    policyId: "tooling-browser-door",
    subject: "tooling/src/_shared/browser.ts",
    operation: "browser-attach",
    why: "`attachProbeSession` IS the one door onto a stateful session daemon's browser (docs/design/1208-instrument-substrate.md §3.4): the `connectOverCDP` here is the attach every consumer rides, shape-identical to a launched session (arm H of the retired plumbing gate).",
    endsWhen: "the attach moves out of browser.ts or the daemon stops exposing a debugging endpoint — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-browser-door:browser-launch",
    policyId: "tooling-browser-door",
    subject: "tooling/src/_shared/browser.ts",
    operation: "browser-launch",
    why: "`launchProbeSession` IS the one Playwright bootstrap: the `chromium.launch` here carries the marked args/env and the run-marker every instrument's browser must wear (arm B of the retired plumbing gate).",
    endsWhen: "the launch moves out of browser.ts — the row is then consumed zero times and reds at its dead subject.",
  },
  {
    id: "tooling-child-process-door:proc",
    policyId: "tooling-child-process-door",
    subject: "tooling/src/_shared/proc.ts",
    operation: "child-process-import",
    why: "THE subprocess home: proc.ts is where `node:child_process` is imported so every tooling spawn rides the nice -19 homelab floor (`spawnNiced`/`runNicedSync`/`spawnNicedChild`); the two full-priority doors are defined here too (arm F of the retired plumbing gate).",
    endsWhen: "the subprocess home moves — the row is then consumed zero times and reds at its dead subject, which is the legacy HOMES stale sweep.",
  },
  {
    id: "tooling-child-process-door:snap-session-client",
    policyId: "tooling-child-process-door",
    subject: "tooling/src/snap/ops/session-client.ts",
    operation: "full-priority-spawn",
    why: "the session daemon owns the interactive Chromium a human drives across calls — nice 19 silently changes motion/performance evidence (the legacy FULL_PRIORITY_CALLERS row, carried verbatim).",
    endsWhen: "the daemon stops hosting the interactive browser or its spawn moves — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-child-process-door:snap-stage",
    policyId: "tooling-child-process-door",
    subject: "tooling/src/snap/ops/stage.ts",
    operation: "full-priority-spawn",
    why: "the stage stack BOOT serves interactive snap navigations — a -19 staged app times out captures under load (the legacy FULL_PRIORITY_CALLERS row, carried verbatim).",
    endsWhen: "the stage boot moves or drops the exception — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-child-process-door:stack-engines",
    policyId: "tooling-child-process-door",
    subject: "tooling/src/stack/ops/engines.ts",
    operation: "full-priority-spawn",
    why: "the vLLM engines ARE the inference workload the operator waits on — a -19 engine degrades the interactive token latency the fleet exists to provide (the legacy FULL_PRIORITY_CALLERS row, carried verbatim).",
    endsWhen: "the fleet launcher moves or stops spawning — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-child-process-door:stack-start",
    policyId: "tooling-child-process-door",
    subject: "tooling/src/stack/ops/start.ts",
    operation: "full-priority-spawn",
    why: "`pnpm start`, the portable one-command launcher: the child it spawns IS the production server answering the operator's requests (the prod-up row's reason, on the cross-platform path), and the niced doors are structurally unavailable to it — they exec the POSIX `nice` binary, which does not exist on Windows.",
    endsWhen: "`pnpm start` is retired, or stops spawning the server and its client build — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-child-process-door:stack-prod-up",
    policyId: "tooling-child-process-door",
    subject: "tooling/src/stack/ops/prod-up.ts",
    operation: "full-priority-spawn",
    why: "the child it spawns IS the production server answering the operator's requests — a -19 app is the thing the launcher exists to run, degraded (the legacy FULL_PRIORITY_CALLERS row, carried verbatim).",
    endsWhen: "the prod spawn moves or drops the exception — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-port-registry:ports",
    policyId: "tooling-port-registry",
    subject: "tooling/src/_shared/ports.ts",
    operation: "port-literal",
    why: "THE port registry — the one home every reserved row and stage band is declared in, and the table the policy imports to know what a port number even is (the legacy PORT_HOME row; docs/design/1208-instrument-substrate.md §3.6).",
    endsWhen: "the registry moves, or stops declaring ports — which is the day it stopped being the registry; the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-process-exit-home:run-tool",
    policyId: "tooling-process-exit-home",
    subject: "tooling/src/_shared/run-tool.ts",
    operation: "process-exit",
    why: "THE exit-honesty runner: the crash path's hard exit lives here and nowhere else — every verdict path sets `process.exitCode` and lets the loop drain (arm D of the retired plumbing gate).",
    endsWhen: "the runner's hard exit moves — the row is then consumed zero times and reds at its dead subject, which is the legacy HOMES stale sweep.",
  },
  {
    id: "tooling-project-home:baseui-read",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/lib/baseui-read.ts",
    operation: "ts-morph-project-construction",
    why: "loads the INSTALLED @base-ui/react `.d.ts` surface out of packages/ui/node_modules — not workspace source, not in harnessGlobs, and unreadable any other way, so the manifest would have nothing to adjudicate against (the legacy PROJECT_SITES row, carried verbatim).",
    endsWhen: "the surface is ever vendored INTO the workspace — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:comment-spans",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/lib/comment-spans.ts",
    operation: "ts-morph-project-construction",
    why: "an in-memory SCRATCH parser (`useInMemoryFileSystem`) for ONE string of text read off real disk — it resolves no dependency and walks no workspace; it exists so a `//` inside a string literal is still not a comment (the legacy PROJECT_SITES row; three constructions, one grant).",
    endsWhen: "comment blanking ever reads from the shared project instead of raw text — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:config-static-read",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/lib/config-static-read.ts",
    operation: "ts-morph-project-construction",
    why: "ONE scratch parser (`useInMemoryFileSystem`) for exact code outside the governed workspace corpus: the root eslint/dep-cruiser configs, Playwright's CT bootstrap, and now the three root runner configs delivered as `exact-file` facts. Loading them into harnessGlobs would widen every gate's jurisdiction; separate parsers per consumer would violate the one-parser census (the legacy PROJECT_SITES row).",
    endsWhen: "every such file joins the governed corpus or stops needing AST reads — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:ops-policy-conformance",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/ops/policy-conformance.ts",
    operation: "ts-morph-project-construction",
    why: "materializes each FINAL policy's proof as its own mini-project (a virtual project for source/types rows, a real temp dir plus an in-memory parser for resource rows) and hosts the shared scratch parser the twin rewriter reads — three constructions the legacy census never listed, RED on the live tree under the legacy gate itself and licensed here for what they load (#1950 group 4; the module belongs to another lane and is not edited).",
    endsWhen:
      "policy conformance stops being example-driven, or its parsers fold onto `lib/config-static-read.ts`'s scratch — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:spelling-twins",
    policyId: "tooling-project-home",
    subject: "tooling/src/verify/lib/spelling-twins.ts",
    operation: "ts-morph-project-construction",
    why: "an in-memory SCRATCH parser (`useInMemoryFileSystem`) that parses each gate's mustFlag fixture STRING at its OWN virtual path to emit its bracket/namespace twins (#1506) — resolves no dependency, walks no workspace, and cannot ride comment-spans' door (that one reuses a single overwritten SourceFile; the namespace twin walks references and needs the fixture's own extension) (the legacy PROJECT_SITES row).",
    endsWhen: "the twin rewriter becomes purely textual or moves onto conformance's per-example mini-project — the row is then consumed zero times and reds.",
  },
  {
    id: "tooling-project-home:ts-workspace",
    policyId: "tooling-project-home",
    subject: "tooling/src/_shared/ts-workspace.ts",
    operation: "ts-morph-project-construction",
    why: "THE ts-morph loader (`getWorkspace`): the one home the shared workspace is loaded from, once, so every gate walks one project (Core-Tooling-Law.md §2.4/§4.4, arm A of the retired plumbing gate).",
    endsWhen: "the loader moves — the row is then consumed zero times and reds at its dead subject, which is the legacy HOMES stale sweep.",
  },
  {
    id: "tooling-root-config-import:prodonly-knip",
    policyId: "tooling-root-config-import",
    subject: "tooling/src/ast/ops/prodonly.ts",
    operation: "root-config-import:knip.ts",
    why: "ast/ops/prodonly derives its entry closure from the ONE knip workspace-entry config — re-spelling the globs is the one-home violation the front-door law exists to kill (P4 of #393, Core-Tooling-Law §4.2).",
    endsWhen:
      "prodonly stops deriving its closure from knip.ts, or knip's entry config moves — the row is then consumed zero times and reds at its dead subject, which is the two-sided stale sweep the legacy ROOT_CONFIG_IMPORTS table carried by hand.",
  },
  {
    id: "tsconfig-entry-liveness:node-modules",
    policyId: "tsconfig-entry-liveness",
    subject: "**/node_modules",
    operation: "tsconfig-glob-entry",
    why: "INSTALLED DEPENDENCIES: node_modules is gitignored (.gitignore), so it is absent from the tracked corpus by design and present only after an install — judging it either way would make the verdict depend on machine state, which is the whole reason this family reads `git ls-files` rather than the filesystem.",
    endsWhen: "the type programs stop needing to exclude installed packages.",
  },
  {
    id: "tsconfig-entry-liveness:scripts-cts",
    policyId: "tsconfig-entry-liveness",
    subject: "scripts/**/*.cts",
    operation: "tsconfig-glob-entry",
    why: "the Node world root declares EVERY authored TypeScript dialect before its first `scripts` .cts file, so a future authored file cannot be silently unowned by any program (docs/architecture/core/Core-Tooling-Law.md).",
    endsWhen: "the first scripts/**/*.cts source lands — the glob acquires a member, the finding disappears and this row is consumed zero times.",
  },
  {
    id: "tsconfig-entry-liveness:scripts-mts",
    policyId: "tsconfig-entry-liveness",
    subject: "scripts/**/*.mts",
    operation: "tsconfig-glob-entry",
    why: "the same pre-declaration, for the `.mts` dialect: the Node world root owns every authored dialect under scripts/ before the first file of that dialect exists (docs/architecture/core/Core-Tooling-Law.md).",
    endsWhen: "the first scripts/**/*.mts source lands.",
  },
  {
    id: "tsconfig-entry-liveness:scripts-tsx",
    policyId: "tsconfig-entry-liveness",
    subject: "scripts/**/*.tsx",
    operation: "tsconfig-glob-entry",
    why: "the BROWSER world root declares TSX scripts before its first member so a future authored file cannot be silently unowned — the DOM half of the same pre-declaration (docs/architecture/core/Core-Tooling-Law.md).",
    endsWhen: "the first scripts/**/*.tsx source lands.",
  },
  {
    id: "tsconfig-entry-liveness:st-goldens-runtime",
    policyId: "tsconfig-entry-liveness",
    subject: "scripts/probes/st-goldens/sillytavern-runtime",
    operation: "tsconfig-exact-entry",
    why: "not a dead entry — a GITIGNORED captured SillyTavern install, absent on a clean checkout by design. The root aggregator EXCLUDES it so its four root .d.ts files, which declare ST's browser globals into our global scope, never join the program. Evidence: scripts/probes/st-goldens/README.md.",
    endsWhen:
      "scripts/probes/st-goldens stops shipping a gitignored runtime subtree — the exclude then names nothing anybody would create and leaves the config.",
  },
  {
    id: "tsconfig-entry-liveness:tests-cts",
    policyId: "tsconfig-entry-liveness",
    subject: "tests/**/*.cts",
    operation: "tsconfig-glob-entry",
    why: "the Node world root's dialect pre-declaration for the test tree, identical in kind to its scripts siblings (docs/architecture/core/Core-Tooling-Law.md).",
    endsWhen: "the first tests/**/*.cts source lands.",
  },
  {
    id: "two-class-role-authority:admin-guard-can-seam",
    policyId: "two-class-role-authority",
    subject: "packages/server/src/domain/admin/guard.ts",
    operation: "enforcement-role-comparison",
    why: "the `can()` seam itself — spine invariant #6: the chat resource-role verdict is DECIDED here and nowhere else, so the comparison must be spelled here exactly once.",
    endsWhen:
      "the kernel stops comparing the participant role directly (a resource-role table replaces the switch); the row is then consumed zero times and reds.",
  },
  {
    id: "two-class-role-authority:chat-nominee-target",
    policyId: "two-class-role-authority",
    subject: "packages/server/src/domain/chat/verbs/participants.ts",
    operation: "enforcement-role-comparison",
    why: "the host compare is on the NOMINEE (`nominee.role === 'host'` → ChatNotFound) — a TARGET-VALIDITY check on the handoff candidate, not the caller's privilege; the caller's gate is the `requireHost` on the line above it.",
    endsWhen: "target validity moves behind a chokepoint helper that owns the leak-free refusal for a nominee as well as for a caller.",
  },
  {
    id: "two-class-role-authority:chat-participant-shape",
    policyId: "two-class-role-authority",
    subject: "packages/server/src/domain/chat/persistence/participant.ts",
    operation: "enforcement-role-comparison",
    why: "`assertForcedCharacterMember` is the runtime twin of the `chat_participants` CHECK constraint — a persisted-row SHAPE invariant (a character seat can never be the host), not a caller-privilege gate. The legacy reader was blind to it because it hardcoded the `host` literal and this assertion names `member`.",
    endsWhen: "the row shape is guaranteed by the schema alone at every write path, so the runtime twin can be deleted.",
  },
  {
    id: "ui-primitive-permissions:colors-color-field",
    policyId: "ui-primitive-permissions",
    subject: "tests/ui/primitives/color-field/color-field.ct.tsx",
    operation: "test-color-values",
    why: "This component test exercises caller-supplied and hostile color values as data; replacing them with design tokens would remove the color-input boundary proof.",
    endsWhen: "the subject is removed or satisfies this obligation without the exception; zero consumption makes this grant stale.",
  },
  {
    id: "ui-primitive-permissions:colors-sandbox-frame",
    policyId: "ui-primitive-permissions",
    subject: "tests/ui/content/sandbox-frame/sandbox-frame.ct.tsx",
    operation: "test-color-values",
    why: "This component test exercises caller-supplied and hostile color values as data; replacing them with design tokens would remove the color-input boundary proof.",
    endsWhen: "the subject is removed or satisfies this obligation without the exception; zero consumption makes this grant stale.",
  },
  {
    id: "ui-primitive-permissions:colors-theme-scope",
    policyId: "ui-primitive-permissions",
    subject: "tests/ui/content/theme-scope/theme-scope.ct.tsx",
    operation: "test-color-values",
    why: "This component test exercises caller-supplied and hostile color values as data; replacing them with design tokens would remove the color-input boundary proof.",
    endsWhen: "the subject is removed or satisfies this obligation without the exception; zero consumption makes this grant stale.",
  },

  {
    id: "ui-primitive-permissions:ct-icons",
    policyId: "ui-primitive-permissions",
    subject: "packages/ui/src/primitives/icons",
    operation: "primitive-ct",
    why: "The legacy UI primitive contract exempts this nonvisual satellite from the styled-primitive co-located CT obligation.",
    endsWhen: "the subject is removed or satisfies this obligation without the exception; zero consumption makes this grant stale.",
  },
  {
    id: "ui-primitive-permissions:provider-drawerprovider",
    policyId: "ui-primitive-permissions",
    subject: "DrawerProvider",
    operation: "inline-test-provider",
    why: "Drawer-local provider behavior is the subject of these component tests; it cannot be replaced by the global CtProviders shell.",
    endsWhen: "the subject is removed or satisfies this obligation without the exception; zero consumption makes this grant stale.",
  },
  {
    id: "ui-primitive-permissions:provider-drawervirtualkeyboardprovider",
    policyId: "ui-primitive-permissions",
    subject: "DrawerVirtualKeyboardProvider",
    operation: "inline-test-provider",
    why: "Drawer-local provider behavior is the subject of these component tests; it cannot be replaced by the global CtProviders shell.",
    endsWhen: "the subject is removed or satisfies this obligation without the exception; zero consumption makes this grant stale.",
  },
  {
    id: "ui-primitive-permissions:shape-aria-announcer",
    policyId: "ui-primitive-permissions",
    subject: "packages/ui/src/primitives/aria-announcer",
    operation: "primitive-shape",
    why: "The headless announcer owns accessibility behavior without visual styling.",
    endsWhen: "the subject is removed or satisfies this obligation without the exception; zero consumption makes this grant stale.",
  },
  {
    id: "ui-primitive-permissions:shape-file-trigger",
    policyId: "ui-primitive-permissions",
    subject: "packages/ui/src/primitives/file-trigger",
    operation: "primitive-shape",
    why: "The headless file trigger delegates its rendered trigger and styling to the caller.",
    endsWhen: "the subject is removed or satisfies this obligation without the exception; zero consumption makes this grant stale.",
  },
  {
    id: "ui-primitive-permissions:shape-icons",
    policyId: "ui-primitive-permissions",
    subject: "packages/ui/src/primitives/icons",
    operation: "primitive-shape",
    why: "The lucide export barrel has no styled primitive body.",
    endsWhen: "the subject is removed or satisfies this obligation without the exception; zero consumption makes this grant stale.",
  },
  {
    id: "ui-primitive-permissions:shape-message-list",
    policyId: "ui-primitive-permissions",
    subject: "packages/ui/src/primitives/message-list",
    operation: "primitive-shape",
    why: "The virtual message wrapper delegates row styling to the caller renderItem.",
    endsWhen: "the subject is removed or satisfies this obligation without the exception; zero consumption makes this grant stale.",
  },
  {
    id: "ui-primitive-permissions:shape-virtual-list",
    policyId: "ui-primitive-permissions",
    subject: "packages/ui/src/primitives/virtual-list",
    operation: "primitive-shape",
    why: "The virtual wrapper delegates row styling to the caller renderItem.",
    endsWhen: "the subject is removed or satisfies this obligation without the exception; zero consumption makes this grant stale.",
  },
  {
    id: "wire-schema-vocab-one-home:inverse-lift",
    policyId: "wire-schema-vocab-one-home",
    subject: "packages/kit/src/json-schema/lift.ts",
    operation: "wire-schema-vocabulary-home",
    why: "lift.ts is the inverse reader paired with the canonical wire-subset scrub engine in D93 and must recognize the same keyword vocabulary.",
    endsWhen: "the inverse lift delegates to the engine vocabulary without spelling a table, or the inverse reader is removed.",
  },
];
