/**
 * `@orb/ui/icons` — the ONE icon home (gate icons-lucide-only; UI-Arch §2). A curated lucide-react
 * re-export for the shell + primitives, plus the `<Icon>` sizing wrapper. Grow the set per
 * consumer chunk — never import `lucide-react` outside this dir (dep-cruiser ui-satellite-seals).
 */

export type { LucideIcon } from "lucide-react";
export {
  AlertTriangle,
  Anchor,
  Archive,
  ArrowLeft,
  Bell,
  BookOpen,
  BrainCircuit,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  CircleAlert,
  CircleUser,
  Clock,
  Coins,
  Command,
  Copy,
  Cpu,
  Crown,
  Download,
  Drama,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  FlaskConical,
  Gauge,
  GitFork,
  GripVertical,
  Hash,
  Heart,
  History,
  ImageOff,
  ImagePlus,
  Images,
  Info,
  KeyRound,
  Library,
  Loader2,
  Lock,
  LogOut,
  MessagesSquare,
  Minus,
  MonitorSmartphone,
  MoreHorizontal,
  MoreVertical,
  MoveHorizontal,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Pause,
  Pencil,
  Play,
  Plus,
  Redo2,
  RotateCcw,
  Search,
  Send,
  Settings,
  Shrink,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  SunMoon,
  Trash2,
  Undo2,
  Unlock,
  Upload,
  UserPlus,
  Users,
  UserX,
  Volume2,
  VolumeX,
  WandSparkles,
  X,
  Zap,
} from "lucide-react";
export type { IconProps } from "./icon";
export { ICON_LG, ICON_MD, ICON_SM, ICON_XS, Icon } from "./icon";
