// Unit: the generation credit's sentence (features/chat/lib/swipe-attribution). Every connection state the
// persisted swipe record can carry: one of the viewer's rows, a row outside the viewer's list, a null id read
// through its provenance (deleted when recorded, not recorded otherwise), a failed lookup and a pending lookup.

import type { UserConnectionId } from "@orb/kit/ids";
import { castId } from "@orb/kit/ids";
import { modelDisplayName } from "@orb/kit/model-name";
import type { CreditConnections } from "../../../../../packages/client/src/features/chat/lib/swipe-attribution.ts";
import { generationCreditSentence, providerName } from "../../../../../packages/client/src/features/chat/lib/swipe-attribution.ts";
import { expect, test } from "../../../../support/fixtures.ts";
import { testModelId, testProviderId } from "../../../../support/inference-identities.ts";

const MODEL = testModelId("anthropic/claude-sonnet-5");
const ANTHROPIC = testProviderId("anthropic");
const MINE = castId<UserConnectionId>("user_connection_unitcredit01");
const THEIRS = castId<UserConnectionId>("user_connection_unitcredit02");
const LOADED: CreditConnections = { rows: [{ id: MINE, label: "Work key", providerLabel: "Anthropic (work)", tasks: ["chat"] }], failed: false };
const LEAD_ROW = `Generated by ${modelDisplayName(MODEL)} via Anthropic (work).`;
const LEAD_REGISTRY = `Generated by ${modelDisplayName(MODEL)} via Anthropic.`;

test("the viewer's own row names the connection, and its provider label wins over the registry's", () => {
  expect(generationCreditSentence({ model: MODEL, provider: ANTHROPIC, connectionId: MINE, connectionAttributionProvenance: "recorded" }, LOADED)).toBe(
    `${LEAD_ROW} Connection: Work key.`,
  );
});

test("a recorded id outside a loaded list says it is not in the viewer's list", () => {
  expect(generationCreditSentence({ model: MODEL, provider: ANTHROPIC, connectionId: THEIRS, connectionAttributionProvenance: "recorded" }, LOADED)).toBe(
    `${LEAD_REGISTRY} Connection: not in your list.`,
  );
});

test("a null id reads through its provenance: recorded means deleted, unrecorded means never recorded", () => {
  expect(generationCreditSentence({ model: MODEL, provider: ANTHROPIC, connectionId: null, connectionAttributionProvenance: "recorded" }, LOADED)).toBe(
    `${LEAD_REGISTRY} Connection: deleted.`,
  );
  expect(generationCreditSentence({ model: MODEL, provider: ANTHROPIC, connectionId: null, connectionAttributionProvenance: "unrecorded" }, LOADED)).toBe(
    `${LEAD_REGISTRY} Connection: not recorded.`,
  );
});

test("a failed lookup and a pending lookup are distinct: one says so, the other waits", () => {
  const record = { model: MODEL, provider: ANTHROPIC, connectionId: MINE, connectionAttributionProvenance: "recorded" as const };
  expect(generationCreditSentence(record, { rows: undefined, failed: true })).toBe(`${LEAD_REGISTRY} Connection: couldn't be looked up.`);
  expect(generationCreditSentence(record, { rows: undefined, failed: false })).toBe(LEAD_REGISTRY);
});

test("no recorded model means no generation to credit", () => {
  expect(generationCreditSentence({ model: null, provider: ANTHROPIC, connectionId: MINE, connectionAttributionProvenance: "recorded" }, LOADED)).toBeNull();
});

test("a provider the client has no registry row for still names itself by id", () => {
  expect(providerName("plugin:acme/relay", undefined)).toBe("plugin:acme/relay");
});
