// CT: the generation credit in a message's reveal cluster (generation-credit.tsx). Each assistant swipe names
// the model, provider and connection from its persisted record; the connection is resolved against the
// VIEWER's own list, so a row outside it (the host's, in a shared room) is named as such, and a swipe whose
// connection id is null (a deleted connection or an import) says it was deleted or never recorded. The #167
// posture holds: the glyph is the only rendering and the sentence lives on `title` and in sr-only text.

import type { MessageView } from "@orb/contracts/chat";
import type { UserConnectionId } from "@orb/kit/ids";
import { castId } from "@orb/kit/ids";
import { modelDisplayName } from "@orb/kit/model-name";
import { expect, test } from "@playwright/experimental-ct-react";
import type { Locator } from "@playwright/test";
import { testModelId, testProviderId } from "../../../../support/inference-identities.ts";
import type { TrpcFixtureOutput } from "../../../../support/node/route-trpc.ts";
import { routeTrpc, trpcError } from "../../../../support/node/route-trpc.ts";
import { MessageActionsRowStory } from "../_ct-stories.tsx";
import { CHAT_AMBIENT_ROUTES, CHAT_ROOM_ROUTES, makeMessageView } from "../fixtures.ts";

const CREDIT = '[data-slot="message-metadata-model"]';
const MODEL = "anthropic/claude-sonnet-5";
const LEAD = `Generated by ${modelDisplayName(MODEL)} via Anthropic.`;
const WORK_KEY_ID = castId<UserConnectionId>("user_connection_ctcredit0001");
const HOST_KEY_ID = castId<UserConnectionId>("user_connection_ctcredit0002");

const WORK_KEY = {
  id: WORK_KEY_ID,
  label: "Work key",
  providerId: "anthropic",
  providerLabel: "Anthropic",
  model: MODEL,
  tasks: ["chat"],
} satisfies TrpcFixtureOutput<"connection.list">[number];

function generated(overrides: Partial<MessageView> = {}): MessageView {
  return makeMessageView({ role: "assistant", model: testModelId(MODEL), provider: testProviderId("anthropic"), connectionId: WORK_KEY_ID, ...overrides });
}

function credit(component: Locator): Locator {
  return component.locator(CREDIT);
}

/** The credit's text with the sr-only sentence removed: the glyph is the only rest rendering (#167). */
async function restText(target: Locator): Promise<string> {
  return await target.evaluate((el) => {
    const clone = el.cloneNode(true) as HTMLElement;
    for (const node of clone.querySelectorAll(".sr-only")) {
      node.remove();
    }
    return (clone.textContent ?? "").trim();
  });
}

test("a swipe on one of the viewer's connections names the model, provider and connection", async ({ mount, page }) => {
  await routeTrpc(page, { ...CHAT_AMBIENT_ROUTES, ...CHAT_ROOM_ROUTES, "connection.list": [WORK_KEY] });
  const component = await mount(<MessageActionsRowStory message={generated()} generationCredit={true} />);

  const sentence = `${LEAD} Connection: Work key.`;
  await expect(credit(component)).toHaveAttribute("title", sentence);
  await expect(credit(component)).toHaveText(sentence);
  await expect.poll(async () => restText(credit(component))).toBe("");
});

test("a swipe on a connection outside the viewer's list (the host's, in a shared room) says so", async ({ mount, page }) => {
  await routeTrpc(page, { ...CHAT_AMBIENT_ROUTES, ...CHAT_ROOM_ROUTES, "connection.list": [WORK_KEY] });
  const component = await mount(<MessageActionsRowStory message={generated({ connectionId: HOST_KEY_ID })} generationCredit={true} />);

  await expect(credit(component)).toHaveAttribute("title", `${LEAD} Connection: not in your list.`);
});

test("a swipe whose connection was deleted (or never recorded) says exactly that, and keeps its model and provider", async ({ mount, page }) => {
  await routeTrpc(page, { ...CHAT_AMBIENT_ROUTES, ...CHAT_ROOM_ROUTES, "connection.list": [WORK_KEY] });
  const component = await mount(<MessageActionsRowStory message={generated({ connectionId: null })} generationCredit={true} />);

  await expect(credit(component)).toHaveAttribute("title", `${LEAD} Connection: deleted or never recorded.`);
});

test("a failed connection lookup is named as a failed lookup, never as a missing connection", async ({ mount, page }) => {
  await routeTrpc(page, { ...CHAT_AMBIENT_ROUTES, ...CHAT_ROOM_ROUTES, "connection.list": trpcError({ message: "boom" }) });
  const component = await mount(<MessageActionsRowStory message={generated()} generationCredit={true} />);

  await expect(credit(component)).toHaveAttribute("title", `${LEAD} Connection: couldn't be looked up.`);
});

test("a swipe with no recorded provider credits the model and connection alone", async ({ mount, page }) => {
  await routeTrpc(page, { ...CHAT_AMBIENT_ROUTES, ...CHAT_ROOM_ROUTES, "connection.list": [WORK_KEY] });
  const component = await mount(<MessageActionsRowStory message={generated({ provider: null })} generationCredit={true} />);

  await expect(credit(component)).toHaveAttribute("title", `Generated by ${modelDisplayName(MODEL)}. Connection: Work key.`);
});

test("a swipe with no recorded model (a greeting or draft) credits nothing, even with the toggle on", async ({ mount, page }) => {
  await routeTrpc(page, { ...CHAT_AMBIENT_ROUTES, ...CHAT_ROOM_ROUTES, "connection.list": [WORK_KEY] });
  const component = await mount(<MessageActionsRowStory message={generated({ model: null, provider: null, connectionId: null })} generationCredit={true} />);

  await expect(component.locator('[data-slot="message-actions-row"]')).toBeAttached();
  await expect(credit(component)).toHaveCount(0);
});

test("the toggle off shows no credit and never reads the connection list", async ({ mount, page }) => {
  const trpc = await routeTrpc(page, { ...CHAT_AMBIENT_ROUTES, ...CHAT_ROOM_ROUTES, "connection.list": [WORK_KEY] });
  const component = await mount(<MessageActionsRowStory message={generated()} />);

  await expect(component.locator('[data-slot="message-actions-row"]')).toBeAttached();
  await expect(credit(component)).toHaveCount(0);
  await expect.poll(() => trpc.count("connection.list")).toBe(0);
});

for (const viewport of [
  { name: "desktop", width: 1280, height: 800 },
  { name: "narrow", width: 900, height: 800 },
  { name: "mobile", width: 390, height: 844 },
] as const) {
  test(`${viewport.name}: the revealed credit is a glyph inside the viewport, with its sentence on hover`, async ({ mount, page }) => {
    await page.setViewportSize({ width: viewport.width, height: viewport.height });
    await routeTrpc(page, { ...CHAT_AMBIENT_ROUTES, ...CHAT_ROOM_ROUTES, "connection.list": [WORK_KEY] });
    const component = await mount(<MessageActionsRowStory message={generated()} generationCredit={true} />);
    const target = credit(component);
    await expect(target).toHaveAttribute("title", `${LEAD} Connection: Work key.`);
    await component.locator('[data-slot="message-actions-row"]').evaluate((el: HTMLElement) => {
      el.style.opacity = "1";
    });
    await expect(target).toBeVisible();
    await expect(target).toBeInViewport({ ratio: 1 });
    await expect.poll(async () => restText(target)).toBe("");
  });
}
