// The USAGE block — the doc `pnpm ast` prints bare.

import { DEPCRUISE_VERBS } from "../ops/depcruise.ts";
import { VERBS } from "../ops/verbs.ts";
import { CORPUS_SYNTACTIC, CORPUS_TYPED, CORPUS_WIDE_SYNTACTIC } from "./ledger.ts";

const VERB_LIST = [...Object.keys(VERBS), ...Object.keys(DEPCRUISE_VERBS)].join("|");

export const USAGE = [
  `usage: pnpm ast <${VERB_LIST}> <arg> [--in substr] [--files] [--public] [--all] [--near [pct]] [--json] [--max n]`,
  "",
  "Structural + semantic workspace search (ts-morph). Prefer this over grep for CODE questions.",
  "Each verb below states whether it follows symbol identity or matches syntax/spelling.",
  "",
  "  pnpm ast refs MessageView          every real reference to the symbol (defs marked) — slow, exact",
  "  pnpm ast callers sendTurn          call sites (incl. method tails obj.sendTurn())",
  "  pnpm ast subset-callers sendTurn   call sites passing a STRICT SUBSET of another's param keys (stale doors)",
  "  pnpm ast importers @orb/ui/badge   who imports a module (static + dynamic import())",
  "  pnpm ast exports preset/lib        exported symbols of a file or dir",
  "  pnpm ast jsx ListRow               JSX usages of a component (BOTH <X>…</X> and <X />; name is POSITIONAL — there is no --name flag)",
  "  pnpm ast ident probeMode           raw identifier occurrences (fast; comments/strings excluded)",
  "  pnpm ast literal chatDeleted       STRING-LITERAL text only (never idents/comments) — the coupled-fixture sweep",
  "  pnpm ast dead legacyHelper         evidence ladder for ONE symbol (product/tool/test refs, swallowed, @public, …)",
  "  pnpm ast orphans server            exports reached by NOBODY (prod or test) — resolution-based rot",
  "  pnpm ast testonly server           exports reached ONLY from tests — resolution-based rot",
  "  pnpm ast prodonly server           FILES no production entry can reach (the knip unused-files lens)",
  "  pnpm ast cycles client             import cycles, alias-resolved — slow, exact",
  "  pnpm ast aliases packages/server   rename-bindings (X as Y / const Y = X / type Y = X)",
  "  pnpm ast unwired                   server tRPC procedures NO client consumes (the PD-138 blind spot)",
  "  pnpm ast clientgap contracts       *View/*Summary contracts the SERVER uses but the CLIENT never does",
  "  pnpm ast viewgap                   *View/*Summary FIELDS no packages/client/src file reads (the field-level clientgap)",
  "  pnpm ast swallowed db              exports alive ONLY because an `import * as` swallowed their module",
  "  pnpm ast respell chat              domain contract/ shapes structurally identical to an @orb/contracts shape",
  "  pnpm ast respell chat --near 75    ADDS a NEAR tier beside the exact one: Jaccard field-diff, 75%+ threshold",
  "  pnpm ast typeonly-alive server     VALUE exports whose every reference is a TYPE position (runtime-dead)",
  "  pnpm ast columns rpg_games         drizzle columns by consumption: READ+WRITE / WRITE-only / READ-only / NEITHER",
  "  pnpm ast regkeys TEMPLATE_DEFS     registry ROWS whose key is dispatched nowhere (HEURISTIC, informational)",
  "  pnpm ast registry-candidates       convention-maintained open sets that may need a registry door (INFORMATIONAL)",
  "  pnpm ast contract-field-liveness   contracts FIELDS no producer populates (INFORMATIONAL — the caption class one tier up)",
  "  pnpm ast chains server             WHOLE dead chains: declarations alive only via other DEAD declarations",
  "  pnpm ast stringy kit               type aliases that RESOLVE to bare `string` (no narrowing, no brand)",
  "  pnpm ast apisurface contracts      exports by package boundary: PUBLIC (cross-pkg) / INTERNAL / UNUSED",
  "  pnpm ast rot server                orphans+testonly+chains+typeonly-alive+swallowed over ONE package, ONE load",
  "  pnpm ast flow chat/engine          packages+tooling graph: X's direct edges both ways (depcruise, text)",
  "  pnpm ast reaches agent-sdk         packages+tooling modules that can transitively reach X (depcruise)",
  "",
  "ARGV IS STRICT (#452 — a silent false clean is the one failure this tool exists to prevent): every",
  "  verb's SUBJECT is positional and comes FIRST; there is no --name/--component flag. A flag where a",
  "  required subject belongs (`pnpm ast jsx --name Button` — which used to SEARCH FOR the flag itself and",
  "  print a clean matches=0 over 5433 scanned files) and any argument this parser cannot name (a typo'd",
  "  `--fles`) both REFUSE with exit 3 (misuse). A zero is only ever printed beside the receipt below.",
  "",
  "AUDIT EPILOGUE — every run ends with ONE line on STDERR (stdout is byte-unchanged, so pipes/redirects",
  "  keep working). It is what makes a zero trustworthy:",
  "    [ast] verb=… scope=… langs=ts:N,tsx:N scanned=N skipped=N(reason:count,…) matches=N status=complete|partial|error",
  "  scanned = the files the SCOPE admitted (what a hit can come from), counted by the same pass that fed",
  "  the lens; a whole-workspace substrate pass (liveness, reference resolution) is deliberately NOT counted.",
  "  skipped reasons: out-of-scope · out-of-filter (--in) · test-file · declaration-file.",
  "  status: complete = all matches shown · partial = the list was capped (raise --max) · error = NOT a",
  "  verdict. `--json` carries the same fields as an additive `meta` object (no existing key changes).",
  "  scanned=0 prints `SCOPE ENTERED NOTHING` and exits 2 — nothing was searched, so nothing could be found.",
  "  THREE CORPORA: syntactic/wide labels derive from the shared glob authority; typed names its native-program source:",
  `    syntactic: ${CORPUS_SYNTACTIC}`,
  `    typed: ${CORPUS_TYPED}`,
  `    wide syntax (literal): ${CORPUS_WIDE_SYNTACTIC}`,
  "  Typed verbs add native TypeScript program semantics. `literal` uses the wide roots without a type graph.",
  "  (`pnpm --filter <pkg>` scopes the BUILD, never this lens: use the scope arg or --in, and read scope=.)",
  "",
  "Scope arg (orphans/testonly/prodonly): a package NAME (kit|contracts|db|server|client|ui) OR a path",
  "  under packages/<pkg>/src (`packages/server/src/domain/chat`). A scope matching zero files is a tool",
  '  error — it prints what was tried + a suggestion and exits 2 (never a silent "no results"). The same',
  "  rule now covers every other scope shape: a raw path (exports/aliases/cycles), an --in filter that",
  "  matches nothing, and the UNIT scopes (unwired procedures, columns tables, regkeys registries,",
  "  respell domains) — zero units is a blind lens, not a clean one.",
  "  orphans/testonly key liveness on (declaring-file, export name), not bare name: same-file use,",
  "  dynamic import(), and `import * as` namespaces all count as alive; name collisions never merge.",
  "  orphans NAMES every star-suppressed candidate (`~ file:line [star-suppressed] <symbol>`) above the hit",
  "  list when a barrel's members are only reachable through an `export *` chain — reported per SYMBOL,",
  "  never counted as a hit, so a zero is legible as clean rather than as star-blindness.",
  "",
  "prodonly is the FILE lens (testonly/orphans are symbol lenses): it BFS-walks the resolved import graph",
  "  (static + dynamic + star/namespace edges) from the production entry set — derived from each",
  "  package.json `exports` map + package scripts/tool config runtime entries, never knip analysis roots — and",
  "  reports source files no entry reaches. A file reachable only from a test IS prod-unreachable (the",
  "  point of the lens); it is stricter than `knip:prod` for test-only-reachable package-subpath files.",
  "",
  "unwired diffs two STRUCTURAL surfaces (import-liveness is blind to both — the client consumes via the",
  "  typed proxy, not an import edge): the server `t.router({…})` object-literals (keyed `<ns>.<proc>` off",
  '  the appRouter namespacing) MINUS the client\'s `trpc.<ns>.<proc>` chains + `Trpc["<ns>"]["<proc>"]`',
  "  inferences. Optional arg = a `<ns>.<proc>` substring (a router name) to scope; bare = all procedures.",
  "",
  "clientgap (CANDIDATE lens, run on demand) = exports used by server product code but NOT client product code.",
  "  Test imports annotate behavior but do not acquit an unwired product surface; db/kit/inference/ui/tool",
  "  consumption stays outside the exact-server evidence bucket.",
  "  Default scope `contracts`, filtered to client-facing wire names (`*View`/`*Summary`) — a UI shape the",
  "  server produces but the front-end never wired. A hit may be client-consumed via a re-exported barrel",
  "  or a `Trpc[…]` inference the import-liveness can't see — VERIFY before acting. A path/package scope",
  "  overrides the filter and reports every server-only gap in it (noisier).",
  "",
  "viewgap (CANDIDATE lens, run on demand) = clientgap's FIELD tier, and the one instrument for the",
  "  server-View-field-the-client-never-reads class (#650 `netHosts`; the MessageView per-turn economics).",
  "  clientgap is EXPORT-level, so a `*View` the front-end imports at all reads as wired however many of its",
  "  fields the UI never renders. A hit is a field of a `*View`/`*Summary` declared in packages/contracts/src",
  "  or packages/server/src (a domain `contract/views.ts` — projected through the tRPC proxy, an inference no",
  "  import edge sees) that NO file under packages/client/src spells as a read. READS are the SAME index",
  '  `contract-field-liveness` uses — all three property shapes (`x.foo` / `x?.foo` / `x["foo"]`) plus object',
  "  destructuring, tests excluded — so the two lenses cannot fork on what a read is. NAME-matched, never",
  "  type-resolved: any client file spelling the name absolves the field, so the lens UNDER-reports (a hit is",
  "  strong, a clean run weak), and a `{ ...view }` spread / a computed-key read / a rename inside an @orb/ui",
  "  primitive are stated blind spots. Every run prints its DENOMINATORS (fields, owners, owner files, client",
  "  reader files); an EMPTY reader corpus is a TOOL ERROR, never a clean sweep. `unwired ≠ worthless` — a hit",
  "  is an intent question (wire it, mark it, delete it). Keep a deliberate one with `// @view-server-only:",
  "  <reason>` on the field; a marker on a field the client now reads is STALE and exits 1 (two-sided).",
  "  Optional scope = a field name / owner name / owner-file path; bare = every view field.",
  "",
  'swallowed (CANDIDATE lens, run on demand) = the rot-hider class. `import * as ns from "#schema"` +',
  "  `drizzle(client, { schema })` marks EVERY export of that module alive without naming one, so a dead",
  "  export inside a namespace-consumed barrel reads as consumed forever. A hit is an export whose ONLY",
  '  liveness arm is that namespace import, that no swallowing file ever spells (`ns.x` / `ns["x"]` /',
  "  `const {x} = ns`), that no named import reaches anywhere (prod OR test), and that its own file never",
  "  uses. It may still be load-bearing THROUGH the swallowing API — VERIFY, never auto-delete. Keep one",
  "  deliberately with `// @swallowed-ok: <reason>` on the declaration; a marker the lens no longer agrees",
  "  with is reported STALE and exits 1 (two-sided). Optional scope; bare = every package.",
  "",
  "respell (CANDIDATE lens, run on demand) = a domain `contract/` shape structurally identical to (mutually",
  "  assignable with) a sibling `@orb/contracts/<domain>` shape — the RENAMED re-spell the syntactic gate",
  "  (`contract-derives-not-respells`) cannot see. `--near [pct]` (default 80 when the flag is present)",
  "  ADDS a NEAR tier beside it, never replacing it: Jaccard similarity over (fieldName, semanticType)",
  "  pairs, on the SAME axis, floor 4+ fields both sides, excluding every pair the exact tier already",
  "  resolves. Reports a FIELD-LEVEL DIFF, never a bare percentage — shared-field count, fields that kept",
  "  their TYPE but changed NAME, and each side's leftover fields (`7/9 shared (82%) · renamed-same-type:",
  "  updatedAt→modifiedAt · domain-only: scope`). Keep a deliberate near-pair with `// @nearpair-ok:",
  "  <reason>` on the domain declaration; a marker the lens no longer agrees with is STALE and exits 1",
  "  (two-sided). Optional scope; bare = every domain.",
  "",
  "typeonly-alive (CANDIDATE lens, run on demand) = the STRUCTURAL-liveness class: a VALUE export (function,",
  "  const, class, enum — never an interface/type alias, which is type-only by nature) whose EVERY reference",
  "  is a TYPE position: an `import type` specifier, `typeof X`, an annotation, an `implements`/interface",
  "  `extends` clause. Nothing ever calls, reads or constructs it — it ships a runtime body to satisfy a",
  "  shape. Classified by REFERENCE POSITION, not import form (a plain `import { X }` used only as `typeof X`",
  "  is exactly the defect), so it sees through renaming barrels, `export *`, `import * as ns` member access",
  "  and dynamic-import member access. An export nothing references at all is an `orphans` hit, not this one.",
  "  Keep a deliberate conformance seam with `// @typeonly-ok: <reason>`; a stale marker exits 1 (two-sided).",
  "  Optional scope; bare = every package. SLOW — it costs one `refs` resolution per value export.",
  "",
  "columns (CANDIDATE lens, run on demand) = the RV-11 class: every drizzle column in packages/db/src/schema",
  "  classified by how the WORKSPACE consumes it — READ+WRITE (healthy, never a hit) · WRITE-only (something",
  "  fills it, nothing ever reads it back) · READ-only (rendered but never written — a permanent default) ·",
  "  NEITHER (pure rot). READS are EXACT (language-service references, which resolve BOTH `<table>.<col>`",
  "  query refs and `<row>.<col>` accesses on an inferred row); WRITES are STRUCTURAL (drizzle's `$inferInsert`",
  "  is a mapped type whose properties carry ZERO declarations, so no reference resolution can see a write) —",
  "  walked from every `insert(<T>)….values(x)` / `update(<T>)….set(x)` / `.onConflictDoUpdate({set:x})`. A",
  "  whole-row or spread writer names no column, so it marks its TABLE opaque and every column of it prints",
  '  `write?` — never "unwritten". A `raw?` annotation = the column\'s SQL name appears in some raw `sql`',
  "  template; v1 CANNOT attribute an alias-qualified raw query to a table, so that arm is table-agnostic and",
  "  deliberately over-inclusive. Scope = a SQL table name / table variable / schema-file substring; bare =",
  "  every table. Keep one deliberately with `// @column-ok: <reason>` on the column property; a marker on a",
  "  now-READ+WRITE column is reported STALE and exits 1 (two-sided). SLOW — one reference resolution per column.",
  "",
  "regkeys (HEURISTIC + INFORMATIONAL — never gates, no exemption marker, owner-ruled) = the ROW-level blind",
  "  spot every symbol lens shares: a string-keyed dispatch table is ONE live symbol however many of its rows",
  "  are dead. A registry is derived structurally (an exported const with 3+ rows carrying a `Record<…>`",
  "  annotation or a SCREAMING_SNAKE name — an OBJECT literal keyed by property name, or an ARRAY literal of",
  '  `{ id: "<key>" }` rows, the TEMPLATE_DEFS shape), and a row is reported when its KEY is spelled — as a',
  "  string, a property name, an identifier, or a JSX attribute — in NO non-test file outside its own table.",
  "  EXPECT FALSE POSITIVES: a key from the DB, a URL segment, a template literal, or an `Object.keys(REG)`",
  "  iteration is a LIVE row that looks dead here. That is exactly why it never gates. Syntactic only, so fast.",
  "",
  "chains (CANDIDATE lens, run on demand) = the ALIAS-RABBIT-HOLE class `orphans` is structurally blind to.",
  "  `orphans` asks 'does anything reach this export?' and stops, so a dead chain (`export const Head = Mid`",
  "  that nobody consumes, `export const Mid = Deep`, `function Deep()`) reports as ONE hit — the head — and",
  "  costs a delete-and-rerun cycle per link. No FILE lens can help either: the middle links live inside",
  "  perfectly live files. `chains` runs a FIXPOINT over a DECLARATION-granular consumption edge (which",
  "  declaration's body holds the consuming reference, not merely which file) and reports whole chains in one",
  "  run: `X ← only via Y (dead) ← only via Z (unconsumed)`. ALIVE ROOTS: a module-scope side-effect consumer,",
  "  a consumer in a test/script (outside packages/), any reasoned `@public`-family export (treated alive",
  "  conservatively here; the ratchet separately judges marker legality), and every `packages/ui/src` export",
  "  (the R2 sealed surface). A declaration NOTHING reaches is an `orphans` hit and is deliberately NOT repeated",
  "  here. There",
  "  is NO per-link exemption marker by design — every chain ends at an unconsumed head that `orphans` already",
  "  reports and the ratchet already governs, so FIX AT THE HEAD (wire it, delete it, or add a reasoned",
  "  `@public`-family claim for the ratchet to adjudicate) and the",
  "  whole chain resolves. VERIFY before acting: a consumer this substrate cannot see (a DB-keyed registry",
  "  row, a `Trpc[…]` proxy read) makes a live declaration look chain-dead, and a fixpoint amplifies one",
  "  missed edge into a whole dead-looking subtree. Optional scope; bare = every package.",
  "",
  "stringy (FINDINGS lens, run on demand) = an alias that NEITHER NARROWS NOR BRANDS: its RESOLVED type is",
  "  exactly `string`, so it buys a name and gives up all checking while READING like a type at the call site.",
  "  DO NOT confuse it with `aliases` — that verb reports rename laundering (`X as Y` / `const Y = X` /",
  "  `type Y = X`: one declaration under N public names) and never inspects what a type MEANS; this one never",
  "  inspects what an alias is NAMED. Resolution-based on purpose: the direct `type X = string` is a grep, but",
  "  `type A = B` where B is `string` across import + re-export hops in another package is invisible to every",
  "  syntactic tool. NOT reported, because each genuinely narrows: a template-literal type (a backticked",
  "  `chat_` prefix over a string placeholder), the brand `string & { readonly [brand]: B }` (`Branded`/",
  "  `TypeIdOf`, packages/kit/src/ids — the sanctioned form), a literal union or any",
  "  union merely CONTAINING string (`JsonValue`, `string | null`), a `T extends string` parameter, and `string`",
  "  inside an object/array. A generic whose body is `string` regardless of its parameters IS reported. Each hit",
  "  prints its RESOLUTION CHAIN (`A → B @ file:line → string`) — that is what names the fix: BRAND it, NARROW",
  "  it, or DELETE the alias and use the primitive. No exemption marker and no gate (owner-ruled: the verdict is",
  "  a human's four-way call, and a marker no gate reads is dead vocabulary). Optional scope; bare = all packages.",
  "",
  "apisurface (CANDIDATE lens, run on demand) = the BARREL-BLOAT class `orphans`/the ratchet are blind to.",
  "  `orphans` is BINARY (any importer vs none), so an export used all over its OWN package but by no other",
  "  package reads exactly like a real cross-boundary API. This verb partitions every export by the PACKAGE of",
  "  its consumers: PUBLIC (≥1 PROD consumer in a DIFFERENT workspace package — the consuming package(s) are",
  "  printed; `(type-only)` when every cross-pkg consumer imported it as a TYPE) · INTERNAL (consumed ONLY",
  "  within its own package — a candidate to un-export from the barrel / make module-private) · UNUSED (the",
  "  `orphans` set verbatim, so the two never disagree — star-suppressed candidates carry the same caveat) ·",
  "  TEST-ONLY (no prod consumer anywhere, but a test imports it — cross-boundary yet NOT prod API, flagged",
  "  distinctly so a PUBLIC count is a real prod-API count). It keys on the origin declaration (a renaming",
  "  barrel hop cannot fork identity) and mirrors `orphans`' err-alive arms: a namespace consumer",
  "  (`import * as ns`) or a dynamic import promotes a whole module to PUBLIC — VERIFY with `swallowed`.",
  "  Default lists INTERNAL + TEST-ONLY + UNUSED (the actionable arms); `--public` adds the PUBLIC rows.",
  "  Optional scope (a package name / path); bare = every package, grouped in a per-package count table.",
  "",
  "literal (WIDE-CORPUS search, run on demand) = string-LITERAL text ONLY — the exact complement of `ident`",
  "  (which never looks inside a string). Matches `value` as a substring of a StringLiteral /",
  "  NoSubstitutionTemplateLiteral's full text, and every STATIC chunk of a TemplateExpression (the text",
  "  between interpolation holes — an interpolated hole is never text, so it never matches). Runs over",
  "  the WIDE corpus (tests + fixtures + scripts, no type graph): the coupled-fixture sweep a value-",
  "  changing merge needs — 'which code/tests pin this literal' as one receipted command instead of a",
  "  noisy `rg` that also matches comments and identifiers.",
  "",
  "subset-callers (CANDIDATE lens, run on demand) = the STALE-DOOR class (#539). Two call sites of one wire",
  "  verb are structurally identical to every text-based instrument (cpd, respell) and to every gate, so a",
  "  door that stopped being updated is invisible: SpeakAsSelect passed `{speakerCharacterId}` while the",
  "  surviving door also carried guided steer + responseNudge, and one affordance silently lost two features.",
  "  This verb matches call sites the way `callers` does (bare `send(…)` and method-tail `api.send(…)`),",
  "  reads the FIRST argument's object KEYS, and reports each site whose key set is a STRICT SUBSET of",
  "  another site's, naming the MISSING keys and the superset sites. NOT reported: equal key sets, disjoint",
  "  key sets, and a partial overlap in both directions (two doors that diverged — a different class, with",
  "  no stale one to name). RESOLUTION IS ONE HOP, SAME FILE: an object literal (through `(…)`/`as`/",
  "  `satisfies` wrappers), or an identifier naming a same-file const whose initializer is one. Anything",
  "  else — a SPREAD, a COMPUTED key, a parameter, an imported value, a call result — is UNJUDGED: printed",
  "  by site with its reason above the hits, never silently dropped. Fewer than two RESOLVED sites (or none",
  "  at all) is a TOOL ERROR, not a clean verdict — the comparison was never possible.",
  "  THE SUBJECT IS THE COMPARISON UNIT (same property `callers` has): a shared method TAIL — `mutate`,",
  "  `call`, `parse` — pools every unrelated verb that spells it, and every finding is then noise. Name the",
  "  verb or the hook, and narrow with --in <path>. The banner prints this caveat beside its own numbers.",
  "  THE CLIENT-DOOR ARM (#572): a client affordance names its verb only where it is CREATED",
  "  (`createEntityMutation({ options: (trpc) => trpc.chat.generate.mutationOptions() })`) and fires through",
  "  a bare `.mutate(…)` that names nothing — so this lens ALSO resolves each fire site's RECEIVER back to",
  "  its factory hook and pools those keys under the verb the subject names (bare member `generate`, or the",
  "  full path `chat.generate`). That resolution is the SAME one `duplicate-action-doors` counts doors with",
  "  (tooling/src/_shared/trpc-doors.ts — ONE home, so the gate's census and this lens cannot disagree about",
  "  what a door is). It is LEVEL 1: a receiver bound same-file to a corpus-indexed hook. Every run prints a",
  "  DOOR CLASSES banner saying what it could and could not judge — a fire site the resolver cannot follow",
  "  (a parameter, a cross-module binding, an ambiguous hook name) is COUNTED there, a destructured",
  "  `const { mutate } = useX()` is out of reach entirely and the banner says so, and ZERO indexed factories",
  "  is a TOOL ERROR (the arm ran blind), never a narrower clean. A finding whose subset and every superset",
  "  sit in DIFFERENT classes is marked CROSS-CLASS: a wire payload cannot carry server-only fields like",
  "  `principal`, so that is pooling, not a stale door — the #539 class is a client door under ANOTHER",
  "  client door, and same-class supersets are named FIRST so that evidence never hides behind `+N more`.",
  "",
  "dead (CANDIDATE lens, run on demand) = a composite evidence-ladder verdict for ONE symbol, resolved",
  "  once (the same substrate `refs` uses) and laid out as a table: shipped-product references (count + up",
  "  to 3 sites) · tool/script references · test-only references · namespace-swallowed consumption (the `swallowed` collector, scoped to",
  "  this declaration) · the `@public`-family marker · a vendored-file home (informational — `/vendor/` or",
  "  a header comment saying so) · raw COMMENT-TEXT mentions (informational — the one arm here that",
  "  deliberately reads comments). Ends with ONE verdict, evidence-priority order: ALIVE (≥1 prod ref) ·",
  "  SWALLOWED-ONLY (may be load-bearing THROUGH the swallowing API) · TAGGED-KEEP (a `@public` marker) ·",
  "  TOOL-ANCHORED (reached only from tooling/scripts) · TEST-ANCHORED (reached only from tests) · CANDIDATE",
  '  (nothing reaches it). "Unwired ≠ worthless"',
  "  (constitution §1) — the verdict is a human's, never a delete signal. A name with several declarations",
  "  (a collision) is classified once per declaration.",
  "",
  "rot (CANDIDATE lens, run on demand) = the five rot collectors — orphans / testonly / chains /",
  "  typeonly-alive / swallowed — over ONE package, with ONE project load + ONE liveness build instead of",
  "  five separate ~40s loads. Each section calls the EXACT collector function its standalone verb calls",
  "  (never a re-derived copy), so behavior parity is structural. Bucketed/stale-marker narration (star-",
  "  suppression, declared test seams, the union-source bucket, `@…-ok:` staleness) is each standalone",
  "  verb's own business and is NOT reproduced here — run the verb directly for that detail. Required arg",
  "  = a package name / path (no bare form).",
  "",
  "Flags: --in <substr> path filter · --files per-file counts only (cheapest output) ·",
  "       --public (apisurface) also list PUBLIC rows, not just the actionable arms ·",
  "       --all (columns/regkeys) per-table/per-registry sectioning over EVERY table/registry — full",
  "       findings for one that has any, one collapsed line for a clean one, instead of forty manual",
  "       per-table/per-registry runs ·",
  "       --near [pct] (respell) ADDS a NEAR tier beside the exact one, default 80 when the flag is",
  "       present — never changes the exact tier's output ·",
  "       --max <n> raw-line cap (default 60; big result sets auto-collapse to per-file counts) ·",
  "       --json machine output (one JSON value; rot and respell --near retain repeated section values).",
  "              flow/reaches are dependency-cruiser text pass-throughs and explicitly refuse --json.",
  "       Syntactic verbs load in ~10s;",
  "       refs/callers/importers/jsx/dead/cycles/orphans/testonly/prodonly/typeonly-alive/columns/apisurface/rot resolve types;",
  "       aliases/exports/ident/literal load the wide corpus without resolving types.",
].join("\n");
