// The generated files: the three tree indexes and each plan's `tasks.md`. Pure renderers over parsed
// summaries, byte-deterministic, so `pnpm doc index` writes them and the checker proves the tree carries
// exactly what a fresh render would produce. A generated file carries `kind: index` and no `updated`
// (its date would make every day's render differ from the committed bytes).
import { DOC_TOOL_TREES, FIRST_RESERVED_RULING, LAST_RESERVED_RULING } from "#doc-catalog";
import type { DocSummary, WorkItem } from "../contract/types.ts";
import { renderFrontmatter } from "./frontmatter-write.ts";
import { basenameOf, padId, parseNumberedName } from "./names.ts";

const GENERATED_FIELDS = { kind: "index", status: "active" } as const;
const NOTE = "Generated by `pnpm doc index`";
const SHORT_SHA = 12;

export const ADR_INDEX_PATH = `${DOC_TOOL_TREES.adr}README.md`;
export const PLAN_INDEX_PATH = `${DOC_TOOL_TREES.plans}README.md`;
export const WORK_INDEX_PATH = `${DOC_TOOL_TREES.work}README.md`;
export const LAW_INDEX_PATH = `${DOC_TOOL_TREES.law}README.md`;
export const TASKS_FILE = "tasks.md";
export const DESIGN_FILE = "design.md";

const RESERVED_WINDOW = `D${String(FIRST_RESERVED_RULING)}–D${String(LAST_RESERVED_RULING)}`;
/** The standing rules of the decision tree, folded in from the retired ledger index doc: precedence, the
 *  citation form, and the reserved window. */
const ADR_INDEX_PREAMBLE =
  "On any conflict a decision here wins over every other doc. Cite one as a bare `D<n>`; the number is the file number and never changes. " +
  `${RESERVED_WINDOW} are reserved for main-era rulings that rolled back while the code obeying them survived: such a number is re-minted with its original number and meaning, and a new decision is never minted into the window.\n\n`;
/** Where the standing law's anchors are, folded in from the retired ledger index doc. Named in words, not
 *  paths: every planted tree renders this index, and a path a planted tree cannot hold would read as a dead
 *  reference. */
const LAW_INDEX_PREAMBLE =
  "The locked principles are the first section of Core-0, the enforcement catalog is the active-gates doc, " +
  "and decisions are the ADR tree beside this one.\n\n";

function head(title: string, note: string): string {
  return `${renderFrontmatter(GENERATED_FIELDS)}\n# ${title}\n\n${NOTE}; ${note}\n\n`;
}

function relativeTo(fromDir: string, path: string): string {
  const from = fromDir.split("/").filter((part) => part !== "");
  const to = path.split("/");
  let common = 0;
  while (common < from.length && common < to.length - 1 && from[common] === to[common]) {
    common += 1;
  }
  return [...from.slice(common).map(() => ".."), ...to.slice(common)].join("/");
}

export function isGeneratedPath(path: string): boolean {
  return (
    path === ADR_INDEX_PATH ||
    path === PLAN_INDEX_PATH ||
    path === WORK_INDEX_PATH ||
    path === LAW_INDEX_PATH ||
    (path.startsWith(DOC_TOOL_TREES.plans) && basenameOf(path) === TASKS_FILE)
  );
}

/** The plan slug a `docs/plans/<slug>/…` path belongs to. */
export function planSlugOf(path: string): string | null {
  if (!path.startsWith(DOC_TOOL_TREES.plans)) {
    return null;
  }
  const rest = path.slice(DOC_TOOL_TREES.plans.length).split("/");
  return rest.length > 1 ? (rest[0] ?? null) : null;
}

export function planDirOf(path: string): string {
  return path.slice(0, path.lastIndexOf("/") + 1);
}

export function renderAdrIndex(adrs: readonly DocSummary[]): string {
  const rows = adrs
    .map((adr) => ({ adr, name: parseNumberedName(basenameOf(adr.path)) }))
    .filter((row): row is { adr: DocSummary; name: { id: number; slug: string } } => row.name !== null)
    .toSorted((left, right) => left.name.id - right.name.id)
    .map(({ adr, name }) => {
      const status =
        adr.supersededBy === null ? adr.status : `${adr.status} by [${basenameOf(adr.supersededBy)}](${relativeTo(DOC_TOOL_TREES.adr, adr.supersededBy)})`;
      return `| D${String(name.id)} | [${adr.title}](${basenameOf(adr.path)}) | ${status} |`;
    });
  return `${head("Decisions", "mint one with `pnpm doc new adr <slug>`, never by hand.")}${ADR_INDEX_PREAMBLE}| Id | Decision | Status |\n| - | - | - |\n${rows.join("\n")}\n`;
}

export function renderLawIndex(laws: readonly DocSummary[]): string {
  const rows = laws.toSorted((left, right) => left.path.localeCompare(right.path)).map((law) => `| [${law.title}](${basenameOf(law.path)}) | ${law.status} |`);
  return `${head("Law", "mint one with `pnpm doc new law <slug>`; change the doc, never this file.")}${LAW_INDEX_PREAMBLE}| Law | Status |\n| - | - |\n${rows.join("\n")}\n`;
}

export function renderPlanIndex(plans: readonly DocSummary[]): string {
  const rows = plans
    .toSorted((left, right) => left.path.localeCompare(right.path))
    .map((plan) => `| [${plan.title}](${relativeTo(DOC_TOOL_TREES.plans, plan.path)}) | ${plan.status} |`);
  return `${head("Plans", "mint one with `pnpm doc new plan <slug>`; delete a finished one with `pnpm doc remove <path>`.")}| Plan | Status |\n| - | - |\n${rows.join("\n")}\n`;
}

function itemTail(item: WorkItem): string {
  if (item.state === "doing") {
    return item.lane === null ? "" : ` (${item.lane})`;
  }
  if (item.state === "blocked") {
    return item.blocked === null ? "" : ` (${item.blocked})`;
  }
  if (item.state === "done") {
    return item.evidence === null ? "" : ` (${item.evidence.slice(0, SHORT_SHA)})`;
  }
  return "";
}

function itemLine(item: WorkItem, fromDir: string): string {
  const priority = item.priority ?? "triage";
  const plan = item.plan === null ? "" : ` \`${item.plan}\``;
  return `[${padId(item.id)}](${relativeTo(fromDir, item.path)}) ${priority} ${item.title}${plan}${itemTail(item)}`;
}

export function renderWorkIndex(items: readonly WorkItem[]): string {
  const byId = items.toSorted((left, right) => left.id - right.id);
  const section = (state: WorkItem["state"], title: string): string => {
    const lines = byId.filter((item) => item.state === state).map((item) => `- ${itemLine(item, DOC_TOOL_TREES.work)}`);
    return `## ${title}\n\n${lines.length === 0 ? "None.\n" : `${lines.join("\n")}\n`}`;
  };
  return `${head("Work items", "mint one with `pnpm doc item <title> --kind <kind>`; move one with `pnpm doc set` or `pnpm doc land`.")}${[
    section("open", "Open"),
    section("doing", "Doing"),
    section("blocked", "Blocked"),
    section("done", "Done"),
  ].join("\n")}`;
}

/** A plan's task list: its items by id, ticked when done. Links are relative to the plan folder. */
export function renderTasks(planTitle: string, planDir: string, items: readonly WorkItem[]): string {
  const lines = items.toSorted((left, right) => left.id - right.id).map((item) => `- [${item.state === "done" ? "x" : " "}] ${itemLine(item, planDir)}`);
  return `${head(`${planTitle}: tasks`, "one line per work item carrying this plan's slug; change the item, never this file.")}${lines.length === 0 ? "None yet.\n" : `${lines.join("\n")}\n`}`;
}
