// Names the model, provider and connection behind a generation, from the persisted record alone. A swipe's
// `connectionId` is SET NULL when its connection is deleted and null on imports, so a recorded model with no
// connection cannot tell those two apart, and the credit says exactly that rather than guessing.

import type { MessageView } from "@orb/contracts/chat";
import { builtinProvider, providerDisplayLabel } from "@orb/contracts/inference";
import type { UserConnectionId } from "@orb/kit/ids";
import { modelDisplayName } from "@orb/kit/model-name";

/** One of the VIEWER's own connection rows (`connection.list`), as a readout names it. */
export interface CreditConnectionRow {
  readonly id: UserConnectionId;
  readonly label: string;
  readonly providerLabel: string;
}

/** The viewer's connection list as a readout sees it. `rows` absent and `failed` false is the pending read. */
export interface CreditConnections {
  readonly rows: readonly CreditConnectionRow[] | undefined;
  readonly failed: boolean;
}

/** The provider's shown name: the viewer's own row wins (it knows plugin and admin rows), then the shipped
 *  registry, then the raw id — a runtime provider the client has no registry for still names itself. */
export function providerName(providerId: string, row: CreditConnectionRow | undefined): string {
  if (row !== undefined) {
    return row.providerLabel;
  }
  const shipped = builtinProvider(providerId);
  return shipped === undefined ? providerId : providerDisplayLabel(shipped);
}

/** The connection half of the credit. `null` while the viewer's list is still loading. A recorded id outside
 *  a loaded list is usually the host's (a shared room runs on the host's connection); the copy states only
 *  what the client knows, because a transcript cached from before a delete still carries the old id. */
function connectionClause(connectionId: UserConnectionId | null, connections: CreditConnections): string | null {
  if (connectionId === null) {
    return "Connection: deleted or never recorded.";
  }
  if (connections.failed) {
    return "Connection: couldn't be looked up.";
  }
  if (connections.rows === undefined) {
    return null;
  }
  const row = connections.rows.find((candidate) => candidate.id === connectionId);
  return row === undefined ? "Connection: not in your list." : `Connection: ${row.label}.`;
}

/** The whole credit sentence for one shown swipe, or `null` when the swipe records no model: a card greeting
 *  or a draft was never generated, so there is nothing to credit. */
export function generationCreditSentence(message: Pick<MessageView, "model" | "provider" | "connectionId">, connections: CreditConnections): string | null {
  if (message.model === null || message.model.trim() === "") {
    return null;
  }
  const row = message.connectionId === null ? undefined : connections.rows?.find((candidate) => candidate.id === message.connectionId);
  const via = message.provider === null ? "" : ` via ${providerName(message.provider, row)}`;
  const lead = `Generated by ${modelDisplayName(message.model)}${via}.`;
  const connection = connectionClause(message.connectionId, connections);
  return connection === null ? lead : `${lead} ${connection}`;
}
