// The `devtools-frontend-assets` family test (#1584). Everything a PROOF ROW can express now lives in the
// module's own `mustFlag`/`mustPass`/`mustRefuse` rows and runs on the static bar through
// `structure:policy-conformance`; this file carries only what a row structurally cannot.
//
// What a row cannot be here, and it is the #2149 obligation: a REAL-CORPUS LIVENESS PIN. Every proof row
// materialises a one-resource synthetic closure in a temp root, so a policy that had quietly stopped
// reaching the repository's actual 500-member vendored closure would keep every row green and report
// nothing forever — silent-because-dead reading exactly like silent-because-clean. The two arms below are a
// virtual OVERLAY on the real root: the clean one asserts the live verdict and the receipt census, the
// broken one asserts the policy REPORTS on the real subject.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { Project } from "ts-morph";
import { DEVTOOLS_CLOSURE_PIN, DEVTOOLS_CLOSURE_ROOT } from "../../../../tooling/src/verify/contract/resource-artifact.ts";
import { gate as devtoolsFrontendAssets } from "../../../../tooling/src/verify/gates/devtools-frontend-assets.ts";
import { runPolicyPass } from "../../../../tooling/src/verify/lib/policy-pass.ts";
import { verifyPolicyProofs } from "../../../../tooling/src/verify/ops/policy-conformance.ts";
import { expect, test } from "../../../support/tool-fixtures.ts";

const REPO_ROOT = new URL("../../../../", import.meta.url).pathname.replace(/\/$/u, "");
const CLOSURE_ROOT = join(REPO_ROOT, DEVTOOLS_CLOSURE_ROOT);

/** The live closure's member count, DERIVED rather than pinned as a literal: the vendored root is
 *  regenerated by `pnpm snap:devtools-assets` and a hardcoded number would make a legitimate regeneration
 *  red this test. The claim is that the policy's receipt equals the real census, not that the census is N. */
function liveMemberCount(directory = CLOSURE_ROOT): number {
  return readdirSync(directory, { withFileTypes: true }).reduce(
    (total, entry) => total + (entry.isDirectory() ? liveMemberCount(join(directory, entry.name)) : 1),
    0,
  );
}

function runOverReal(overlay: Readonly<Record<string, string>>): ReturnType<typeof runPolicyPass> {
  return runPolicyPass({
    knownPolicies: [devtoolsFrontendAssets],
    policies: [devtoolsFrontendAssets],
    root: REPO_ROOT,
    project: new Project({ skipAddingFilesFromTsConfig: true }),
    resourceOptions: { overlay },
    reviewedGrants: [],
    failOnWarnings: false,
  });
}

test("devtools-frontend-assets keeps its three-arm proofs", () => {
  expect(verifyPolicyProofs([devtoolsFrontendAssets])).toEqual([]);
});

test("the policy reaches a verdict on the REAL vendored closure and receipts the members it measured", () => {
  const result = runOverReal({});

  expect(result.toolErrors).toEqual([]);
  expect(result.authority.effectiveFindings).toEqual([]);
  const receipts = result.policies.flatMap(({ receipts: rows }) => rows);
  // The census is the receipt, and it is the whole liveness claim: a policy withheld, blinded or pointed at
  // an empty root would file a zero here, which `receiptFailures` turns into a refusal rather than a clean
  // run. Asserting the DERIVED count instead of `> 0` is what makes a shrunken closure visible.
  expect(receipts.filter((receipt) => receipt.source === "devtools-frontend-assets")).toEqual([
    { kind: "resource", source: "devtools-frontend-assets", resources: liveMemberCount(), unresolved: 0 },
  ]);
  // And every DECLARED door was acquired exactly once — the other half of the liveness question, because an
  // unconsumed declaration is a receipt-phase refusal while a consumed-but-ignored one is silent.
  expect(
    receipts
      .filter((receipt) => receipt.kind === "resource" && receipt.source !== "devtools-frontend-assets")
      .map(({ source }) => source)
      .toSorted(),
  ).toEqual(["devtools-closure", "installed-package:playwright-core:text:browsers.json", "installed-package:playwright-test:metadata"]);
});

test("a corrupted pin on the REAL closure is reported through the policy — silent-because-dead cannot pass as clean", () => {
  const pin = JSON.parse(readFileSync(join(REPO_ROOT, DEVTOOLS_CLOSURE_PIN), "utf8")) as Record<string, unknown>;
  // A checksum that is well-formed (the pin still PARSES) but wrong, so the finding comes from the contract
  // rather than from a schema refusal — the arm that proves the manifest bytes are really compared.
  pin["manifestSha256"] = createHash("sha256").update("planted: not the committed manifest").digest("hex");
  const result = runOverReal({ [DEVTOOLS_CLOSURE_PIN]: `${JSON.stringify(pin, null, 2)}\n` });

  expect(result.toolErrors).toEqual([]);
  expect(result.authority.effectiveFindings.map(({ token, file }) => [token, file])).toEqual([["asset-contract", DEVTOOLS_CLOSURE_PIN]]);
  expect(result.authority.effectiveFindings[0]?.message).toContain("manifest checksum does not match the tuple pin");
});

test("the closure root the policy reads is the one the repository actually ships", () => {
  // A cheap two-sided anchor: the derived census is non-trivial and the three control documents are in it.
  // Without this, the overlay arms above would still pass over an empty directory the day the root moves.
  const members = new Set(
    readdirSync(CLOSURE_ROOT, { withFileTypes: true, recursive: true })
      .filter((entry) => entry.isFile())
      .map((entry) => relative(CLOSURE_ROOT, join(entry.parentPath, entry.name))),
  );

  expect(members).toContain("pin.json");
  expect(members).toContain("manifest.json");
  expect(members).toContain("licenses.json");
  expect(members.size).toBe(liveMemberCount());
});
