// Gate: no-raw-color-in-css (UI-Architecture-and-Layout.md / D43) — the CSS arm of the color-token seal
// (the className arm is `no-color-literals`, the inline-style arm is `no-off-token-inline-style`): a raw
// color literal (`#rrggbb`, or a bare `rgb()/hsl()/oklch()/oklab()/lab()/lch()` NOT deriving from a token)
// written into a packages/{ui,client}/src/**/*.css file bypasses the theme. The ONLY sanctioned home for
// raw color literals is the GENERATED token file `packages/ui/src/styles/theme.css` (tokens.json →
// `pnpm --filter @orb/ui tokens:build`). Token-DERIVED colors — `oklch(from var(--color-*) l c h / α)`, or
// any declaration referencing `var(--…)` — are ON-token and pass. ALLOWLIST is a both-directions ratchet
// (motion-token-purity precedent): a listed file that no longer holds a raw color REDS.
import { existsSync, globSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { GateDescriptor } from "../contract.ts";
import type { Violation } from "../harness.ts";

/** Real-tree anchor (GATE-AUTHORING.md §4.5) — a synthetic conformance temp dir only holds an example's
 *  own files, so the stale arm needs proof this is a real run. Deliberately NOT the ALLOWLIST row's own path
 *  (that would be the mode-B blind spot: a deleted token home never exists either). */
const ANCHOR = "packages/ui/src/tokens/index.ts";

/** The ONE sanctioned raw-color home → reason. `theme.css` is the GENERATED DTCG token surface where every
 *  oklch color literal is DEFINED; regenerated by `pnpm --filter @orb/ui tokens:build`. Stale (ratchet down)
 *  the day the token system emits no raw color literal here. */
const ALLOWLIST: Record<string, string> = {
  "packages/ui/src/styles/theme.css":
    "the generated DTCG token home — tokens.json → theme.css is the ONE place raw oklch color literals are DEFINED (the theme itself); regenerated by `pnpm --filter @orb/ui tokens:build`.",
};

const MESSAGE =
  "raw color literal in CSS (UI-Architecture-and-Layout.md / D43) — a hex or a non-token rgb()/hsl()/oklch() " +
  "value bypasses the theme and breaks theme switching: use a var(--color-*) token, or the token-derived " +
  "relative form `oklch(from var(--color-*) l c h / α)`. Raw color literals live ONLY in the generated theme.css.";

const STALE_ENTRY_MESSAGE_PREFIX =
  "ALLOWLIST entry has NO raw color literal any more — the raw colors moved onto tokens (ratchet down): delete the stale row in no-raw-color-in-css.ts: ";

// A hex literal is ALWAYS raw. A color FUNCTION is raw only when its line does not reference a token var —
// `oklch(from var(--color-x) …)` and `hsl(var(--h) …)` derive from a token and are on-token.
const HEX_RE = /#[0-9a-fA-F]{3,8}\b/u;
const COLOR_FN_RE = /\b(?:rgb|rgba|hsl|hsla|oklch|oklab|lab|lch)\s*\(/u;

/** Does one CSS line carry a raw (non-token-derived) color literal? */
function hasRawColor(line: string): boolean {
  if (HEX_RE.test(line)) {
    return true;
  }
  return COLOR_FN_RE.test(line) && !line.includes("var(--");
}

/** 1-based lines of every raw-color declaration in one CSS file's text. */
function offenceLines(text: string): number[] {
  const lines: number[] = [];
  const rows = text.split("\n");
  for (let i = 0; i < rows.length; i += 1) {
    if (hasRawColor(rows[i] ?? "")) {
      lines.push(i + 1);
    }
  }
  return lines;
}

/** Scan every CSS file in the two src trees (fs, not ts-morph — CSS isn't in the Project). Returns new
 *  offenders + which allowlisted files still carry a raw color (for the two-sided stale arm). */
function scanCss(root: string): { violations: Violation[]; seenAllowlisted: Set<string> } {
  const violations: Violation[] = [];
  const seenAllowlisted = new Set<string>();
  const files = [...globSync("packages/ui/src/**/*.css", { cwd: root }), ...globSync("packages/client/src/**/*.css", { cwd: root })];
  for (const rel of files) {
    const lines = offenceLines(readFileSync(join(root, rel), "utf8"));
    if (rel in ALLOWLIST) {
      if (lines.length > 0) {
        seenAllowlisted.add(rel);
      }
      continue;
    }
    for (const line of lines) {
      violations.push({ file: rel, line, message: MESSAGE });
    }
  }
  return { violations, seenAllowlisted };
}

const GATE_SELF = "scripts/check/gates/no-raw-color-in-css.ts";

export const gate: GateDescriptor = {
  name: "no-raw-color-in-css",
  docRow: "UI-Architecture-and-Layout.md / D43",
  status: "active",
  scopeSafety: "whole-project",
  fsBacked: true,
  message: MESSAGE,
  fix: "use a var(--color-*) token, or the token-derived relative form oklch(from var(--color-*) l c h / α); raw color literals live only in the generated theme.css.",
  run: (ctx) => {
    const { violations, seenAllowlisted } = scanCss(ctx.root);
    for (const v of violations) {
      ctx.report({ file: v.file, line: v.line, column: 0, message: v.message });
    }
    // The stale arm is a whole-tree claim — never fire it below project scope or off the real-tree anchor.
    if (ctx.scope.kind !== "project" || !existsSync(join(ctx.root, ANCHOR))) {
      return;
    }
    for (const rel of Object.keys(ALLOWLIST)) {
      // NOT existsSync-guarded on the row's own path — that is the mode-(B) blind spot (a deleted token
      // home never exists either). `seenAllowlisted` is set only when the file exists AND still holds a raw
      // color, so "never seen" covers both a fixed file (A) and a gone one (B).
      if (!seenAllowlisted.has(rel)) {
        ctx.report({
          file: GATE_SELF,
          line: 1,
          column: 0,
          message: `${STALE_ENTRY_MESSAGE_PREFIX}"${rel}" — scripts/check/gates/no-raw-color-in-css.ts`,
        });
      }
    }
  },
  mustFlag: [
    {
      files: { "packages/client/src/features/x/x.css": ".a {\n  color: #ff0000;\n}\n" },
      expect: { messageIncludes: "raw color literal in CSS" },
      why: "a raw hex color (#ff0000) in a feature CSS file — bypasses the theme, RED",
    },
    {
      files: { "packages/ui/src/x/x.css": ".a {\n  background: oklch(0.5 0.2 30);\n}\n" },
      expect: { messageIncludes: "raw color literal in CSS" },
      why: "a raw oklch literal NOT deriving from a token var — RED (the theme.css token-definition shape, but outside the sanctioned home)",
    },
    {
      // Mode-(B) proof (GATE-AUTHORING.md §4.3b/§4.4): the anchor exists (a real run) but NONE of the
      // ALLOWLIST .css paths do — the shape of a deleted/renamed token home. Every row must RED.
      files: { [ANCHOR]: "export const x = 1;\n" },
      expect: { messageIncludes: "ALLOWLIST entry has NO raw color literal" },
      why: "the real-tree anchor exists but no ALLOWLIST row's .css does (mode-B: gone from the tree) — every row must RED, not silently pass",
    },
  ],
  mustPass: [
    {
      files: { "packages/ui/src/x/ok.css": ".a {\n  background: oklch(from var(--color-primary) l c h / 0.2);\n}\n" },
      why: "the token-derived relative form oklch(from var(--color-*) …) — on-token, passes",
    },
    {
      files: { "packages/client/src/features/x/ok.css": ".a {\n  color: var(--color-foreground);\n}\n" },
      why: "a bare var(--color-*) token reference — on-token, passes",
    },
    {
      files: { "packages/ui/src/styles/theme.css": ":root {\n  --color-primary: oklch(0.7 0.1 250);\n}\n" },
      why: "the sanctioned token home (theme.css) with raw oklch definitions — the ONE allowlisted raw-color home, passes",
    },
  ],
};
