import { readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { CHAT_TRIGGER_TYPES, DOMAIN_TRIGGER_TYPES } from "@orb/contracts/automation";
import { PROMPT_TRANSFORM_POINTS } from "@orb/contracts/chat";
import {
  HOST_FUNCTION_CAPABILITY,
  PLUGIN_ANCHOR_TIERS,
  PLUGIN_CAPABILITIES,
  PLUGIN_COMMAND_PLACEMENT_TARGETS,
  PLUGIN_SURFACE_ANCHORS,
  PLUGIN_SURFACE_TIERS,
  PLUGIN_TIER_REGISTRAR,
  UI_PROXYABLE_HOST_FUNCTIONS,
} from "@orb/contracts/plugin";
import { createPluginAuthorSupport } from "../packages/plugin-toolchain/src/support-model.ts";

const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUTPUT_PATH = join(REPO_ROOT, "packages", "plugin-toolchain", "src", "support.generated.ts");

const support = createPluginAuthorSupport({
  capabilities: PLUGIN_CAPABILITIES,
  hostFunctionCapability: HOST_FUNCTION_CAPABILITY,
  uiProxyableHostFunctions: UI_PROXYABLE_HOST_FUNCTIONS,
  chatEventHooks: CHAT_TRIGGER_TYPES,
  domainEventHooks: DOMAIN_TRIGGER_TYPES,
  promptTransformPoints: PROMPT_TRANSFORM_POINTS,
  surfaceAnchors: PLUGIN_SURFACE_ANCHORS,
  surfaceTiers: PLUGIN_SURFACE_TIERS,
  anchorTiers: PLUGIN_ANCHOR_TIERS,
  tierRegistrar: PLUGIN_TIER_REGISTRAR,
  commandPlacements: PLUGIN_COMMAND_PLACEMENT_TARGETS,
});

const output = [
  "// Generated by scripts/generate-plugin-author-support.ts from the application contract registries.",
  'import type { PluginAuthorSupport } from "./support-model.ts";',
  "",
  `export const PLUGIN_AUTHOR_SUPPORT = ${JSON.stringify(support, null, 2)} as const satisfies PluginAuthorSupport;`,
  "",
].join("\n");

if (process.argv[2] === "--check") {
  let current = "";
  try {
    current = await readFile(OUTPUT_PATH, "utf8");
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) {
      throw error;
    }
  }
  if (current !== output) {
    process.stderr.write(`${OUTPUT_PATH} is stale; run node scripts/generate-plugin-author-support.ts\n`);
    process.exitCode = 1;
  }
} else {
  const temporary = `${OUTPUT_PATH}.tmp-${process.pid}`;
  try {
    await writeFile(temporary, output);
    await rename(temporary, OUTPUT_PATH);
  } finally {
    await rm(temporary, { force: true });
  }
}
