// The DTCG → derived-theme codegen (UI-Architecture §3, D42): src/tokens/tokens.json is the ONE
// design-value source; this script derives BOTH src/styles/theme.css (the Tailwind v4 @theme block)
// AND src/tokens/index.ts (the typed TS map). The generated artifacts are committed;
// tests/ui/tokens/index.test.ts re-runs generateArtifacts() and diffs — hand-editing either output,
// or editing tokens.json without regenerating, FAILS the test ("derived, never hand-authored" as a
// machine invariant, not a hope). Run: pnpm --filter @orb/ui tokens:build
//
// Style Dictionary v5 (docs said v4 — delta recorded in proposed/ui-package-design.md §3/§10; the
// v5 API used here: `new StyleDictionary(config)` + `exportPlatform()` for reference resolution).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import StyleDictionary from "style-dictionary";
import type { DesignTokens } from "style-dictionary/types";

const HERE = dirname(fileURLToPath(import.meta.url));
const TOKENS_JSON = join(HERE, "src/tokens/tokens.json");
const THEME_CSS = join(HERE, "src/styles/theme.css");
const TOKENS_TS = join(HERE, "src/tokens/index.ts");

const HEADER =
  "GENERATED by tokens.build.ts from src/tokens/tokens.json — DO NOT EDIT.\n" +
  " * Regenerate: pnpm --filter @orb/ui tokens:build (freshness is test-enforced).";

interface FlatToken {
  readonly path: readonly string[];
  readonly value: unknown;
}

/** A pointer-conditional override: the token's fine-pointer value (DTCG `$extensions["orb.pointerFine"]`). */
interface FineOverride {
  readonly path: readonly string[];
  readonly value: string;
}

/** A DTCG value → its CSS string (cubicBezier arrays become cubic-bezier(); numbers stringify). */
function renderValue(value: unknown): string {
  if (Array.isArray(value)) {
    return `cubic-bezier(${value.join(", ")})`;
  }
  return String(value);
}

/** `["color","user-bubble"]` → `--color-user-bubble` (group name IS the Tailwind v4 namespace). */
function cssVarName(path: readonly string[]): string {
  return `--${path.join("-")}`;
}

function renderThemeCss(tokens: readonly FlatToken[]): string {
  const lines = tokens.map((t) => `  ${cssVarName(t.path)}: ${renderValue(t.value)};`);
  return `/* ${HEADER}\n */\n@theme {\n${lines.join("\n")}\n}\n`;
}

/**
 * The pointer-conditional override block (D62 P1, UI-Arch §4b axis 3). The `@theme` block above
 * carries the COARSE-first control heights (the ≥44px touch floor holds by default); fine pointers
 * narrow them here. Emitted UNLAYERED on purpose: an unlayered `:root` custom-property override
 * beats the `@layer theme` value regardless of source order (verified against the Tailwind v4
 * compiler), so the fine values win wherever a `height: var(--spacing-control-*)` utility resolves.
 * The narrowed values live in `tokens.json` (`$extensions["orb.pointerFine"]`) — this script carries
 * no design literals.
 */
function renderPointerFineBlock(overrides: readonly FineOverride[]): string {
  if (overrides.length === 0) {
    return "";
  }
  const lines = overrides.map((o) => `    ${cssVarName(o.path)}: ${o.value};`);
  return `\n@media (pointer: fine) {\n  :root {\n${lines.join("\n")}\n  }\n}\n`;
}

/** Collect `$extensions["orb.pointerFine"]` fine-pointer values from the RAW DTCG source (literal
 *  dimensions — no `{references}` to resolve, so the un-transformed source is the right input). */
function collectPointerFine(
  node: Record<string, unknown>,
  path: readonly string[],
  out: FineOverride[],
): void {
  if ("$value" in node) {
    const ext = (node["$extensions"] as Record<string, unknown> | undefined)?.["orb.pointerFine"];
    if (typeof ext === "string") {
      out.push({ path, value: ext });
    }
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$") || typeof child !== "object" || child === null) {
      continue;
    }
    collectPointerFine(child as Record<string, unknown>, [...path, key], out);
  }
}

function renderTokensTs(tokens: readonly FlatToken[]): string {
  const entries = tokens.map((t) => {
    const key = t.path.join(".");
    const value = renderValue(t.value);
    return `  "${key}": { cssVar: "${cssVarName(t.path)}", value: ${JSON.stringify(value)} },`;
  });
  const varOpen = "`var(${";
  const varClose = "TOKENS[path].cssVar})`";
  return [
    `/** ${HEADER} */`,
    "",
    "/** Token → `{ cssVar, value }`: `cssVar` for CSS (theme-overridable); `value` is the static literal, for consumers that can't resolve `var()` (canvas chart libs, `parseFloat`). */",
    "export const TOKENS = {",
    ...entries,
    "} as const;",
    "",
    "export type TokenPath = keyof typeof TOKENS;",
    "",
    "/** `var(--…)` reference for a token — the ONE way runtime code names a token. */",
    "export function cssVar(path: TokenPath): string {",
    `  return ${varOpen}${varClose};`,
    "}",
    "",
  ].join("\n");
}

export async function generateArtifacts(): Promise<{ themeCss: string; tokensTs: string }> {
  const source = JSON.parse(readFileSync(TOKENS_JSON, "utf8")) as DesignTokens;
  const sd = new StyleDictionary({
    tokens: source,
    usesDtcg: true,
    log: { verbosity: "silent" },
    platforms: { flat: { files: [] } },
  });
  // exportPlatform resolves {references} against the raw values (no transforms registered).
  const dictionary = await sd.exportPlatform("flat");
  const flat: FlatToken[] = [];
  const walk = (node: Record<string, unknown>, path: readonly string[]): void => {
    if ("$value" in node) {
      flat.push({ path, value: node["$value"] });
      return;
    }
    for (const [key, child] of Object.entries(node)) {
      if (key.startsWith("$") || typeof child !== "object" || child === null) {
        continue;
      }
      walk(child as Record<string, unknown>, [...path, key]);
    }
  };
  walk(dictionary as Record<string, unknown>, []);
  const fine: FineOverride[] = [];
  collectPointerFine(source as unknown as Record<string, unknown>, [], fine);
  return {
    themeCss: renderThemeCss(flat) + renderPointerFineBlock(fine),
    tokensTs: renderTokensTs(flat),
  };
}

// tsx entrypoint (`pnpm --filter @orb/ui tokens:build`): write the committed artifacts.
if (process.argv[1] !== undefined && process.argv[1].endsWith("tokens.build.ts")) {
  const { themeCss, tokensTs } = await generateArtifacts();
  writeFileSync(THEME_CSS, themeCss);
  writeFileSync(TOKENS_TS, tokensTs);
}
