// The DTCG → derived-theme codegen (UI-Architecture §3, D42): src/tokens/tokens.json is the ONE
// design-value source; this script derives THREE artifacts — src/styles/theme.css (the Tailwind v4
// @theme block + the [data-theme] seed blocks), src/tokens/index.ts (the typed TS map), and
// src/tokens/themes.gen.ts (the seed value-sets as TS, re-exported by index). The generated artifacts
// are committed; tests/ui/tokens/index.test.ts re-runs generateArtifacts() and diffs — hand-editing any
// output, or editing tokens.json without regenerating, FAILS the test ("derived, never hand-authored"
// as a machine invariant, not a hope). Run: pnpm --filter @orb/ui tokens:build
//
// WHY the value-sets are their OWN module (2026-08-02, the 10-palette default-character pack): one seed
// palette emits ~37 lines, so a growing roster pushed the single index past the 450-line
// `component-size-ui` cap. The split keeps each artifact legible and wears the repo's generated-file
// name (`*.gen.ts` — the same convention as client's routeTree.gen.ts, already exempted by BOTH size
// gates' SKIP_RE and by biome's files.includes). index.ts re-exports it, so no consumer import moves.
//
// Style Dictionary v5 (docs said v4 — delta recorded in proposed/ui-package-design.md §3/§10; the
// v5 API used here: `new StyleDictionary(config)` + `exportPlatform()` for reference resolution).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import StyleDictionary from "style-dictionary";
import type { DesignTokens } from "style-dictionary/types";
import { THEME_SCOPE_EMIT_VARS } from "./src/content/theme-scope/clamp.ts";
import { assertNoNearDuplicateColors } from "./tokens.near-duplicate.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const TOKENS_JSON = join(HERE, "src/tokens/tokens.json");
const THEMES_DIR = join(HERE, "src/tokens/themes");
const THEME_CSS = join(HERE, "src/styles/theme.css");
const TOKENS_TS = join(HERE, "src/tokens/index.ts");
const THEMES_TS = join(HERE, "src/tokens/themes.gen.ts");
/** The specifier index.ts re-exports the value-sets from (extension-less — the package's TS resolution). */
// Extension-ful: node's type-stripping does no extensionless resolution, and `nodenext` makes the
// bare form a compile error (tsx-shedding stages 1/4). The GENERATOR owns this string, so a regen
// must keep it — that is why it is fixed here and not only in the emitted file.
const THEMES_MODULE = "./themes.gen.ts";

// The exact token-path coverage every seed value-set must carry: each EMITTED `--color-*` (the
// themeable surface, from clamp.ts) plus color.scrim (SEED_COVERED). A value-set with a missing or
// extra path fails the build — this is what makes the seed palettes un-driftable against the emit set.
const SEED_VALUE_SET_PATHS: ReadonlySet<string> = new Set([
  ...THEME_SCOPE_EMIT_VARS.filter((v) => v.startsWith("--color-")).map((v) => `color.${v.slice("--color-".length)}`),
  "color.scrim",
]);

const HEADER =
  "GENERATED by tokens.build.ts from src/tokens/tokens.json — DO NOT EDIT.\n" +
  " * Regenerate: pnpm --filter @orb/ui tokens:build (freshness is test-enforced).";

interface FlatToken {
  readonly path: readonly string[];
  readonly value: unknown;
}

/** A pointer-conditional override: the token's fine-pointer value (DTCG `$extensions["orb.pointerFine"]`). */
interface FineOverride {
  readonly path: readonly string[];
  readonly value: string;
}

/** A DTCG value → its CSS string (cubicBezier arrays become cubic-bezier(); numbers stringify). */
function renderValue(value: unknown): string {
  if (Array.isArray(value)) {
    return `cubic-bezier(${value.join(", ")})`;
  }
  return String(value);
}

/** `["color","user-bubble"]` → `--color-user-bubble` (group name IS the Tailwind v4 namespace). */
function cssVarName(path: readonly string[]): string {
  return `--${path.join("-")}`;
}

function renderThemeCss(tokens: readonly FlatToken[]): string {
  const lines = tokens.map((t) => `  ${cssVarName(t.path)}: ${renderValue(t.value)};`);
  return `/* ${HEADER}\n */\n@theme {\n${lines.join("\n")}\n}\n`;
}

/**
 * The pointer-conditional override block (D62 P1, UI-Arch §4b axis 3). The `@theme` block above
 * carries the COARSE-first control heights (the ≥44px touch floor holds by default); fine pointers
 * narrow them here. Emitted UNLAYERED on purpose: an unlayered `:root` custom-property override
 * beats the `@layer theme` value regardless of source order (verified against the Tailwind v4
 * compiler), so the fine values win wherever a `height: var(--spacing-control-*)` utility resolves.
 * The narrowed values live in `tokens.json` (`$extensions["orb.pointerFine"]`) — this script carries
 * no design literals.
 */
function renderPointerFineBlock(overrides: readonly FineOverride[]): string {
  if (overrides.length === 0) {
    return "";
  }
  const lines = overrides.map((o) => `    ${cssVarName(o.path)}: ${o.value};`);
  return `\n@media (pointer: fine) {\n  :root {\n${lines.join("\n")}\n  }\n}\n`;
}

/** Collect `$extensions["orb.pointerFine"]` fine-pointer values from the RAW DTCG source (literal
 *  dimensions — no `{references}` to resolve, so the un-transformed source is the right input). */
function collectPointerFine(node: Record<string, unknown>, path: readonly string[], out: FineOverride[]): void {
  if ("$value" in node) {
    const ext = (node["$extensions"] as Record<string, unknown> | undefined)?.["orb.pointerFine"];
    if (typeof ext === "string") {
      out.push({ path, value: ext });
    }
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$") || typeof child !== "object" || child === null) {
      continue;
    }
    collectPointerFine(child as Record<string, unknown>, [...path, key], out);
  }
}

function renderTokensTs(tokens: readonly FlatToken[]): string {
  const entries = tokens.map((t) => {
    const key = t.path.join(".");
    const value = renderValue(t.value);
    return `  "${key}": { cssVar: "${cssVarName(t.path)}", value: ${JSON.stringify(value)} },`;
  });
  const varOpen = "`var(${";
  const varClose = "TOKENS[path].cssVar})`";
  return [
    `/** ${HEADER} */`,
    "",
    "/** Token → `{ cssVar, value }`: `cssVar` for CSS (theme-overridable); `value` is the static literal, for consumers that can't resolve `var()` (canvas chart libs, `parseFloat`). */",
    "export const TOKENS = {",
    ...entries,
    "} as const;",
    "",
    "export type TokenPath = keyof typeof TOKENS;",
    "",
    "/** `var(--…)` reference for a token — the ONE way runtime code names a token. */",
    "export function cssVar(path: TokenPath): string {",
    `  return ${varOpen}${varClose};`,
    "}",
    "",
    "/** The seed [data-theme] value-sets — their own generated module (see tokens.build.ts), re-exported here so `@orb/ui/tokens` stays the ONE import for every token surface. */",
    `export { SEED_THEME_VALUE_SETS } from "${THEMES_MODULE}";`,
    "",
  ].join("\n");
}

/** A loaded + validated seed value-set: its `[data-theme]` name, native color-scheme, and ordered vars. */
interface SeedTheme {
  readonly name: string;
  readonly colorScheme: "light" | "dark";
  /** `[--color-…, oklch(…)]` in the value-set's own key order (drives both the CSS and the TS emit). */
  readonly vars: ReadonlyArray<readonly [name: string, value: string]>;
}

/** Flatten a value-set's `color` group into `{ "color.x": "$value" }` in insertion (key) order. */
function flattenValueSet(node: Record<string, unknown>, path: readonly string[], out: Map<string, string>): void {
  if ("$value" in node) {
    out.set(path.join("."), String(node["$value"]));
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$") || typeof child !== "object" || child === null) {
      continue;
    }
    flattenValueSet(child as Record<string, unknown>, [...path, key], out);
  }
}

/**
 * Load + VALIDATE every `src/tokens/themes/*.json` seed value-set (deterministic filename order),
 * failing the build with a precise message on any violation: (a) `$colorScheme` ∈ {light,dark};
 * (b) the token-path set is EXACTLY SEED_VALUE_SET_PATHS (no missing, no extra); (c) every path exists
 * in the base tokens.json; (d) every `$value` is an `oklch(` literal (the house seed-color format).
 * `basePaths` is the flat set of resolved base-token paths — the value-set can only re-value a token
 * the base already declares.
 */
function loadSeedThemes(basePaths: ReadonlySet<string>): SeedTheme[] {
  const files = readdirSync(THEMES_DIR)
    .filter((f) => f.endsWith(".json"))
    .sort();
  return files.map((file) => {
    const name = file.slice(0, -".json".length);
    const fail = (msg: string): never => {
      throw new Error(`seed value-set src/tokens/themes/${file}: ${msg}`);
    };
    const raw = JSON.parse(readFileSync(join(THEMES_DIR, file), "utf8")) as Record<string, unknown>;
    const colorScheme = raw["$colorScheme"];
    if (colorScheme !== "light" && colorScheme !== "dark") {
      fail(`$colorScheme must be "light" or "dark" (got ${JSON.stringify(colorScheme)})`);
    }
    const flat = new Map<string, string>();
    flattenValueSet(raw, [], flat);
    const present = new Set(flat.keys());
    const missing = [...SEED_VALUE_SET_PATHS].filter((p) => !present.has(p));
    const extra = [...present].filter((p) => !SEED_VALUE_SET_PATHS.has(p));
    if (missing.length > 0 || extra.length > 0) {
      fail(`token paths must be EXACTLY the EMITTED colors + color.scrim — missing [${missing.join(", ")}], extra [${extra.join(", ")}]`);
    }
    for (const [path, value] of flat) {
      if (!basePaths.has(path)) {
        fail(`${path} is not a token in tokens.json`);
      }
      if (!value.startsWith("oklch(")) {
        fail(`${path} must be an oklch(…) literal (got ${JSON.stringify(value)})`);
      }
    }
    return {
      name,
      colorScheme: colorScheme as "light" | "dark",
      vars: [...flat].map(([path, value]) => [`--${path.replace(".", "-")}`, value] as const),
    };
  });
}

/**
 * The seed-theme block, emitted AFTER the pointer-fine block. The base `:root { color-scheme: dark }`
 * is emitted FIRST here (moved out of globals.css) so the light seed's `color-scheme: light` flip wins
 * by source order within this one generated file. Each `[data-theme]` block is unlayered + self-complete.
 */
function renderSeedThemesBlock(themes: readonly SeedTheme[]): string {
  const parts = ["\n:root {\n  color-scheme: dark;\n}\n"];
  for (const theme of themes) {
    const lines = theme.vars.map(([name, value]) => `  ${name}: ${value};`);
    parts.push(`\n[data-theme="${theme.name}"] {\n  color-scheme: ${theme.colorScheme};\n${lines.join("\n")}\n}\n`);
  }
  return parts.join("");
}

/** The generated `themes.gen.ts` module — the seed palettes as a typed TS record (parallel to TOKENS),
 *  re-exported by index.ts. Its own file so a growing palette roster never pushes the token map past the
 *  `component-size-ui` cap (see the header). */
function renderSeedThemesTs(themes: readonly SeedTheme[]): string {
  const lines = [
    `/** ${HEADER} */`,
    "",
    "/** The seed [data-theme] value-sets, GENERATED from src/tokens/themes/*.json — the same palettes theme.css emits as `[data-theme=…]` blocks, exposed to TS (e.g. the theme picker) so a seed palette has ONE source. */",
    "export const SEED_THEME_VALUE_SETS = {",
  ];
  for (const theme of themes) {
    lines.push(`  ${JSON.stringify(theme.name)}: {`);
    lines.push(`    colorScheme: ${JSON.stringify(theme.colorScheme)},`);
    lines.push("    vars: {");
    for (const [name, value] of theme.vars) {
      lines.push(`      ${JSON.stringify(name)}: ${JSON.stringify(value)},`);
    }
    lines.push("    },");
    lines.push("  },");
  }
  lines.push("} as const;");
  lines.push("");
  return lines.join("\n");
}

export async function generateArtifacts(): Promise<{ themeCss: string; tokensTs: string; themesTs: string }> {
  const source = JSON.parse(readFileSync(TOKENS_JSON, "utf8")) as DesignTokens;
  // Runs on the RAW source, BEFORE resolution: a `{color.x}` reference is the one-token answer, and a
  // resolved dictionary can no longer tell a reference from a hand-authored twin (tokens.near-duplicate.ts).
  assertNoNearDuplicateColors(source as unknown as Record<string, unknown>);
  const sd = new StyleDictionary({
    tokens: source,
    usesDtcg: true,
    log: { verbosity: "silent" },
    platforms: { flat: { files: [] } },
  });
  // exportPlatform resolves {references} against the raw values (no transforms registered).
  const dictionary = await sd.exportPlatform("flat");
  const flat: FlatToken[] = [];
  const walk = (node: Record<string, unknown>, path: readonly string[]): void => {
    if ("$value" in node) {
      flat.push({ path, value: node["$value"] });
      return;
    }
    for (const [key, child] of Object.entries(node)) {
      if (key.startsWith("$") || typeof child !== "object" || child === null) {
        continue;
      }
      walk(child as Record<string, unknown>, [...path, key]);
    }
  };
  walk(dictionary as Record<string, unknown>, []);
  const fine: FineOverride[] = [];
  collectPointerFine(source as unknown as Record<string, unknown>, [], fine);
  const seedThemes = loadSeedThemes(new Set(flat.map((t) => t.path.join("."))));
  return {
    themeCss: renderThemeCss(flat) + renderPointerFineBlock(fine) + renderSeedThemesBlock(seedThemes),
    tokensTs: renderTokensTs(flat),
    themesTs: renderSeedThemesTs(seedThemes),
  };
}

// tsx entrypoint (`pnpm --filter @orb/ui tokens:build`): write the committed artifacts.
if (process.argv[1]?.endsWith("tokens.build.ts")) {
  const { themeCss, tokensTs, themesTs } = await generateArtifacts();
  writeFileSync(THEME_CSS, themeCss);
  writeFileSync(TOKENS_TS, tokensTs);
  writeFileSync(THEMES_TS, themesTs);
}
