// Front door for the boot protocol's step functions, run in order by entry/lifecycle.ts.

export type { DistributedPluginApplier, DistributedPluginApplierDeps } from "./apply-distributed-plugins.ts";
export { createDistributedPluginApplier } from "./apply-distributed-plugins.ts";
export type { BackfillPluginProvenanceOnBootDeps } from "./backfill-plugin-provenance.ts";
export { backfillPluginProvenanceOnBoot } from "./backfill-plugin-provenance.ts";
export type { BootSecrets, BootSecretsDeps } from "./boot-secrets.ts";
export { settleBootSecrets } from "./boot-secrets.ts";
export type { BootDisclaimerInput, BootDisclaimerLine, BootSecretProvenance } from "./disclaimer.ts";
export { BOOT_DISCLAIMER_TOPICS, composeBootDisclaimer } from "./disclaimer.ts";
export type { HealLegacyBackgroundPinsDeps } from "./heal-legacy-background-pins.ts";
export { healLegacyBackgroundPinsOnBoot } from "./heal-legacy-background-pins.ts";
export type { LocalLightPrefetchPlanDeps } from "./local-light-prefetch.ts";
export { planLocalLightPrefetch } from "./local-light-prefetch.ts";
export type { MigrateDeps } from "./migrate.ts";
export { DB_LAUNCHED, resolveMigrationsFolder, runBootMigrations } from "./migrate.ts";
export type { DataLayoutMigrationReport, DataLayoutMove, MigrateDataLayoutDeps } from "./migrate-data-layout.ts";
export { LAYOUT_JOURNAL, migrateDataLayout } from "./migrate-data-layout.ts";
export type { MigrateHandoffOfferVocabDeps } from "./migrate-handoff-offer-vocab.ts";
export { migrateHandoffOfferVocabOnBoot } from "./migrate-handoff-offer-vocab.ts";
export type { MigratePluginToolWireNamesDeps } from "./migrate-plugin-tool-wire-names.ts";
export { migratePluginToolWireNamesOnBoot } from "./migrate-plugin-tool-wire-names.ts";
export type { MigrateProseSlotVocabDeps } from "./migrate-prose-slot-vocab.ts";
export { migrateProseSlotVocabOnBoot } from "./migrate-prose-slot-vocab.ts";
export type { OwnerClaimAnnouncement } from "./owner-claim.ts";
export { announceOwnerClaim } from "./owner-claim.ts";
export type { ReactivatePluginsDeps, ReactivatePluginsReport } from "./reactivate-plugins.ts";
export { reactivatePluginsOnBoot } from "./reactivate-plugins.ts";
export type { ReclaimLocksDeps } from "./reclaim-locks.ts";
export { reclaimLocksOnBoot } from "./reclaim-locks.ts";
export type { RepairStaleJoinSeqDeps } from "./repair-stale-join-seq.ts";
export { repairStaleJoinSeqOnBoot } from "./repair-stale-join-seq.ts";
export type { SeedCasSchedulesDeps } from "./seed-cas-schedules.ts";
export { seedCasSchedules } from "./seed-cas-schedules.ts";
export type { SeedCredentialDeps } from "./seed-credential.ts";
export { seedCredentialFromEnv } from "./seed-credential.ts";
export type { SeedDefaultBackgroundsDeps } from "./seed-default-backgrounds.ts";
export { seedDefaultBackgrounds } from "./seed-default-backgrounds.ts";
export type { DefaultPersonaSeeder, DefaultPersonaSeederDeps } from "./seed-default-persona.ts";
export { createDefaultPersonaSeeder } from "./seed-default-persona.ts";
export type { SeedDefaultPersonaDeps } from "./seed-default-persona-step.ts";
export { seedDefaultPersona } from "./seed-default-persona-step.ts";
export type { SeedDefaultPresetDeps } from "./seed-default-preset.ts";
export { seedDefaultPreset } from "./seed-default-preset.ts";
export type { ExamplePluginSeeder, ExamplePluginSeederDeps } from "./seed-example-plugins.ts";
export { createExamplePluginSeeder } from "./seed-example-plugins.ts";
export type { SeedExamplePluginsDeps } from "./seed-example-plugins-step.ts";
export { seedExamplePlugins } from "./seed-example-plugins-step.ts";
export type { SeedLocalLightDeps } from "./seed-local-light.ts";
export { createLocalLightUserSeed, seedLocalLightOnBoot } from "./seed-local-light.ts";
export type { SeedOwnerDeps } from "./seed-owner.ts";
export { seedOwner } from "./seed-owner.ts";
export type { SeedThemesDeps } from "./seed-themes.ts";
export { seedThemes } from "./seed-themes.ts";
export type { SeedUserContentDeps, UserContentSeeder, UserContentSeederDeps } from "./seed-user-content.ts";
export { createUserContentSeeder, seedUserContent } from "./seed-user-content.ts";
