import { existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, realpathSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const AGENTS_PATH = join(ROOT, "AGENTS.md");
const CLAUDE_AGENTS_DIR = join(ROOT, ".claude", "agents");
const CLAUDE_RULES_DIR = join(ROOT, ".claude", "rules");
const CLAUDE_SKILLS_DIR = join(ROOT, ".claude", "skills");
const CODEX_AGENTS_DIR = join(ROOT, ".codex", "agents");
const CODEX_SKILLS_DIR = join(ROOT, ".agents", "skills");
const FRONTMATTER_PATTERN = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/;
const RULE_IMPORTS_BEGIN = "<!-- codex-claude-rules:begin — generated by pnpm agents:sync -->";
const RULE_IMPORTS_END = "<!-- codex-claude-rules:end -->";
const RULE_IMPORTS_PATTERN = /<!-- codex-claude-rules:begin[^\n]*-->[\s\S]*?<!-- codex-claude-rules:end -->/;
const MAX_ARGV_LENGTH = 3;

const ROLE_MODELS: Readonly<Record<string, string>> = {
  executor: "gpt-5.6-sol",
  forge: "gpt-5.6-sol",
  "mech-executor": "gpt-5.6-sol",
  "security-executor": "gpt-5.6-sol",
  "side-eye": "gpt-5.6-sol",
  stickler: "gpt-5.6-sol",
  verifier: "gpt-5.6-sol",
};

interface ClaudeAgent {
  readonly body: string;
  readonly description: string;
  readonly effort: string;
  readonly name: string;
  readonly skills: readonly string[];
}

function requiredString(record: Readonly<Record<string, unknown>>, key: string, filename: string): string {
  const value = record[key];
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`${filename}: frontmatter.${key} must be a non-empty string`);
  }
  return value;
}

function parseFrontmatter(source: string, filename: string): Readonly<Record<string, unknown>> {
  const record: Record<string, unknown> = {};
  for (const line of source.split("\n")) {
    const separator = line.indexOf(":");
    if (separator <= 0) {
      throw new Error(`${filename}: frontmatter entries must be one-line key/value pairs`);
    }
    const key = line.slice(0, separator).trim();
    const raw = line.slice(separator + 1).trim();
    if (key in record) {
      throw new Error(`${filename}: duplicate frontmatter key ${key}`);
    }
    if (raw.startsWith('"')) {
      record[key] = JSON.parse(raw);
    } else if (raw.startsWith("[") && raw.endsWith("]")) {
      record[key] = raw
        .slice(1, -1)
        .split(",")
        .map((value) => value.trim().replace(/^['"]|['"]$/g, ""));
    } else {
      record[key] = raw;
    }
  }
  return record;
}

function parseClaudeAgent(filename: string, source: string): ClaudeAgent {
  const match = FRONTMATTER_PATTERN.exec(source);
  if (match === null) {
    throw new Error(`${filename}: expected YAML frontmatter followed by an agent body`);
  }
  const frontmatter = match[1];
  const body = match[2];
  if (frontmatter === undefined || body === undefined) {
    throw new Error(`${filename}: frontmatter parser did not capture both required sections`);
  }

  const record = parseFrontmatter(frontmatter, filename);
  const skillsValue = record["skills"];
  const skills = Array.isArray(skillsValue)
    ? skillsValue.map((skill) => {
        if (typeof skill !== "string" || skill.trim() === "") {
          throw new Error(`${filename}: every frontmatter.skills entry must be a non-empty string`);
        }
        return skill;
      })
    : [];

  return {
    body: body.trimEnd(),
    description: requiredString(record, "description", filename),
    effort: requiredString(record, "effort", filename),
    name: requiredString(record, "name", filename),
    skills,
  };
}

function codexPreamble(agent: ClaudeAgent, filename: string): string {
  const lines = [
    "Codex compatibility: this role body is shared with Claude Code. The TOML model and reasoning-effort settings are authoritative; treat Claude model names and tool names below as intent labels and use the Codex tools available in this session.",
  ];
  const paths = agent.skills.map((skill) => {
    const path = `.agents/skills/${skill}/SKILL.md`;
    if (!existsSync(join(ROOT, path))) {
      throw new Error(`${filename}: Claude skill ${skill} has no Codex-readable source at ${path}`);
    }
    return `\`${path}\``;
  });
  if (paths.length > 0) {
    lines.push(`Read ${paths.join(", ")} in full before applying the shared role instructions below.`);
  }
  return `${lines.join(" ")}\n\n`;
}

export function renderCodexAgent(filename: string, source: string): string {
  const agent = parseClaudeAgent(filename, source);
  const model = ROLE_MODELS[agent.name];
  if (model === undefined) {
    throw new Error(`${filename}: add an explicit Codex model mapping for role ${agent.name}`);
  }
  if (agent.body.includes("'''")) {
    throw new Error(`${filename}: agent body contains the TOML literal-string delimiter`);
  }

  const preamble = codexPreamble(agent, filename);
  return [
    `# Generated from .claude/agents/${filename} by pnpm agents:sync. Do not edit this file directly.`,
    `name = ${JSON.stringify(agent.name)}`,
    `description = ${JSON.stringify(agent.description)}`,
    `model = ${JSON.stringify(model)}`,
    `model_reasoning_effort = ${JSON.stringify(agent.effort)}`,
    "developer_instructions = '''",
    `${preamble}${agent.body}`,
    "'''",
    "",
  ].join("\n");
}

function sourceFilenames(): readonly string[] {
  return readdirSync(CLAUDE_AGENTS_DIR)
    .filter((filename) => filename.endsWith(".md"))
    .toSorted();
}

function codexFilename(sourceFilename: string): string {
  return `${sourceFilename.slice(0, -".md".length)}.toml`;
}

function renderedRuleImports(): string {
  const imports = readdirSync(CLAUDE_RULES_DIR)
    .filter((filename) => filename.endsWith(".md"))
    .toSorted()
    .map((filename) => `@.claude/rules/${filename}`);
  if (imports.length === 0) {
    throw new Error(".claude/rules must contain at least one Markdown rule");
  }
  return [RULE_IMPORTS_BEGIN, ...imports, RULE_IMPORTS_END].join("\n");
}

function replaceRuleImports(source: string): string {
  if (!RULE_IMPORTS_PATTERN.test(source)) {
    throw new Error("AGENTS.md is missing the generated Claude rule import block");
  }
  return source.replace(RULE_IMPORTS_PATTERN, renderedRuleImports());
}

function skillsLinkProblem(): string | null {
  if (!(existsSync(CODEX_SKILLS_DIR) && lstatSync(CODEX_SKILLS_DIR).isSymbolicLink())) {
    return ".agents/skills must be a symlink to .claude/skills";
  }
  if (realpathSync(CODEX_SKILLS_DIR) !== realpathSync(CLAUDE_SKILLS_DIR)) {
    return ".agents/skills does not resolve to .claude/skills";
  }
  return null;
}

export function codexAgentSyncProblems(): readonly string[] {
  const expectedFiles = sourceFilenames().map(codexFilename);
  const actualFiles = readdirSync(CODEX_AGENTS_DIR)
    .filter((filename) => filename.endsWith(".toml"))
    .toSorted();
  const problems: string[] = [];

  const skillsProblem = skillsLinkProblem();
  if (skillsProblem !== null) {
    problems.push(skillsProblem);
  }

  const agentsSource = readFileSync(AGENTS_PATH, "utf8");
  if (!agentsSource.includes(renderedRuleImports())) {
    problems.push("AGENTS.md Claude rule imports are stale; run pnpm agents:sync");
  }

  if (JSON.stringify(actualFiles) !== JSON.stringify(expectedFiles)) {
    problems.push(`agent file set differs: expected ${expectedFiles.join(", ")}; found ${actualFiles.join(", ")}`);
  }

  for (const sourceFilename of sourceFilenames()) {
    const targetFilename = codexFilename(sourceFilename);
    const targetPath = join(CODEX_AGENTS_DIR, targetFilename);
    const expected = renderCodexAgent(sourceFilename, readFileSync(join(CLAUDE_AGENTS_DIR, sourceFilename), "utf8"));
    if (!existsSync(targetPath) || readFileSync(targetPath, "utf8") !== expected) {
      problems.push(`${targetFilename} is stale; run pnpm agents:sync`);
    }
  }
  return problems;
}

function syncCodexAgents(): void {
  mkdirSync(CODEX_AGENTS_DIR, { recursive: true });
  const sourceFiles = sourceFilenames();
  const expectedTargets = new Set(sourceFiles.map(codexFilename));

  for (const targetFilename of readdirSync(CODEX_AGENTS_DIR).filter((filename) => filename.endsWith(".toml"))) {
    if (!expectedTargets.has(targetFilename)) {
      unlinkSync(join(CODEX_AGENTS_DIR, targetFilename));
    }
  }
  for (const sourceFilename of sourceFiles) {
    const targetFilename = codexFilename(sourceFilename);
    const rendered = renderCodexAgent(sourceFilename, readFileSync(join(CLAUDE_AGENTS_DIR, sourceFilename), "utf8"));
    writeFileSync(join(CODEX_AGENTS_DIR, targetFilename), rendered);
  }
  writeFileSync(AGENTS_PATH, replaceRuleImports(readFileSync(AGENTS_PATH, "utf8")));
  const skillsProblem = skillsLinkProblem();
  if (skillsProblem !== null) {
    throw new Error(skillsProblem);
  }
  process.stdout.write(
    `synced ${sourceFiles.length} Claude roles, ${readdirSync(CLAUDE_RULES_DIR).filter((filename) => filename.endsWith(".md")).length} rule imports, and the shared skill tree\n`,
  );
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  if (process.argv.length > MAX_ARGV_LENGTH || (process.argv[2] !== undefined && process.argv[2] !== "--check")) {
    throw new Error("usage: pnpm agents:sync [--check]");
  }
  if (process.argv[2] === "--check") {
    const problems = codexAgentSyncProblems();
    if (problems.length > 0) {
      throw new Error(problems.join("\n"));
    }
    process.stdout.write(`checked ${sourceFilenames().length} Codex agent manifests: current\n`);
  } else {
    syncCodexAgents();
  }
}
