// Generated by scripts/generate-plugin-author-support.ts from the application contract registries.
import type { PluginAuthorSupport } from "./support-model.ts";

export const PLUGIN_AUTHOR_SUPPORT = {
  schemaVersion: 1,
  runtimes: {
    main: {
      world: "main",
      execution: "server-quickjs",
      sourceEntry: "main.ts",
      sdkEntry: "@orb/plugin-sdk/main",
      entrypoint: "orb.host(1)",
      dom: false,
      hostFunctions: [
        "chat.current",
        "chat.listMessages",
        "chat.getVariables",
        "chat.listCharacters",
        "chat.applyVariableOps",
        "chat.surfaceQuickReply",
        "chat.requestTurn",
        "worldInfo.listBooks",
        "worldInfo.listEntries",
        "worldInfo.upsertEntry",
        "assets.read",
        "search.documents",
        "variables.get",
        "variables.set",
        "variables.delete",
        "storage.get",
        "storage.set",
        "storage.delete",
        "storage.compareAndSet",
        "storage.list",
        "notifications.post",
        "imagery.generatePicture",
        "llm.quiet",
        "databank.ingest",
        "character.ingest",
        "character.ingestAsset",
        "character.setCardData",
        "character.getCardData",
        "events.on",
        "pubsub.emit",
        "pubsub.on",
        "tools.register",
        "transforms.register",
        "transforms.registerDisplay",
        "macros.register",
        "net.fetch",
        "net.fetchAsset",
        "ui.register",
        "ui.setState",
        "ui.registerCommand",
        "ui.toast",
        "ui.openDialog",
        "ui.registerFrame",
      ],
      localHelpers: ["clock", "random", "ids", "log", "tokens"],
    },
    ui: {
      world: "ui",
      execution: "browser-quickjs-worker",
      sourceEntry: "ui.ts",
      sdkEntry: "@orb/plugin-sdk/ui",
      entrypoint: "orb.ui(1)",
      dom: false,
      hostFunctions: [
        "chat.listMessages",
        "chat.getVariables",
        "variables.get",
        "variables.set",
        "variables.delete",
        "storage.get",
        "storage.set",
        "storage.delete",
        "storage.list",
        "storage.compareAndSet",
      ],
      localHelpers: ["clock", "random", "log", "tokens", "render", "onEvent"],
    },
    frame: {
      world: "frame",
      execution: "isolated-browser-frame",
      sourceEntry: "frame.ts",
      sdkEntry: "@orb/plugin-sdk/frame",
      entrypoint: "parent.postMessage",
      dom: true,
      hostFunctions: [
        "chat.listMessages",
        "chat.getVariables",
        "variables.get",
        "variables.set",
        "variables.delete",
        "storage.get",
        "storage.set",
        "storage.delete",
        "storage.list",
        "storage.compareAndSet",
      ],
      localHelpers: ["orbPluginAssetUrl"],
    },
  },
  capabilities: [
    {
      capability: "chat.read",
      functions: {
        main: ["chat.current", "chat.listMessages", "chat.getVariables", "chat.listCharacters"],
        ui: ["chat.listMessages", "chat.getVariables"],
        frame: ["chat.listMessages", "chat.getVariables"],
      },
    },
    {
      capability: "chat.variables.write",
      functions: {
        main: ["chat.applyVariableOps"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "chat.quick_reply",
      functions: {
        main: ["chat.surfaceQuickReply"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "chat.transform",
      functions: {
        main: ["transforms.register", "transforms.registerDisplay", "macros.register"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "worldinfo.read",
      functions: {
        main: ["worldInfo.listBooks", "worldInfo.listEntries"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "worldinfo.write",
      functions: {
        main: ["worldInfo.upsertEntry"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "global_vars",
      functions: {
        main: ["variables.get", "variables.set", "variables.delete"],
        ui: ["variables.get", "variables.set", "variables.delete"],
        frame: ["variables.get", "variables.set", "variables.delete"],
      },
    },
    {
      capability: "storage.kv",
      functions: {
        main: ["storage.get", "storage.set", "storage.delete", "storage.compareAndSet", "storage.list"],
        ui: ["storage.get", "storage.set", "storage.delete", "storage.compareAndSet", "storage.list"],
        frame: ["storage.get", "storage.set", "storage.delete", "storage.compareAndSet", "storage.list"],
      },
    },
    {
      capability: "assets.read",
      functions: {
        main: ["assets.read"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "search.query",
      functions: {
        main: ["search.documents"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "notify",
      functions: {
        main: ["notifications.post"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "ui.surface",
      functions: {
        main: ["ui.register", "ui.setState", "ui.registerCommand", "ui.toast", "ui.openDialog"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "ui.frame",
      functions: {
        main: ["ui.registerFrame"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "turn.trigger",
      functions: {
        main: ["chat.requestTurn"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "imagery.generate",
      functions: {
        main: ["imagery.generatePicture"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "llm.quiet",
      functions: {
        main: ["llm.quiet"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "databank.ingest",
      functions: {
        main: ["databank.ingest"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "character.ingest",
      functions: {
        main: ["character.ingest", "character.ingestAsset"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "character.card_state",
      functions: {
        main: ["character.setCardData", "character.getCardData"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "events.subscribe",
      functions: {
        main: ["events.on"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "plugin_events",
      functions: {
        main: ["pubsub.emit", "pubsub.on"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "tools.register",
      functions: {
        main: ["tools.register"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "net.fetch",
      functions: {
        main: ["net.fetch"],
        ui: [],
        frame: [],
      },
    },
    {
      capability: "net.fetch_asset",
      functions: {
        main: ["net.fetchAsset"],
        ui: [],
        frame: [],
      },
    },
  ],
  hooks: {
    events: {
      chat: [
        {
          name: "chatOpened",
          world: "main",
        },
        {
          name: "messageCommitted",
          world: "main",
        },
        {
          name: "messageEdited",
          world: "main",
        },
        {
          name: "variantSelected",
          world: "main",
        },
        {
          name: "turnStarted",
          world: "main",
        },
        {
          name: "turnCompleted",
          world: "main",
        },
        {
          name: "turnAborted",
          world: "main",
        },
        {
          name: "worldInfoActivated",
          world: "main",
        },
        {
          name: "personaSwitched",
          world: "main",
        },
        {
          name: "chatCreated",
          world: "main",
        },
        {
          name: "reactionsChanged",
          world: "main",
        },
        {
          name: "messageHidden",
          world: "main",
        },
        {
          name: "messagesDeleted",
          world: "main",
        },
        {
          name: "chatUpdated",
          world: "main",
        },
        {
          name: "wiEntryAttached",
          world: "main",
        },
        {
          name: "wiEntryDetached",
          world: "main",
        },
      ],
      domain: [
        {
          name: "character.updated",
          world: "main",
        },
        {
          name: "asset.created",
          world: "main",
        },
        {
          name: "persona.updated",
          world: "main",
        },
        {
          name: "world-info.updated",
          world: "main",
        },
      ],
    },
    promptTransforms: [
      {
        name: "user_input",
        world: "main",
      },
      {
        name: "assembled_dynamic",
        world: "main",
      },
    ],
  },
  ui: {
    surfaces: [
      {
        anchor: "settings",
        tiers: ["static", "scripted", "frame"],
        registrationWorld: "main",
      },
      {
        anchor: "chat-flank",
        tiers: ["static", "scripted", "frame"],
        registrationWorld: "main",
      },
      {
        anchor: "chat-settings-section",
        tiers: ["static", "scripted"],
        registrationWorld: "main",
      },
      {
        anchor: "tool-card",
        tiers: ["static", "scripted", "frame"],
        registrationWorld: "main",
      },
      {
        anchor: "message-footer",
        tiers: ["static"],
        registrationWorld: "main",
      },
      {
        anchor: "page",
        tiers: ["static", "scripted", "frame"],
        registrationWorld: "main",
      },
      {
        anchor: "dialog",
        tiers: ["static", "scripted", "frame"],
        registrationWorld: "main",
      },
    ],
    tiers: [
      {
        tier: "static",
        registrar: "ui.register",
        registrationWorld: "main",
        executionWorld: "main",
      },
      {
        tier: "scripted",
        registrar: "ui.register",
        registrationWorld: "main",
        executionWorld: "ui",
      },
      {
        tier: "frame",
        registrar: "ui.registerFrame",
        registrationWorld: "main",
        executionWorld: "frame",
      },
    ],
    commandPlacements: [
      {
        target: "composer-action",
        registrationWorld: "main",
      },
      {
        target: "composer-media",
        registrationWorld: "main",
      },
    ],
  },
} as const satisfies PluginAuthorSupport;
