// @orb/contracts/plugin — the guest↔host wire vocabulary for the D46 code sandbox. The
// membrane a guest sees (`PluginHostV1` + opaque handles + supporting projections — host-v1.ts), the
// install-time manifest + capability axis (manifest.ts), the capability→function completeness map, and
// the two guest-observable membrane errors (errors.ts). The runtime lives in `infra/plugin-host`
// (landed); the registry/lifecycle/grants lives in `domain/plugin`. This node imports nothing above
// contracts (the package cake) and is the ONE home for these shapes — the domain derives, never re-spells.

/** The `plugin.getLog` page CEILING, enforced at the transport trust boundary (the `CHARACTER_LIST_MAX_LIMIT`
 *  precedent) — a plugin's execution log is a growing per-plugin catalog, so an over-bound ask is a
 *  BAD_REQUEST rather than an unbounded log fetch (the #45 class). */
export const PLUGIN_LOG_LIST_MAX_LIMIT = 500;

/** The `plugin.transformForDisplay` input CEILING (seam 14, U6) — the longest rendered row a
 *  viewer's client may submit for display transformation, enforced at the transport trust boundary. It is
 *  generous against real prose (a very long message is a few thousand characters) and it exists because the
 *  round-trip is PER ROW: without it a transcript render is an unbounded upload per visible message. A row over
 *  the cap is a BAD_REQUEST, and the client's fallback is the text it already has — the same degrade a skipped
 *  transform produces, so an over-long row renders un-annotated rather than not at all. */
export const PLUGIN_DISPLAY_TEXT_MAX_CHARS = 32_000;

export type { InvocationChat, PluginBridge, PluginInvocationLiveness } from "./bridge.ts";
export { HostVersionError, PluginCapabilityError, PluginSuggestedError } from "./errors.ts";
export type { PluginFrameCall, PluginFrameMintRequest, PluginFrameMintResponse, PluginFrameResult } from "./frame.ts";
export {
  PLUGIN_FRAME_CALL_REFUSED,
  PLUGIN_FRAME_CALLS_IN_FLIGHT_MAX,
  PLUGIN_FRAME_DOC_PREFIX,
  PLUGIN_FRAME_MINT_BODY_MAX_BYTES,
  PLUGIN_FRAME_RESULT_KEY,
  PLUGIN_FRAME_ROUTE,
  parsePluginFrameCall,
  pluginFrameMintRequestSchema,
  pluginFrameMintResponseSchema,
  pluginFrameResultMessage,
  pluginFrameUrl,
} from "./frame.ts";
export type { PluginGrantTask } from "./grant-tasks.ts";
export { pluginGrantTasks } from "./grant-tasks.ts";
export type {
  ChatHandle,
  HostFunctionRef,
  PluginAssetView,
  PluginCharacterView,
  PluginHostV1,
  PluginLogLevel,
  PluginMessageView,
  PluginQuietOptions,
  PluginQuietSchema,
  PluginSearchHit,
  PluginVariableOp,
  PluginWorldBookView,
  PluginWorldEntryUpsert,
  PluginWorldEntryView,
  UiProxyableHostFunction,
} from "./host-v1.ts";
export {
  HOST_FUNCTION_CAPABILITY,
  isUiProxyableHostFunction,
  PLUGIN_ASSET_READ_MAX_BYTES,
  PLUGIN_LOG_LEVELS,
  PLUGIN_QUIET_IMAGES_MAX,
  PLUGIN_SEARCH_RESULTS_MAX,
  UI_PROXYABLE_HOST_FUNCTIONS,
} from "./host-v1.ts";
export type { PluginOrigin, PluginStatus } from "./lifecycle.ts";
export { PLUGIN_ORIGINS, PLUGIN_STATUSES } from "./lifecycle.ts";
export type { PluginBuiltAgainst, PluginCapability, PluginManifest, PluginProviderContribution, PluginSlug } from "./manifest.ts";
export {
  NET_HOSTS_MAX,
  PLUGIN_CAPABILITIES,
  PLUGIN_HOST_VERSIONS,
  PLUGIN_MAIN_ENTRY,
  PLUGIN_MANIFEST_ENTRY,
  PLUGIN_PROVIDERS_MAX,
  PLUGIN_SLUG_MAX,
  PLUGIN_TOOL_NAME_LOCAL_MAX,
  PLUGIN_TOOL_WIRE_NAME_MAX,
  PLUGIN_UI_ASSET_ENTRY_RE,
  PLUGIN_UI_ASSET_MAX_BYTES,
  PLUGIN_UI_ASSETS_DIR,
  PLUGIN_UI_ASSETS_MAX_COUNT,
  PLUGIN_UI_ASSETS_TOTAL_MAX_BYTES,
  PLUGIN_UI_ENTRY,
  pluginBuiltAgainstSchema,
  pluginManifestSchema,
  pluginNetHostSchema,
  pluginSlugSchema,
} from "./manifest.ts";
export type {
  PluginCommandRegistration,
  PluginDisplayTransformRegistration,
  PluginEventSubscription,
  PluginHandlerRef,
  PluginInstance,
  PluginInvokeArgs,
  PluginMacroRegistration,
  PluginPubsubSubscription,
  PluginSurfaceRegistration,
  PluginToolRegistration,
  PluginTransformRegistration,
} from "./registrations.ts";
export {
  PLUGIN_PUBSUB_NAME_RE,
  PLUGIN_PUBSUB_PAYLOAD_MAX_BYTES,
  PLUGIN_PUBSUB_SUBSCRIPTIONS_MAX,
  PLUGIN_TOOL_NAME_PREFIX,
  pluginCardStateKey,
  pluginToolWireName,
} from "./registrations.ts";
export type { PluginSuggestedAct, PluginSuggestedActKind } from "./suggestion.ts";
export { PLUGIN_SUGGESTED_ACT_KINDS, summarizePluginAct } from "./suggestion.ts";
export type {
  PluginBadgeIntent,
  PluginBadgeNode,
  PluginBoundBoolean,
  PluginBoundGridTile,
  PluginBoundKeyValueRow,
  PluginBoundNumber,
  PluginBoundString,
  PluginButtonNode,
  PluginButtonVariant,
  PluginCommandArgSpec,
  PluginCommandArgs,
  PluginCommandArgsFor,
  PluginCommandArgType,
  PluginCommandArgValue,
  PluginCommandRegistrationMeta,
  PluginConfirmButtonNode,
  PluginFrameBody,
  PluginGapToken,
  PluginGridNode,
  PluginGridTile,
  PluginIconName,
  PluginIconNode,
  PluginImageAspect,
  PluginImageNode,
  PluginKeyValueNode,
  PluginKeyValueRow,
  PluginListNode,
  PluginMarkdownNode,
  PluginMasterDetailNode,
  PluginMeterNode,
  PluginNodeKind,
  PluginNumberFieldNode,
  PluginPageHero,
  PluginPageStage,
  PluginPageStageKind,
  PluginPrimaryArbitration,
  PluginRowNode,
  PluginSearchBarNode,
  PluginSectionNode,
  PluginSelectNode,
  PluginSelectOption,
  PluginSliderNode,
  PluginStackNode,
  PluginStateBinding,
  PluginSurfaceAnchor,
  PluginSurfaceNode,
  PluginSurfaceRegistrationMeta,
  PluginSurfaceSpec,
  PluginSurfaceTier,
  PluginTabsNode,
  PluginTextFieldNode,
  PluginTextNode,
  PluginTextVoice,
  PluginTierRegistrar,
  PluginToast,
  PluginToastLevel,
  PluginToggleNode,
  PluginToolCardState,
  PluginUiOutcome,
} from "./ui.ts";
export {
  coercePluginCommandArgs,
  PLUGIN_ANCHOR_PRIMARY_ALLOWED,
  PLUGIN_ANCHOR_TIERS,
  PLUGIN_BADGE_INTENTS,
  PLUGIN_BUTTON_VARIANTS,
  PLUGIN_COMMAND_ARG_NAME_RE,
  PLUGIN_COMMAND_ARG_TYPES,
  PLUGIN_COMMAND_ARGS_DECLARED_MAX,
  PLUGIN_COMMAND_ARGS_MAX,
  PLUGIN_COMMAND_DESCRIBE_MAX,
  PLUGIN_COMMAND_ENUM_VALUES_MAX,
  PLUGIN_COMMAND_NAME_RE,
  PLUGIN_FOOTER_MAX_DEPTH,
  PLUGIN_FOOTER_MAX_NODES,
  PLUGIN_FOOTER_NODE_KIND_ALLOWED,
  PLUGIN_FRAME_CSS_MAX_CHARS,
  PLUGIN_FRAME_HTML_MAX_CHARS,
  PLUGIN_FRAME_SURFACES_MAX,
  PLUGIN_GAP_TOKENS,
  PLUGIN_GRID_TILES_MAX,
  PLUGIN_ICON_NAMES,
  PLUGIN_IMAGE_ASPECTS,
  PLUGIN_NODE_KINDS,
  PLUGIN_PAGE_STAGE_KINDS,
  PLUGIN_PAGE_STAGES_MAX,
  PLUGIN_ROWS_MAX,
  PLUGIN_SPEC_MAX_BYTES,
  PLUGIN_SPEC_MAX_DEPTH,
  PLUGIN_SPEC_MAX_NODES,
  PLUGIN_SURFACE_ANCHORS,
  PLUGIN_SURFACE_ID_RE,
  PLUGIN_SURFACE_TIERS,
  PLUGIN_SURFACE_TITLE_MAX,
  PLUGIN_TABS_OPTIONS_MAX,
  PLUGIN_TEXT_MAX_BYTES,
  PLUGIN_TEXT_VOICES,
  PLUGIN_TIER_REGISTRAR,
  PLUGIN_TIER_REGISTRARS,
  PLUGIN_TILE_TAGS_MAX,
  PLUGIN_TOAST_COOLDOWN_SECONDS,
  PLUGIN_TOAST_LEVELS,
  PLUGIN_TOAST_MAX_CHARS,
  PLUGIN_TOOL_NAME_RE,
  PLUGIN_UI_ENTRY_MAX_BYTES,
  PLUGIN_UI_HOST_CALL_ARGS_MAX_BYTES,
  PLUGIN_UI_HOST_CALL_RESULT_MAX_BYTES,
  PLUGIN_UI_OUTBOX_MAX,
  PLUGIN_UI_ROUTE,
  pluginBoundGridTileSchema,
  pluginBoundKeyValueRowSchema,
  pluginBoundSelectOptionSchema,
  pluginChildNodes,
  pluginCommandArgSpecSchema,
  pluginCommandArgsSchema,
  pluginCommandRegistrationMetaSchema,
  pluginFrameBodySchema,
  pluginSurfaceNodeSchema,
  pluginSurfaceRegistrationMetaSchema,
  pluginSurfaceSpecSchema,
  resolvePluginBoundAssetId,
  resolvePluginBoundBoolean,
  resolvePluginBoundKeyValueRows,
  resolvePluginBoundSelectOptions,
  resolvePluginBoundTabOptions,
  resolvePluginBoundTiles,
  resolvePluginPrimaryButton,
} from "./ui.ts";
