// foundation/observability/debug — front door for the /api/_debug surface (the dissolved `debug` domain,
// folded into observability). The route registrar + the two structural-injection ports `entry/` fills.

export {
  type AppSettingRow,
  type AutomationFireFilter,
  type AutomationFireRow,
  appSettingRows,
  automationFireRows,
  type CharacterDetailRow,
  type CharacterListRow,
  type ChatConfigRow,
  type ChatInspection,
  type ChatListRow,
  type ChatParticipantRow,
  characterDetailRow,
  characterListSummaries,
  characterPolicySweep,
  chatConfigRow,
  chatListSummaries,
  type IntegrityReport,
  inspectChatState,
  integrityProbe,
  type PersonaRow,
  type PresetRow,
  personaRows,
  presetRows,
  type RenderPolicyVerdict,
  type RpgGameRow,
  rpgGameForChat,
  tableCounts,
  type UserSettingsRow,
  userSettingsRows,
} from "./inspect/index.ts";
export {
  type AdminAuthChecker,
  type AssetInspector,
  BUG_REPORT_MAX_BODY_BYTES,
  createDebugAuthMiddleware,
  type DebugAuthOptions,
  type DebugRoutesOptions,
  type MemoryRecallInspector,
  type RpgTraceInspector,
  registerDebugRoutes,
  type SocketInspector,
  toDebugLimit,
  tokenMatches,
} from "./routes.ts";
export {
  isWireCaptureEnabled,
  recentTurnOutcomes,
  recentWireCaptures,
  recordTurnOutcome,
  recordWireCapture,
  resetWireCaptures,
  type WireCapture,
  type WireCaptureFilter,
  type WireOutcome,
  type WireToolCall,
  type WireWarning,
} from "./wire-capture.ts";
