// The SHIPPED provider rows — DATA in the one schema (`providerDefSchema`), checked at `tsc` through
// `satisfies` and parsed once at module load through the same zod a plugin/admin row goes through (§5.9-1).
// Most rows are `wire: openai-compat` + a `features` block and need ZERO code; adding a provider is a row
// here + the table test, never a `Record` entry.

import type { ProviderDefInput } from "./provider-schema.ts";

export const BUILTIN_PROVIDER_ROWS = [
  {
    id: "openrouter",
    label: "OpenRouter",
    wire: "openai-compat",
    dialect: "openrouter",
    auth: "apiKey",
    baseUrl: "https://openrouter.ai/api/v1",
    apis: ["chat-completions", "responses"],
    // The whole wire set. `rerank` rides the wire's plain-POST arm: OpenRouter answers `POST /rerank` with
    // the same `{ results: [{ index, relevance_score }] }` shape vLLM does (raw SDK 1.1.8 `rerankRerank`,
    // `pathToFunc("/rerank")`), so the row names the path like the vllm row does.
    features: { rerankPath: "/rerank" },
    catalog: "url",
    metered: true,
    docsUrl: "https://openrouter.ai/docs",
  },
  {
    id: "anthropic",
    label: "Anthropic",
    wire: "anthropic-messages",
    auth: "apiKey",
    baseUrl: "https://api.anthropic.com",
    apis: ["anthropic-messages"],
    catalog: "url",
    metered: true,
    docsUrl: "https://docs.anthropic.com",
  },
  {
    id: "claude-sub",
    label: "Claude subscription",
    wire: "agent-sdk",
    auth: "oauthToken",
    apis: ["agent-sdk"],
    catalog: "url",
    metered: false,
    docsUrl: "https://docs.anthropic.com/en/docs/claude-code",
  },
  {
    id: "openai",
    label: "OpenAI",
    wire: "openai-compat",
    dialect: "openai-compatible",
    auth: "apiKey",
    baseUrl: "https://api.openai.com/v1",
    apis: ["chat-completions"],
    serves: ["chat", "summarize", "structured", "embed", "generateImage"],
    features: {
      effort: "reasoning_effort",
      // gpt-5.x / o-series reject the SDK's `max_tokens` (measured 2026-09-20, `req_f68c8dc2e4a24908a2e5be64132edbc0`).
      outputCapField: "max_completion_tokens",
      images: "images-api",
      strictJson: "declared-only",
    },
    catalog: "url",
    metered: true,
    docsUrl: "https://platform.openai.com/docs",
  },
  {
    id: "vllm",
    label: "vLLM",
    wire: "openai-compat",
    dialect: "openai-compatible",
    auth: "endpoint",
    apis: ["chat-completions"],
    features: {
      prefill: "continue-final-message",
      strictJson: "default-on",
      effort: "reasoning_effort",
      sleep: {
        isSleepingPath: "/is_sleeping",
        wakePath: "/wake_up",
      },
      rerankPath: "/rerank",
      reasoningKeys: ["reasoning", "reasoning_content"],
      prefillSuppressesThinking: true,
    },
    catalog: "url",
    metered: false,
    docsUrl: "https://docs.vllm.ai",
  },
  {
    id: "lm-studio",
    label: "LM Studio",
    wire: "openai-compat",
    dialect: "openai-compatible",
    auth: "endpoint",
    apis: ["chat-completions"],
    features: {
      prefill: "none",
    },
    catalog: "url",
    metered: false,
    docsUrl: "https://lmstudio.ai/docs",
  },
  {
    id: "ollama",
    label: "Ollama",
    wire: "openai-compat",
    dialect: "openai-compatible",
    auth: "endpoint",
    apis: ["chat-completions"],
    features: {
      prefill: "none",
    },
    catalog: "url",
    metered: false,
    docsUrl: "https://docs.ollama.com",
  },
  {
    id: "custom-openai",
    label: "Custom OpenAI-compatible",
    wire: "openai-compat",
    dialect: "openai-compatible",
    auth: "endpoint",
    apis: ["chat-completions"],
    catalog: "url",
    metered: false,
  },
  {
    id: "local-light",
    label: "Built-in (this device)",
    wire: "local-light",
    auth: "none",
    apis: [],
    catalog: "builtin",
    metered: false,
  },
] as const satisfies readonly ProviderDefInput[];
