// Claude role manifest → Codex agent TOML. Touches the tree (it PROVES every declared skill has a
// Codex-readable source before promising the role can read it), so it lives in ops/, not lib/.
import { existsSync } from "node:fs";
import { join } from "node:path";
import { REPO_ROOT } from "../../_shared/artifacts.ts";
import { refuseDirectInvocation } from "../../_shared/entrypoint.ts";
import type { ClaudeAgent } from "../contract/types.ts";
import { parseClaudeAgent } from "../lib/frontmatter.ts";
import { ROLE_MODELS } from "../lib/paths.ts";

refuseDirectInvocation(import.meta.url, "pnpm agents:sync");

const TOML_LITERAL_DELIMITER = "'''";

function codexPreamble(agent: ClaudeAgent, filename: string): string {
  const lines = [
    "Codex compatibility: this role body is shared with Claude Code. The TOML model and reasoning-effort settings win. Read Claude model and tool names below as intent labels, and use the Codex tools in this session. `AGENTS.md` names the files to read first.",
  ];
  const paths = agent.skills.map((skill) => {
    const path = `.agents/skills/${skill}/SKILL.md`;
    if (!existsSync(join(REPO_ROOT, path))) {
      throw new Error(`${filename}: Claude skill ${skill} has no Codex-readable source at ${path}`);
    }
    return `\`${path}\``;
  });
  if (paths.length > 0) {
    lines.push(`Read ${paths.join(", ")} in full before you apply the role instructions below.`);
  }
  return `${lines.join(" ")}\n\n`;
}

/** The rendered `.codex/agents/<role>.toml` bytes — byte-compared by `--check`, so the renderer IS the
 *  staleness oracle. A body carrying the TOML literal-string delimiter would silently truncate the role
 *  instructions, so it refuses instead. */
export function renderCodexAgent(filename: string, source: string): string {
  const agent = parseClaudeAgent(filename, source);
  const model = ROLE_MODELS[agent.name];
  if (model === undefined) {
    throw new Error(`${filename}: add an explicit Codex model mapping for role ${agent.name}`);
  }
  if (agent.body.includes(TOML_LITERAL_DELIMITER)) {
    throw new Error(`${filename}: agent body contains the TOML literal-string delimiter`);
  }

  const preamble = codexPreamble(agent, filename);
  return [
    `# Generated from .claude/agents/${filename} by pnpm agents:sync. Do not edit this file directly.`,
    `name = ${JSON.stringify(agent.name)}`,
    `description = ${JSON.stringify(agent.description)}`,
    `model = ${JSON.stringify(model)}`,
    `model_reasoning_effort = ${JSON.stringify(agent.effort)}`,
    `developer_instructions = ${TOML_LITERAL_DELIMITER}`,
    `${preamble}${agent.body}`,
    TOML_LITERAL_DELIMITER,
    "",
  ].join("\n");
}
